### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by maedoc** [stan-dev/cmdstanpy#1]
#### Summary:
cmdstanpy does not support Python 2

#### Description:
Originally written for Python 3, cmdstanpy uses type annotations among other features of Python 3 that are not supported in Python 2, despite Python 2 still being widely used (official EOL in 2020).

#### Additional Information:
It would be not too much effort to support Python 2 by removing use of incompatible features, if there's demand.

#### Current Version:
v0.0

**Comment by mitzimorris** [comment]
on the one hand, python 2 compatible would lessen the install burden.

on the other hand, note that pandas no longer supports python 2 -
https://www.analyticsvidhya.com/blog/2018/04/pandas-will-drop-all-support-for-python-2-next-year/

**Comment by maedoc** [comment]
The current API uses dictionaries of arrays. I never went up the Pandas learning curve, but users say it’s great.  I’d suggest making it optional for now, and have a Pandas-savvy person implement a convenience API over what’s already done.

NumPy is the hard dependency, and it’s also dropping bug fix support for 2 in 2020.

We can leave the issue open and wait until someone complains, and spend the half hour to remove Py 3 specific bits.

**Comment by mitzimorris** [comment]
OK, it sounds like we should add the requirement that CmdStanPy is Python 2/3 agnostic.

looking at: https://docs.python.org/3/whatsnew/3.0.html - agreed that rewrites should be easy.

**Comment by ahartikainen** [comment]
Do we really need anything else than numpy? How lightweight you want to keep this?

**Comment by mitzimorris** [comment]
as lightweight as possible.
you're right - numpy's ndarrays should be sufficient for our data.

**Comment by mitzimorris** [comment]
reasons to support Python2:
 + less install burden for users

reasons to restrict CmdStanPy to Python3:
 + Python2 EOL is 7 months away (in theory) (as of May 2019)
 + Python3 language features improve code readability and maintainability; in particular, `@property` annotations and type hints - i.e., less coding burden for developers
 + using pandas, which says it won't support Python2 past 2020
 + most downstream analysis tools, e.g., ScikitLearn, require Python3

reluctantly closing this issue - won't fix.
