### ISSUE TITLE
install_cmdstan fails on W10

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#100]
#### Summary:

Running `python bin/install_cmdstan` fails on Windows 10.

Tested with `conda install m2w64-toolchain -c msys2` and `MAKE=mingw32-make`

and

RTools35

#### Description:

Trying to install on W10 leads to errors :

```
...
bin/cmdstan/stanc.o:stanc.cpp:(.text+0x13d4e): undefined reference to `stan::lang::block_var_decl::type() const'
...
bin/cmdstan/stanc.o:stanc.cpp:(.text$_ZN5boost6detail7variant15backup_assignerINS_7variantINS_17recursive_wrapperIN4stan4lang3nilEEEINS4_INS6_11int_literalEEENS4_INS6_14double_literalEEENS4_INS6_10array_exprEEENS4_INS6_11matrix_exprEEENS4_INS6_15row_vector_exprEEENS4_INS6_8variableEEENS4_INS6_3funEEENS4_INS6_12integrate_1dEEENS4_INS6_13integrate_odeEEENS4_INS6_21integrate_ode_controlEEENS4_INS6_14algebra_solverEEENS4_INS6_22algebra_solver_controlEEENS4_INS6_8map_rectEEENS4_INS6_8index_opEEENS4_INS6_15index_op_slicedEEENS4_INS6_14conditional_opEEENS4_INS6_9binary_opEEENS4_INS6_8unary_opEEEEEEE14construct_implISY_EEvPvPKv[_ZN5boost6detail7variant15backup_assignerINS_7variantINS_17recursive_wrapperIN4stan4lang3nilEEEINS4_INS6_11int_literalEEENS4_INS6_14double_literalEEENS4_INS6_10array_exprEEENS4_INS6_11matrix_exprEEENS4_INS6_15row_vector_exprEEENS4_INS6_8variableEEENS4_INS6_3funEEENS4_INS6_12integrate_1dEEENS4_INS6_13integrate_odeEEENS4_INS6_21integrate_ode_controlEEENS4_INS6_14algebra_solverEEENS4_INS6_22algebra_solver_controlEEENS4_INS6_8map_rectEEENS4_INS6_8index_opEEENS4_INS6_15index_op_slicedEEENS4_INS6_14conditional_opEEENS4_INS6_9binary_opEEENS4_INS6_8unary_opEEEEEEE14construct_implISY_EEvPvPKv]+0x26): undefined reference to `stan::lang::map_rect::map_rect(stan::lang::map_rect const&)'
...
collect2.exe: error: ld returned 1 exit status
make: *** [make/stanc:23: bin/stanc.exe] Error 1
```

#### Additional Information:

I have probably fixed this before, but currently, I don't remember what I did, so I added this issue and at the same time we can document the fix.

Works fine with Ubuntu 18

#### Current Version:

cmdstanpy master
cmdstan 2.20

**Comment by mitzimorris** [comment]
thank you so much for filing this!

I think other beta testers have seen this.   I will be doing a sprint session with the PyLadies here in NYC and will solicit volunteers to test/investigate further.

**Comment by ahartikainen** [comment]
Ok, I was just explicitly using CC and CXX for RTools, but apparently, it linked other tools to m2w64 tools. (I'm using the install_cxx function found in the PR to install RTools to ~/.cmdstanpy)

Doing this (for username: `user`):

    set PATH=C:\Users\user\.cmdstanpy\RTools\RTools35\mingw_64\bin;C:\Users\user\.cmdstanpy\RTools\RTools35\bin;%PATH%

Then `python -m cmdstanpy.install_cmdstan` works.

Now I need to figure out is there something missing from m2w64. (I'm running these in cmder (full)) so I still need to test this with basic cmd.exe.

**Comment by ahartikainen** [comment]
Ok, using RTools on cmd.exe works. (so that is great)

There are some missing tools (not installed) in conda, so I will need to see if this can be fixed for conda toolchains.

**Comment by mitzimorris** [comment]
not following - why would a python user have RTools?

**Comment by mitzimorris** [comment]
I got this report from Brian Parbhu (JuliaStan developer) - perhaps this is a win32 error?

```
C:\Users\brian\Anaconda3\envs\laptop_default_env\python.exe "C:\Program Files\JetBrains\PyCharm 2019.2\helpers\pydev\
\pydevconsole.py" --mode=client --port=51299

import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['C:\\Users\\brian\\PycharmProjects\\stan_cmdstanpy_tests', 'C:/Users/brian/PycharmProjects/stan_cmd\
stanpy_tests'])

PyDev console: starting.
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] on win32

runfile('C:/Users/brian/PycharmProjects/stan_cmdstanpy_tests/check_cmdstanpy_instal.py', wdir='C:/Users/brian/Pychar\
mProjects/stan_cmdstanpy_tests')

CmdStan version: 2.20.0
Install directory: C:\Users\brian\.cmdstanpy
Downloading CmdStan version 2.20.0
Download successful, file: C:\Users\brian\AppData\Local\Temp\tmpzkb0shv6
Unpacked download as cmdstan-2.20.0

Building cmdstan-2.20.0 binaries
Command "make build" failed
cc1plus.exe: sorry, unimplemented: 64-bit mode not compiled in
make: *** [src/cmdstan/stanc.d] Error 1
Process finished with exit code 3
```

**Comment by ahartikainen** [comment]
Not python user, but cmdstan user

**Comment by CatChenal** [comment]
Different installation error on Win10 with `install_cmdstan`.

This is my system:
```
OS: Windows 10, version='10.0.17134', 
      machine='AMD64',
      processor='Intel64 Family 6 Model 142 Stepping 10, GenuineIntel'
Python: 3.7.3
```

These are the steps I took:

1. I cloned my cmdstanpy fork locally, then ran:
```
pip install -e .
```
2. I activated my virtual environment (cmdstandev).

3. I attempted the CmdStan install with the cmdstanpy script:
```
(cmdstandev) C:\<repo path>\cmdstanpy>install_cmdstan
```
With the following results (with `<masked path details>` and blank lines added for legibility):
```
CmdStan version: 2.20.0
Building cmdstan-2.20.0 binaries

Traceback (most recent call last):
  File "C:\<envs path>\cmdstandev\Scripts\install_cmdstan-script.py", line 11, in <module>
    load_entry_point('cmdstanpy', 'console_scripts', 'install_cmdstan')()

  File "c:\<repo path>\cmdstanpy\cmdstanpy\install_cmdstan.py", line 193, in main
    install_version(cmdstan_version)

  File "c:\<repo path>\cmdstanpy\cmdstanpy\install_cmdstan.py", line 48, in install_version
    cmd, cwd=None, stdout=subprocess.PIPE, stderr=subprocess.PIPE

  File "C:\<envs path>\cmdstandev\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)

  File "C:\<envs path>\cmdstandev\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified
deleting tmpfiles dir: C:\Users\<me>\AppData\Local\Temp\tmppgtrdsvh
done
```
My guess is that the failure stems from this line (50) in the `install_version` method of the `install_cmdstan` module:
```
    stdout, stderr = proc.communicate()
```
My question is what is the file the system is looking for & cannot find?

**FYI**:  I've installed **PyStan** according to [their clear and simple instructions](https://pystan.readthedocs.io/en/latest/windows.html) and tested it with [this example](https://pystan.readthedocs.io/en/latest/optimizing.html) without any issue.

**Comment by ahartikainen** [comment]
Hi, what C++ toolchain do you have?

**Comment by mitzimorris** [comment]
we need to check the CmdStan manual to see if there is anything about setting correct MAKEFLAGS for the CmdStan makefile.  investigating

**Comment by ahartikainen** [comment]
Oh yes there are couple of things for Windows:

Install RTools and add bin and mingw_64/bin to PATH (before other)

Use mingw32-make

    SET PATH=C:\Rtools\bin;C:\Rtools\mingw_64\bin;%PATH%

    SET MAKE=mingw32-make.exe

**Comment by CatChenal** [comment]
> Hi, what C++ toolchain do you have? https://github.com/stan-dev/cmdstanpy/issues/100#issuecomment-521876560

I now have mingw-w64 since I used the PyStan installation procedures:
```
conda install libpython m2w64-toolchain -c msys2
```

**Comment by CatChenal** [comment]
CmdStan manual https://github.com/stan-dev/cmdstanpy/issues/100#issuecomment-522025480 @mitzimorris 
I went through that rabbit hole trying to install CmdStan manually. IMHO it is written by and for C++ developers. As the PyStan team has obviously solved the installation steps, why not learn from them?

**Comment by mitzimorris** [comment]
sorry - I should have checked myself.

**Comment by ahartikainen** [comment]
PyStan toolchain is currently missing some tools, so we currently need RTools. I'm trying to find conda based tools.

**Comment by CatChenal** [comment]
> PyStan toolchain is currently missing some tools, so we currently need RTools.

Sorry, I don't understand what you mean: I did not need any RTools to install PyStan.

**Comment by ahartikainen** [comment]
Tools that `make` uses to build cmdstan. PyStan uses only python tools, so no need for the extra tools (`m2w64-toolchain` does have some extra tools, but some are "missing")

**Comment by ahartikainen** [comment]
I think this is fixed with the use of `install_cxx_toolchain`

**Comment by mitzimorris** [comment]
@ahartikainen - is this solved and now tested via appveyor?  in which case, issue can be closed.

**Comment by ahartikainen** [comment]
Yes.

I hope in future we can have those few missing tools from conda, so we would not need to recommend different environments for pystan and cmdstanpy.

**Comment by Cartman0** [comment]
`cmdstan` and `cmdstanpy` supports working on Windows10 64 bit cmd ? 
it is hard to create C++ tool chain(MinGW64) env manually when I tried.

- [MinGW installer + `make` in MSYS](https://osdn.net/projects/mingw/releases/): only 32bit. when calling `python -m cmdstanpy.install_cmdstan`, `make build` failed: `sorry, unimplemented: 64-bit mode not compiled in`. 
- MSYS2: `make` command only use on MSYS2 console. not on cmd.
- Cygwin: `make` command only use on Cygwin(mintty) console. not on cmd.
- Win-builds: because dependent packages aren't  autoly installed, not found `intl-8.dll` when calling `gcc`.

how are you(s) working?

**Comment by mitzimorris** [comment]
hmm,  looks like we need more documentation on function `install_cxx_toolchain` -
https://github.com/stan-dev/cmdstanpy/blob/master/cmdstanpy/install_cxx_toolchain.py
(unit tests here:  https://github.com/stan-dev/cmdstanpy/blob/master/test/test_cxx_installation.py)

try this:

```
from cmdstanpy import install_cxx_toolchain
config = install_cxx_toolchain.get_config('C:\\RTools', True)
install_cxx_toolchain.get_toolchain_name()
```

**Comment by Cartman0** [comment]
@mitzimorris 
i see, if users install `rstan` and `RTools`, 
looks like sure only set PATHs `C:\Rtools\bin` and `C:\Rtools\mingw_64\bin`.

and, if asia user (ex. as me),  may encount unicode err in running `python -m cmdstanpy.install_cmdstan` on cmd. in this case, need `chcp 65001` before command.

**Comment by ahartikainen** [comment]
Hi, what kind of unicode error you have?

So on windows you can use RTools and also remember to set MAKE env var to `mingw32-make`.

I should create the some instructions. (Also I don't personally want to install stuff on C root, it just clutters the root and on many system needs admin rights, which one should not need to use)

The default install location for RTools with `install_cxx_toolchain` is `$HOME/.cmdstanpy`

**Comment by Cartman0** [comment]
@ahartikainen 
hi, set PATHs `C:\Rtools\bin` and `C:\Rtools\mingw_64\bin` of rstan so that cmdstanpy is working successfully in my env. 

> what kind of unicode error you have?
this is probably a error seen frequently on Windows Japanese edition cmd.
default character encoding is `cp932` (based on SHIFT-JIS) on windows-jp-cmd.
because it is, python on cmd is reading files with utf-8, so that it failed.
its solution is change encoding :`chcp 65001`.
