### ISSUE TITLE
install_cmdstan enable github version

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#101]
#### Summary:

Let's add an option to install the latest development from the github

#### Description:

I have noticed that it is quite easy to handle multiple CmdStan installations with CmdStanPy. It would be nice also to have an option for github version (`cmdstan-dev`)

This could be done with `--version=dev` or `--version=git`, which would cause

    git clone --recursive https://github.com/stan-dev/cmdstan.git %CMDSTANPYPATH%/cmdstan-dev

The default version should still be any released version, and then by some convenience function change to `cmdstan-dev`.

Also I think we could somehow hack the `set_cmdstan_path` function to take version name only, which would automatically find the version from the %CMDSTANPYPATH% folder.

#### Additional Information:
Provide any additional information here.

#### Current Version:

Latest git

**Comment by mitzimorris** [comment]
is this feature something that will benefit non-developers?

**Comment by ahartikainen** [comment]
Yes. (but the default should be the released version)

**Comment by mitzimorris** [comment]
OK, right now everything's in beta and we only have a master branch.  at what point do we need to go to master/develop and tags as in Stan/CmdStan/RStan etc?

**Comment by mitzimorris** [comment]
as outlined here:  https://github.com/stan-dev/stan/wiki/Dev:-Git-Process

**Comment by ahartikainen** [comment]
I'm not sure if we should go to develop - master cycle. Currently most repos (common python repos) only use master branch, because we publish in pypi and having develop / master doesn't offer anything for us.

**Comment by mitzimorris** [comment]
closing - we have develop branch and release scripts.
