### ISSUE TITLE
Support stan model as a string in `cmdstanpy.Model`

### ISSUE THREAD

**Issue by thomasjpfan** [stan-dev/cmdstanpy#102]
#### Summary:
Currently the workflow of developing a model in a jupyter notebook as follows:

1. Create jupyter notebook
2. Write stan model file
3. Compile model
4. Sample from model

If the compilation failed or if the sampling was not successful, one would need to jump out of the jupyter notebook, and edit the stan model file and go back into the notebook to compile and sample.

Since the model is not defined in the notebook, notebooks would need to embed the model definition into it as show in the [pyladies bayesian workshop notebook](https://github.com/nyc-pyladies/2019-cmdstanpy-bayesian-workshop/blob/master/notebooks/WWC2019.ipynb). The writer would need to keep the stan model and the embedded model in the jupyter notebook text in sync.

**Comment by ahartikainen** [comment]
For quick solution would be

    # like pystan
    stan_code = """..."""

    with open(stan_path, "w") as f:
        print(stan_code, file=f)

    # use stan_path for cmdstanpy

**Comment by thomasjpfan** [comment]
I agree that would work. My concern is how the current file centric API may detract from new users.

Since cmdstanpy uses a temporary folder for other operations, such as data loading from a json file, this concept can extend to the model files as well.

(These are my observations as an outsider coming from the python point of view.)

**Comment by mitzimorris** [comment]
the result would be that both the Stan program and the compiled model get written to tmp directory and then deleted at the end of the session.

I agree that the example notebook from the workbook has a nasty dependency.  this is a result of my limited experience in developing python notebooks.  the proper approach is to use some kind of include statement to make sure that the only copy of the program is the one on disk.

I don't think that this is a good solution to the problem, because it opens the door for worse ones, therefore I'm closing this issue.

**Comment by thomasjpfan** [comment]
If the `.stan` file is the single source of truth, the current file centric API design makes sense.

> the proper approach is to use some kind of include statement to make sure that the only copy of the program is the one on disk.

What kind of include statement do you have in mind?

**Comment by mitzimorris** [comment]
> What kind of include statement do you have in mind?

https://stackoverflow.com/a/52121118

need to write python function which prints the contents of a stan file.

**Comment by thomasjpfan** [comment]
Hmm maybe a `model.code()` call good enough.

https://github.com/stan-dev/cmdstanpy/blob/5537b0422340c82c2b58469935aa156b5c24e264/cmdstanpy/model.py#L76-L77

**Comment by maedoc** [comment]
In a Jupyter notebook, you can just use the `%%file` magic to write the cell content to a file.
