### ISSUE TITLE
update getting started guide

### ISSUE THREAD

**Issue by annapaux** [stan-dev/cmdstanpy#105]
#### Summary:
Update the getting started guide that is displayed on readthedocs
https://github.com/stan-dev/cmdstanpy/blob/master/docs/getting_started.rst

#### Description:
Changes to be made: 
add comma after stan_file and rename stan_exe --> exe_file

bernoulli_model = Model(
    stan_file = os.path.join(cmdstan_path(), 'examples', 'bernoulli', 'bernoulli.stan')
    stan_exe = os.path.join(cmdstan_path(), 'examples', 'bernoulli', 'bernoulli')
    )

**Comment by annapaux** [comment]
Came back to this after the pyladies meetup and tried to fix the issues, but can't make a pull request due to access rights. (neither HTTPS nor SSH worked) What would be the best way to contribute? @mitzimorris

**Comment by ahartikainen** [comment]
Fork repo -> clone forked repo -> create branch -> do pull request

I can try find some instructions (yes, we should have some instructions)

**Comment by annapaux** [comment]
amazing. it worked now, thanks!

**Comment by annapaux** [comment]
#106
