### ISSUE TITLE
Use black to format code

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#11]
#### Summary:

Formatting code with black makes it more clean.

https://github.com/ambv/black

#### Description:

Black automatic formatting reduces developer hours and keeps codebase clean.

#### Additional Information:

Developer environment needs to be Python 3.6, but the formatted code is still supported by 2.7

**Comment by maedoc** [comment]
Travis runs flake8 before pytest, which is good enough in my experience, to get in the ballpark of "clean readable code", but maybe I'm manually following some of the conventions Black implements.

This would be a precommit hook though, not something to run on CI build.

**Comment by seantalts** [comment]
On Stan we have both - a lot of our developers dislike installing additional tools, so we have a Jenkins stage that will autoformat their code and commit it back to the branch. It's not pretty: https://github.com/stan-dev/math/blob/develop/Jenkinsfile#L64

**Comment by infrahumano** [comment]
I was suggesting in #21 adding at least a few flake8 plugins to improve readability and uniformize divergent practices (for instence with the use of quotations). That could be also resolved with `black`, if I'm not mistaken. 

Another style piece that `black` would not resolve is the use of docstrings. In the new branch I noticed a practice exemplified by [this line](https://github.com/stan-dev/cmdstanpy/blob/refactor/api-per-func-spec/cmdstanpy/lib.py#L24). I would suggest collecting all those parameter descriptions in a proper docstring perhaps following [the Google docstring style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html). I haven't googled it up, but I am sure there are plugins for flake8 that check this as well.

**Comment by ahartikainen** [comment]
Black can do that. (increases readability).

I like the numpydoc style, because it is quite clear.

**Comment by mitzimorris** [comment]
just found this comparison - https://medium.com/3yourmind/auto-formatters-for-python-8925065f9505
will check out black.

**Comment by mitzimorris** [comment]
diagnostic messages use emojis?  :yuck:

**Comment by ahartikainen** [comment]
This works now 

From cmdstanpy root folder 

    black cmdstanpy

**Comment by mitzimorris** [comment]
many thanks!
