### ISSUE TITLE
Refactor - create classes appropriate to `optimize`, `vb` methods (not `StanFit`)

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#112]
#### Summary:
The `StanFit` class has too many method-specific properties.  Create method-appropriate classes for `optimize`method and `vb` (advi) methods.

#### Description:
All calls to CmdStan require specifying the method to be called on the model executable.   Make this explicit via an enum class which reflects the method, and add method-specific classes returned by `optimize` and `vb` methods.

Class names - `StanMLE` ? (penalized maximum likelihood estimate of the posterior density)
this class should allow user to get the Hessian (see RStan fuctionality).

**Comment by mitzimorris** [comment]
@wsuchy - how would this affect Prophet?

**Comment by wsuchy** [comment]
@mitzimorris The code for fbprophet support can be found here: https://github.com/facebook/prophet/pull/1083/files#diff-e256418eb945d8db7bf766e1126c42a5R67
In short, we use only `model.optimize` and `model.sample` so any related changes will have to be reflected in the PR but you can keep the changes in separate release version.

**Comment by mitzimorris** [comment]
great - this PR shouldn't affect current fbprophet code because the names ot the object methods haven't changed - the objects returned by `model.optimize` and `model.sample` will support the appropriate methods.

**Comment by mitzimorris** [comment]
done - https://github.com/stan-dev/cmdstanpy/pull/117
