### ISSUE TITLE
Change class `StanFit` name to `StanMCMC`

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#125]
#### Summary:
Make names precise -  'StanFit' is an RStan, PyStan legacy, but 'StanMCMC' is more descriptive.

#### Description:
Investigate consequences for arviz.

**Comment by ahartikainen** [comment]
We can change it for ArviZ, because this is still beta.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/130
