### ISSUE TITLE
add `__repr__` functions to classes `StanFit`, et. al.

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#126]
#### Summary:
add `__repr__` functions to classes StanFit/StanMCMC, StanMLE, StanQuantities, StanVariational - expose RunSet, CmdStanArgs info

#### Description:
allow users to see what the command that was run was, where the output files are.

**Comment by ahartikainen** [comment]
What information do we want to show?

**Comment by mitzimorris** [comment]
specified method, arguments, locations of csv and console files.
i.e., information present at initialization.
there are property methods which expose method results.
does this make sense?

**Comment by mitzimorris** [comment]
this would allow users to run sanity checks.  it would be useful to me right now as I try to write docs and example notebooks.

**Comment by ahartikainen** [comment]
Makes sense.

Basically what I usually do sometimes is to edit `__str__` and then just call it from `__repr__`.

In jupyter notebook --> __repr__
with print(fit) --> __str__

Maybe we should start with the wanted output and then incrementally add the information to string

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/130
