### ISSUE TITLE
progress bar issues

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#127]
#### Summary:
Simplify progress bar display:

+ single progress bar for warmup/sampling
+ bar should track progress - no longer doing so
+ most relevant timing information is estimate of remaining time; rest of information provided by % completed.

#### Description:

The progress bar display in the jupyter notebook is somewhat difficult to interpret -
the width of the bars doesn't update; there's too much information on the right-hand side which is redundant.  attaching 3 screenshots - during warmup/sampling I expected the progress bar itself to grow/change color according to % completed.

#### Additional Information:

Need to test this on a model that takes a minute or two to run.  Also test behavoir where specified number of chains is greater than specified number of cores.  Capture screenshots and add to docs.
<img width="864" alt="progress_bar_3" src="https://user-images.githubusercontent.com/5466612/66254750-d0e76d00-e748-11e9-8ef8-498d541fe745.png">
<img width="994" alt="progress_bar_2" src="https://user-images.githubusercontent.com/5466612/66254751-d0e76d00-e748-11e9-9e79-9544d9597e3e.png">
<img width="1008" alt="progress_bar" src="https://user-images.githubusercontent.com/5466612/66254752-d0e76d00-e748-11e9-94c6-0d7bdb3f0e83.png">

**Comment by mitzimorris** [comment]
At this time I'm commenting out the section in the 'getting started' docs - apologies - I think this feature is nice already, but could and should be made better.

**Comment by mitzimorris** [comment]
to clarify:

I  find the current behavoir confusing.  it's different than what I remembered when it got merged in August - I will dig into the code more to see what's changed.

**Comment by ahartikainen** [comment]
Not sure, but I think something in Jupyter Notebook / Lab  has changed which has caused me some JS issues. This might be related to it.

Does it work as expected with terminal (ipython/python)

**Comment by ahartikainen** [comment]
Also we can specify what we want to be shown. Currently we use defaults.

https://github.com/tqdm/tqdm/blob/master/README.rst#examples-and-advanced-usage

**Comment by mitzimorris** [comment]
terminal window behavoir is not good - here's a screenshot - test is running 4 chains using 2 cores - red circle is python cursor - tqdm writes ahead of cursor and then backs up - if you hit refresh while a long sample is running, it starts a new progress bar.
<img width="793" alt="progress_bar_term" src="https://user-images.githubusercontent.com/5466612/66256877-b5885c00-e760-11e9-8cf3-0b605c40dac6.png">

**Comment by ahartikainen** [comment]
Interesting. I think we can fix this.

**Comment by mitzimorris** [comment]
terminal test script:

```
import os

from cmdstanpy import Model
from cmdstanpy import __version__
print(__version__)

logistic_path = os.path.join('test', 'data')
logistic_stan = os.path.join(logistic_path,'logistic.stan')
logistic_model = Model(stan_file=logistic_stan)
logistic_model.compile()

logistic_data = os.path.join(logistic_path,'logistic.data.R')
fit = logistic_model.sample(data=logistic_data, chains=4, cores=2, show_progress=True)
```

**Comment by mitzimorris** [comment]
I played with the logic for the refresh as part of the PR for `algorithm=fixed_params` but that shouldn't affect the behavoir of tqdm.

here's Bob's suggestion for the output he'd like to see:

per chain:

 + single progress bar,  proportional between warmup and sampling iters
 + to the left of the progress bar, label chain number,
 + to the right of the progress bar, display estimated time remaining.

can this be done?  the progress bar would need to change color as it goes from warmup to sampling - in progress warmup red, completed warmup blue, in progress sampling red, completed sampling green??   or something like that...

**Comment by mitzimorris** [comment]
> I played with the logic for the refresh as part of the PR for `algorithm=fixed_params` but that shouldn't affect the behavoir of tqdm.

a single progress bar would clean up the problem with the logic which is that the number of updates determined by the refresh rate would be 100 total - should simplify the code.

**Comment by mitzimorris** [comment]
fixed by https://github.com/stan-dev/cmdstanpy/pull/196 -
massive thanks to @evgenyneu
