### ISSUE TITLE
improve argument name `csv_basename`

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#133]
#### Summary:
`csv_basename` is the path prefix used for CmdStan's output.csv files and the console messages written to stdout and stderr by CmdStan.  e.g., `csv_basename='./foo'` when running 3 chains results in the following set of files:

```
 csv_files:
	./foo-1.csv
	./foo-2.csv
	./foo-3.csv
 console_files
	./foo-1.txt
	./foo-2.txt
	./foo-3.txt
```

#### Description:

this name is slightly misleading, because
-  it's not just used for the csv files, but also for console msgs files
-  it must be a valid path
- it's only a prefix, and the chain id plus possible temporary file gunk is added into the name

possible names:

- `output` takes tuple (dir, prefix) - short and easy to grok

- `output_file`
- `output_path`
- `output_prefix`

????

#### Update

the use case for this feature would be production runs.

#### Additional Information:
Provide any additional information here.

**Comment by ahartikainen** [comment]
Btw, this currently fail on Windows, if local folder is not written explicitly

    'output' # fail
    './output' # works

**Comment by mitzimorris** [comment]
fails on Mac as well.
noticing this as I write better docs - any thoughts on good names?

**Comment by ahartikainen** [comment]
I like `output_path`

**Comment by mitzimorris** [comment]
right, but what about the prefix?  optional?  use the model name as the prefix?

**Comment by ahartikainen** [comment]
I think it could be optional.

Each sample run should have some random identifier (uuid4) so multiple calls don't overwrite previous draws.

**Comment by mitzimorris** [comment]
yes, by default model_name.   the point of specifying the output path is to get simple names in a place where the user can see them - adding random junk defeats the simple part and can lead to extreme clutter - maybe a timestamp?

**Comment by ahartikainen** [comment]
timestamp works

**Comment by mitzimorris** [comment]
@jgabry - comments?  what is CmdStanR doing?
is it OK to clobber existing files when using a non-tmpfile directory?
this would be problematic only if downstream processing does something with .csv files such that they would try to combine files outside of the session in which they are created.

**Comment by jgabry** [comment]
I’m clobbering them at the moment you in cmdstanr but was planning on changing that. Using a time stamp works for me.

**Comment by jgabry** [comment]
I added a timestamp in cmdstanr. I’m currently using this convention:

```
basename-id_date-time
bernoulli-1_20191012-1945.csv
```

The underscore separates the name from the time stamp and I don’t include seconds in the time (seems like overkill, right?). 

I’m happy to change this if you prefer something else, but this is what I’m doing at least temporarily.

**Comment by mitzimorris** [comment]
futher discussion with Jonah:
arg is `output_path` which is a directory name
timestamp is created on `RunSet` -
output file names add the timestamp

**Comment by mitzimorris** [comment]
change "csv_basename" to "output_dir" - document accordingly
name format:  model-id_date-time
basename is model name, "output_dir" is a path.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/187
