### ISSUE TITLE
add property 'csv_files' to `StanMCMC` et al 

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#135]
#### Summary:
the coupling between methods `sample` and `run_generated_quantities` requires a list of csv files as input;  the StanMCMC method should provide this via property `csv_files`.

#### Description:
Convenience method on classes that wrap result of CmdStan run.

#### Additional Information:
Provide any additional information here.

**Comment by mitzimorris** [comment]
currently CmdStanMCMC et al objects report locations of console and csv output files via `__repr__` function.  expose via properties as well?

**Comment by ahartikainen** [comment]
methods with some convenience functionality?

Like extract all `error` lines or get last n lines etc?

**Comment by mitzimorris** [comment]
csv_files - rename to "output_files"
console_files
diagnostice_file  (this is also a csv file)

**Comment by mitzimorris** [comment]
we now have both csv_files and diagnostic_files
