### ISSUE TITLE
standardize class and method names - align with CmdStanR

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#137]
#### Summary:

The `Model` class methods which invoke cmdstan and the corresponding returned object classname should align across CmdStanXXX interfaces.

- method `sample` - change `StanMCMC` to `CmdStanMCMC`
- method `optimize` - change `StanMLE` to `CmdStanMLE`
- method `run_generated_quantities` rename as `generate_quantities` and change `StanQuantities` to `CmdStanGQ`
- method `variational` - change `StanVariational` to `CmdStanVB`

#### Description:
see stan-dev/cmdstanr#24

#### Additional Information:
Provide any additional information here.

**Comment by mitzimorris** [comment]
@jgabry - did we discuss name of class `Model`?

change to `CmdStanModel`?

**Comment by jgabry** [comment]
Yeah if that's ok!

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/143
