### ISSUE TITLE
allow user to save data files as well as output files

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#138]
#### Summary:

Add method to RunSet which checks CmdStan args for name of data file, and if data file exists either:
- return object as `Dict`
- return location of data file

Co-ordinate with CmdStanR?

~~CmdStanPy provides utilities ``jsondump`` and ``rdump``.  
expose these via __init__.py and document them.~~

**Comment by mitzimorris** [comment]
@jgabry and @rok-cesnovar  - what does CmdStanR do here?
@ahartikainen - what does Arviz need in order to save this as an inference data obj?

**Comment by ahartikainen** [comment]
ArviZ needs a way to transfer collected data to a dictionary. So either a dictionary / class attributes are enough.

Here are examples 
- CmdStan https://github.com/arviz-devs/arviz/blob/master/arviz/data/io_cmdstan.py#L556
- PyStan https://github.com/arviz-devs/arviz/blob/master/arviz/data/io_pystan.py#L657
- PyStan3 https://github.com/arviz-devs/arviz/blob/master/arviz/data/io_pystan.py#L783

Currently the metadata collected is library specific, so it can use the names from the parent library.

**Comment by jgabry** [comment]
We have `fit$save_data_file()`, which moves the temporary data file to a specified permanent location.

**Comment by mitzimorris** [comment]
if the data is a in-memory object, either dict, dataframe, or xarray object, utility function `write_stan_json` can be used to save data to specified location.
https://github.com/stan-dev/cmdstanpy/pull/418
