### ISSUE TITLE
Handle TBB lib on Windows

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanpy#146]
#### Summary:
Cmdstan 2.21 now includes the Intel TBB library. This changes nothing for non-Windows users in terms of how they build models.

Windows users of cmdstan have the option of adding the path to the build library (`<cmdstan-path>/stan/lib/stan_math/lib/tbb`) to their user of system PATH variable. If they dont do that, the tbb.dll is copied to the executable folder for each model. 

So techincally they also dont have to do anything, but to avoid copying of dlls or requiring the users to set the path variable cmdstanpy and cmdstanr could provide convenience features that Windows users dont have to add that. 

The easiest solution would be to add the above path to the PATH variable for the session or simply for every run.

#### Additional Information:
/

**Comment by ahartikainen** [comment]
Is it always `/stan/lib/stan_math/lib/tbb` or do we accept if users set some ENV var?

**Comment by rok-cesnovar** [comment]
Cmdstan will always look there, if a user wants to use system installed TBB, they can set it in the system PATH and it will then take that one automatically. I think that is ok. 

I am open to any suggestions. I will implement the cmdstanr support so lets coordinate.

**Comment by ahartikainen** [comment]
If we define 

    $PATH += `/stan/lib/stan_math/lib/tbb'

Then any tbb lib on path should have preference. Which could be bad, if there is some version by accident

    $PATH = '/stan/lib/stan_math/lib/tbb' + $PATH

This would always use our tbb.

Is it possible to use `-I` / `-L` as a command line argument?

**Comment by rok-cesnovar** [comment]
> $PATH = '/stan/lib/stan_math/lib/tbb' + $PATH

Yeah this is definitely the way to go. Agree. That is how we modify the path if the user call make install-tbb on Windows.

> Is it possible to use `-I` / `-L` as a command line argument?

You mean as in statically link? No, we need dynamic linking which is why we need all this for Windows.

**Comment by rok-cesnovar** [comment]
Also, I now saw that my original post was not formatted correctly. The path is: `<cmdstan-path>/stan/lib/stan_math/lib/tbb`

**Comment by ahartikainen** [comment]
I added this to Model init. Do we have more suitable env name than `STAN_TBB`, which user can use to overwrite the default library folder.

```
        if platform.system() == "Windows":
            # Add tbb to the $PATH on Windows
            libtbb = os.getenv("STAN_TBB")
            if libtbb is None:
                libtbb = os.path.join(
                    cmdstan_path(), "stan", "lib", "stan_math", "lib", "tbb"
                )
            os.environ["PATH"] = "{};{}".format(libtbb, os.getenv("PATH"))
```

And all the `Popen` calls now use `env=os.environ` which means that the changes in `os.environ` are propagated to cmd.

**Comment by rok-cesnovar** [comment]
> Do we have more suitable env name than `STAN_TBB`

I think its an ok name. Will use the same one for cmdstanr. Thanks @ahartikainen !

**Comment by mitzimorris** [comment]
fixed by https://github.com/stan-dev/cmdstanpy/pull/148
