### ISSUE TITLE
Use linting to check code

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#165]
#### Summary:

We should check our PR with linting (e.g. pylint) so invalid code does not get into codebase.

#### Description:

There was `os.path.exist` vs `os.path.exists` issue (typo I accidentally created). I though we had some linting checks, but apparently we don't have.

#### Additional Information:

I usually use `pylint`.

#### Current Version:

master

**Comment by mitzimorris** [comment]
yes!!!

**Comment by mitzimorris** [comment]
@ahartikainen what config do you use?
looking at this blog post - opinions?  https://pythonspeed.com/articles/pylint/

**Comment by ahartikainen** [comment]
I usually copy this from arviz https://github.com/arviz-devs/arviz/blob/master/.pylintrc and then edit it a bit if there are things I want to include / exclude. For example I might have special names I want to use .

And then there are false-positives that I exclude by special tag

    my_code() #  pylint: disable=error-code-name,second-error-code

**Comment by wesbarnett** [comment]
cf. #184

**Comment by wesbarnett** [comment]
I have started using the following git hook to check for linting errors with flake8 and pylint. This goes in `.git/hooks/pre-commit`, which must be executable. This would be something an individual user would control on their local machine, since it is not in the git tree. We could document this so that contributors could use it (if pre-commit is too often, then pre-push, etc. could be used).
```
#!/bin/bash
command -v flake8 >/dev/null 2>&1 || { echo >&2 "flake8 needs to be installed for pre-commit hook. Aborting."; exit 1; }
command -v pylint >/dev/null 2>&1 || { echo >&2 "pylint needs to be installed for pre-commit hook. Aborting."; exit 1; }
for f in $(git diff --cached --name-only); do 
    if [ ${f: -3} == ".py" ] && [ -f $f ]; then 
        flake8 --extend-ignore=E127,E201,E202,E203,E231,E252,E266,E402,E999,F841,W503,W605 --max-line-length=80 $f
        pylint -v --rcfile=$(git rev-parse --show-toplevel)/.pylintrc $f
    fi
done


```

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/184
