### ISSUE TITLE
investigate save/pickle for CmdStanMCMC, et al, assemble sample before saving

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#171]
#### Summary:
The sample will be lost at the end of the session because the csv output files are written to tmpFiles by default.

#### Description:
The csv output files are written to tmpFiles by default, and not read into memory until one of the methods or properties on the CmdStanXXX object are called.  If a user wants to fit a model and save the output, it's necessary to either assemble the sample in memory or make sure that the csv files are moved to a permament location.

#### Additional Information:
Provide any additional information here.

**Comment by ahartikainen** [comment]
If we read csv in bytes and gzip them, then pickle the object and when unpickle just put them to on disk again?

Or just read data in and pickle that.

**Comment by mitzimorris** [comment]
I was thinking of the latter (read in data, pickle that), both ways you have to read in the data.  although reading and gzipping should be faster than assembling, no?

**Comment by mitzimorris** [comment]
closed by accident, reopening.

**Comment by ahartikainen** [comment]
Yeah, it probably is faster, but I don't know how much faster.

**Comment by mitzimorris** [comment]
add a control argument - save files vs. save sample?

**Comment by ahartikainen** [comment]
Maybe we should list what we should save when saving Fit, Model etc?

And when we save something, it is usually to be either reproducable or continue working later.

**Comment by WardBrian** [comment]
Effectively resolved by #402
