### ISSUE TITLE
Windows 10 cannot import cmdstanpy after installation

### ISSUE THREAD

**Issue by footballdaniel** [stan-dev/cmdstanpy#173]
#### Summary:
After successful cmdstan installation trough the python console, running the bernoulli-example in a virtual conda environment doesn't work.

#### Description:
I tried using cmdstanpy two different ways
- Installing `pip install cmdstanpy` works, but the import of the package in the bernoulli script fails: `ImportError: cannot import name 'Model' from 'cmdstanpy`
- Installing `pip install -e git+https://github.com/stan-dev/cmdstanpy#egg=cmdstanpy` yields the same error

#### Additional Information:
To build cmdstan (trough `import cmdstanpy
cmdstanpy.install_cmdstan()`), I had to:
`SET PATH=C:\Rtools\bin;C:\Rtools\mingw_64\bin;%PATH%`
`SET MAKE=mingw32-make.exe`

#### Current Version:
Windows 10
Rtools 3.4
Python 3.74
conda 4.7.12
gcc 4.9.3
Mingw64

**Comment by ahartikainen** [comment]
I think we need to update the instructions.

Also for windows installation.

**Comment by ahartikainen** [comment]
This is the example from the current readme:

```
import os
from cmdstanpy import CmdStanModel, cmdstan_path

# specify Stan file, create, compile CmdStanModel object
bernoulli_path = os.path.join(cmdstan_path(), 'examples', 'bernoulli', 'bernoulli.stan')
bernoulli_model = CmdStanModel(stan_file=bernoulli_path)


# specify data, fit the model
bernoulli_data = { "N" : 10, "y" : [0,1,0,0,0,0,0,0,0,1] }
bernoulli_fit = bernoulli_model.sample(chains=5, cores=3, data=bernoulli_data)

# summarize the results (wraps CmdStan `bin/stansummary`):
bernoulli_fit.summary()
```

**Comment by mitzimorris** [comment]
is this still causing problems?
are the current installation instructions good enough?

**Comment by footballdaniel** [comment]
Much better, this can be closed! 
I installed cmdstanpy on another windows 10 x64 machine. The only part where the instructions are unsatisfying (for a naive user like me) is
`Prerequisites \n CmdStanPy requires an installed C++ toolchain.`

I figured the way to use the `cmdstanpy.install_cxx_toolchain`, but had to restart / set the path variable for the make file in order to get it running. If you could document how to do this, this would be amazingly helpful.
Love cmdstanpy, thank you!

**Comment by mitzimorris** [comment]
closing this issue, added doc suggestion to issue #225
