### ISSUE TITLE
Cleanup compiled files after tests

### ISSUE THREAD

**Issue by wesbarnett** [stan-dev/cmdstanpy#174]
#### Summary:

I would like to implement a way to cleanup the executable files, object files, and header files generated from running `pytest`.

#### Description:

Several files are generated after tests are run. These can be automatically removed as part of the tests by using a pytest fixture for each class.

**Comment by ahartikainen** [comment]
I think test files and data should go to `tempfolder`

**Comment by mitzimorris** [comment]
do pytest fixtures play nicely with running tests via the unittest module as well?

**Comment by ahartikainen** [comment]
I don't know, but if I would guess: no.

**Comment by wesbarnett** [comment]
pytest fixtures do work with unittest.

**Comment by wesbarnett** [comment]
the alternative of creating a tmpdir might be simpler though

**Comment by wesbarnett** [comment]
I opened a PR of how pytest fixtures could work, but feel free to close if you would like to go the tmpdir route.
