### ISSUE TITLE
Random number generator not configured by seed

### ISSUE THREAD

**Issue by rndpolytope** [stan-dev/cmdstanpy#18]
#### Summary:
Seed not passed to random number generator. Inconsistent results were generated when running the code multiple times.

#### Description:
As in gist file https://gist.github.com/rndpolytope/704fbad70a379e4143d62dcc6b68d592

#### Current Version:
cmdstan 2.18.1, cmdstanpy 0.9.0

**Comment by maedoc** [comment]
Can you update your notebook (I don't have a dev env with cmdstanpy setup at the moment) with
```python
print(fit_1.cmd)
print(fit_2.cmd)
```
which should print the exact commands used to invoke the CmdStan executable?

**Comment by rndpolytope** [comment]
Gist updated.

```text
['/Users/rndpolytope/.cache/cmdstanpy/model-e4c22992', 'id=98540', 'sample', 'algorithm=fixed_param', 'num_warmup=0', 'num_samples=1', 'output', 'file=/var/folders/ly/_ltwkx7n73q9s1xfz8720mvc0000gn/T/tmpycedgg_4/output.csv', 'refresh=1']

['/Users/rndpolytope/.cache/cmdstanpy/model-e4c22992', 'id=98540', 'sample', 'algorithm=fixed_param', 'num_warmup=0', 'num_samples=1', 'output', 'file=/var/folders/ly/_ltwkx7n73q9s1xfz8720mvc0000gn/T/tmp6gzzt466/output.csv', 'refresh=1']
```

**Comment by maedoc** [comment]
Thanks.  It shows the CmdStan executable is getting the same value of `id` parameter.  I assumed this was sufficient to set the Stan RNG, but apparently that's not the case.  If you or another Stan dev knows what parameter to set, this can be fixed [here, where we generate the command](https://github.com/stan-dev/cmdstanpy/blob/master/cmdstanpy/model.py#L235).

**Comment by bob-carpenter** [comment]
There is a seed and an id.  The seed controls the random number generator seed that's used.  The id controls how far to advance that random number generator.  For multiple chains, they can each use the same seed with different ids.

**Comment by maedoc** [comment]
> There is a seed and an id

thanks fro the clarification; in #19 the user's seed is passed along to CmdStan along with the id (as before), which should address this issue.

**Comment by mitzimorris** [comment]
addressed by https://github.com/stan-dev/cmdstanpy/pull/21 - all chains have same seed which is either specified by user or random, chain ids managed by `sample` function.
