### ISSUE TITLE
allow all stanc and stanc3 compiler flags

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#186]
#### Summary:
see discussion and solution for CmdStanR:
https://github.com/stan-dev/cmdstanr/issues/71

#### Description:
Describe the issue as clearly as possible.

#### Additional Information:
Provide any additional information here.

**Comment by mitzimorris** [comment]
address issue #202 as well.

**Comment by ahartikainen** [comment]
Do they already have a solution?

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/219

only allow those compiler flags which are relevant for the CmdStanPy workflow.
ignore compiler flags which don't produce .hpp files or are used to debug the stanc3 compiler.
also ignore flags to pretty print program or cpp code, because this is not really part of the workflow.
