### ISSUE TITLE
How to specify a directory for compiled model?

### ISSUE THREAD

**Issue by evgenyneu** [stan-dev/cmdstanpy#192]
When I call `CmdStanModel(stan_file="my_model.stan")` it creates .hpp, .o and the binary file in the directory where `my_model.stan` is located. This is a bit inconvenient because I don't want to commit those files (.hpp, .o and binary) into git (I only need to commit the *.stan files). Is there a way to specify a different directory for those three files instead? This way, I can call this directory `stan_compile`, for example, and put it into .gitignore. Or maybe you can suggest a different way of achieving what I want?

Right now, I use a hacky way of ignoring the compiled files, by putting the `my_model.stan` into `stan_compile` directory and adding this to .gitignore

```
**/stan_compile/*
!**/stan_compile/*.stan
```

This way I tell Git to ignore everything in `stan_compile` directory except files with .stan extension. I don't like this trick very much though, because it is a bit complicated and requires keeping the *.stan files in subdirectories.

#### Current Version:

0.8.0

Thanks :)

**Comment by ahartikainen** [comment]
Currently we just call CmdStan. Is there a way to define separate folder?

We could implement this by copying `.stan` file, but might get hard if user uses `#include` statements and/or external C++ files.

**Comment by evgenyneu** [comment]
> Currently we just call CmdStan. Is there a way to define separate folder?

I don't know, I have not used cmdstan directly, and I have not found such an option in [cmdstan documentation](https://github.com/stan-dev/cmdstan/releases/download/v2.21.0/cmdstan-guide-2.21.0.pdf).

> We could implement this by copying .stan file, but might get hard if user uses #include statements and/or external C++ files.

Yes, this could create more problems than it solves :). 

I cal solve this easily in my code (by copying compiled files after `CmdStanModel()`), but I just asked here in case this has already been implemented.

**Comment by mitzimorris** [comment]
> Yes, this could create more problems than it solves :).
agreed.

compilation in CmdStan is a direct call to `make` and the makefile rules create the exe file in the same dir as the src file;  the user can then move of copy the exe file as needed.

inasmuch as editing the `.gitignore` file is required for your repo, I suggest putting all models in some designated directory, and making ignore rules accordingly, e.g.:

<path-to-my-models>/*
!<path-to-my-models>/*.stan

closing this issue.
