### ISSUE TITLE
Need some way to display sampling error messages

### ISSUE THREAD

**Issue by seantalts** [stan-dev/cmdstanpy#199]
#### Summary:
I took a quick look and didn't see anything related to this - I can't figure out how to see error messages from CmdStanPy that are encountered during sampling (and ones encountered during compilation are not printed in a pretty way). Here is what error messages during sampling look like in colab:

```
/usr/local/lib/python3.6/dist-packages/cmdstanpy/model.py in sample(self, data, chains, cores, seed, chain_ids, inits, warmup_iters, sampling_iters, save_warmup, thin, max_treedepth, metric, step_size, adapt_engaged, adapt_delta, fixed_param, output_dir, save_diagnostics, show_progress)
    726                             msg, i, runset._retcode(i)
    727                         )
--> 728                 raise RuntimeError(msg)
    729             mcmc = CmdStanMCMC(runset, fixed_param)
    730             mcmc._validate_csv_files()

RuntimeError: Error during sampling, chain 0 returned error code 70, chain 1 returned error code 70, chain 2 returned error code 70, chain 3 returned error code 70
```

**Comment by ahartikainen** [comment]
Probably related to this

https://github.com/stan-dev/cmdstanpy/pull/194

**Comment by seantalts** [comment]
I don't think code from #194 is released yet, right? So it looks like maybe that will fix the compiler error message output, but there's still no Stan program output for errors that occur during sampling.

**Comment by bob-carpenter** [comment]
Stan can print(), reject(), or the math library functions or algorithms can raise exceptions.  All of these need to get printed.  Does the fix need to go in stanc3 or in cmdstanpy or somewhere else?

**Comment by seantalts** [comment]
Cmdstanpy - error messages show up in cmdstan.

**Comment by ahartikainen** [comment]
CmdStanPy gathers that output and we need to fix so we can show it in case of failure.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/220
