### ISSUE TITLE
Setup CI/CD

### ISSUE THREAD

**Issue by maedoc** [stan-dev/cmdstanpy#2]
#### Summary:
How to do CI for cmdstanpy

#### Description:
Previous development used a Docker build to run tests & push tags as packages to PyPI, the question here is if that is to be retained and how (build on Travis, etc).

#### Additional Information:
In repo, cf `Dockerfile` & `.gitlab-ci.yml`

#### Current Version:
N/A

**Comment by seantalts** [comment]
I think Travis is fine!

**Comment by ahartikainen** [comment]
Setting up Docker is more robust.

I think we could follow similar implementation as https://github.com/arviz-devs/arviz

**Comment by ahartikainen** [comment]
But, I think we can start with Travis and then if there are some Travis specific failures we can move to Docker.

**Comment by maedoc** [comment]
closed by #12
