### ISSUE TITLE
Install RTools for mac

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#201]
#### Summary:
Please provide a short couple sentence summary.

Enable RTools for macOS.

#### Description:
Describe the issue as clearly as possible.

RTools currently works only for Windows. I think we should also enable installation for macOS too.

#### Additional Information:
Provide any additional information here.

https://github.com/rmacoslib/r-macos-rtools

#### Current Version:

master

**Comment by mitzimorris** [comment]
why do we want this? in order to get C++ toolchain?
are there other things in rtools as well?

**Comment by ahartikainen** [comment]
yes, for C++

**Comment by mitzimorris** [comment]
agreed we need this - just not sure about using rtools vs. something else.

**Comment by ahartikainen** [comment]
Yeah, we could also implement other toolchains.

**Comment by mitzimorris** [comment]
closing this - `install_cxx_toolchain` rocks!

**Comment by mitzimorris** [comment]
this is doable - https://medium.com/@vaishalihthacker49/xcode-command-line-tools-26f95ba6fb71

keeping up with all the versions of OS X may be challenging, also the fact that Apple doesn't make this easy to find.
