### ISSUE TITLE
`CmdStanMCMC.sample` doesn't include warmup iters if `save_warmup` is `True`.

### ISSUE THREAD

**Issue by SiegeLordEx** [stan-dev/cmdstanpy#207]
#### Summary:
`CmdStanMCMC.sample` doesn't include warmup iters if `save_warmup` is True.

#### Description:
I'm interested in looking at the behavior of the sampler during the warmup stage, so I set the `save_warmup` to `True`. However, that had no effect on the output of `CmdStanMCMC.sample`. I'd have expected it to contain the warmup iterations.

Alternatively, I could live with a separate accessor for just the warmup iterations, but that'd be less convenient than just pre-pending them to samples.

For now, I'll parse the csv files myself.

#### Current Version:
0.0.8

**Comment by mitzimorris** [comment]
> Alternatively, I could live with a separate accessor for just the warmup iterations, but that'd be less convenient than just pre-pending them to samples.

I think a separate accessor for the warmup iterations makes more sense.  warmup draws and post-warmup draws are used for different things:

- the sample lets you make inferences about your model and data,
- the warmup draws  give you information about the sampler

similarly, I would store these underlyingly in different ndarrays.

agreed we should have this feature.

**Comment by mitzimorris** [comment]
> Alternatively, I could live with a separate accessor for just the warmup iterations, but that'd be less convenient than just pre-pending them to samples.

a separate accessor - how about `draws_warmup`  ?

**Comment by mitzimorris** [comment]
accessor `drawset` should be renamed `draws` to match CmdStanR - cf. https://github.com/stan-dev/cmdstanpy/issues/221

**Comment by ahartikainen** [comment]
ArviZ (current master) implements this (for pystan) with a group that is similar to posterior group. So the access procedure is similar.

Maybe we could have something similar with CmdStanPy?

**Comment by mitzimorris** [comment]
@ahartikainen - sounds good.  this is implemented on https://github.com/stan-dev/cmdstanpy/tree/feature/207-save-warmup

I think it's ready for code review - working on the PR writeup since this required some refactoring and touched a lot of files.

**Comment by mitzimorris** [comment]
@ahartikainen - requested your review - happy to change accessor name/config for arviz

**Comment by mitzimorris** [comment]
> I'm interested in looking at the behavior of the sampler during the warmup stage, so I set the save_warmup to True. However, that had no effect on the output of CmdStanMCMC.sample. I'd have expected it to contain the warmup iterations.

reconsidering implementation - will follow CmdStanR in the warmup iterations will be part of returned sample.

**Comment by ahartikainen** [comment]
How are warmup accessed in CmdStanR?

**Comment by mitzimorris** [comment]
CmdStanR uses `draws` instead of `sample` as name of method to get draws X chain X column.
has an option "include_warmup" - false by default.
we should do the same

**Comment by ahartikainen** [comment]
Sounds good.

**Comment by mitzimorris** [comment]
this was addressed by https://github.com/stan-dev/cmdstanpy/pull/277 -
`sample` was renamed `draws` to match CmdStanR.

note issue https://github.com/stan-dev/cmdstanpy/issues/290 - function `draws_as_dataframe` will be renamed `draws_pd`, per discussion on that issue.
