### ISSUE TITLE
after running sampler, remind users to run `diagnose`

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#208]
#### Summary:
see https://github.com/stan-dev/cmdstanr/issues/118

#### Description:
Describe the issue as clearly as possible.

#### Additional Information:
Provide any additional information here.

**Comment by bob-carpenter** [comment]
Would it make sense to run diagnose by default?  Or will it be too slow or verbose?

**Comment by ahartikainen** [comment]
For huge models it might not be a good idea. We had the same problem for PyStan, where we compromised running full diagnosis only for models with less than 1000 parameters and for larger models we just check divergences etc (skipping rhat + ess).

**Comment by mitzimorris** [comment]
> Would it make sense to run diagnose by default? Or will it be too slow or verbose?

the CmdStan diagnose utility takes the sample csv files and reads them all in - in order to go with a lightweight wrapper around this utility, you need to wait for the sampler to finish and then read the csv files back in.  so too slow.

**Comment by mitzimorris** [comment]
use of `diagnose` is part of example notebooks.
