### ISSUE TITLE
Method CmdStanMLE:optimized_params_np is lying about its return type

### ISSUE THREAD

**Issue by wsuchy** [stan-dev/cmdstanpy#213]
#### Summary:
The method `optimized_params_np(self) -> np.array`
defined here: https://github.com/stan-dev/cmdstanpy/blob/master/cmdstanpy/stanfit.py#L547
is lying about its return type because the function `def scan_optimize_csv(path: str)`
doesn't produce numpy object, but a list.

@mitzimorris I am creating this issue because we've finally merged https://github.com/facebook/prophet/pull/1083 and I thought it would be nice to use most recent version of this library in prophet. Unfortunately this is one of the reasons why fbprophet doesn't work with cmdstanpy in version 0.8 out of the box.

**Comment by mitzimorris** [comment]
adding call to `np.asarray` in the return stmt for `optimized_params_np` - https://github.com/stan-dev/cmdstanpy/tree/bugfix/213-optimized-params-asarray

> Unfortunately this is one of the reasons why fbprophet doesn't work with cmdstanpy in version 0.8 out of the box.

@wsuchy - what else is problematic?
