### ISSUE TITLE
Move CI to azure pipelines

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#215]
#### Summary:

We could really simplify our testing pipeline by moving it to azure.

Stan is (under) part of NumFocus which I think has a way to get azure accounts.

#### Description:

I think we could really use similar tests for Linux, macOS and Windows.

#### Additional Information:

ArviZ uses azure pipelines and they are great.

#### Current Version:

master

**Comment by mitzimorris** [comment]
@ahartikainen - great suggestion!
testing for all of stan-dev, or just this repo? alerting @jgabry since he's on the SGB and this is definitely something that we should do (instead of paying for AWS).

**Comment by ahartikainen** [comment]
I updated ArviZ CI to use Azure DevOps.

https://github.com/arviz-devs/arviz/tree/master/.azure-pipelines

https://dev.azure.com/ArviZ/ArviZ/_build/results?buildId=1870&view=results

For example this will create wheel-file for tag releases, builds docs conditionally (we update based on master).

cc. @riddell-stan

**Comment by mitzimorris** [comment]
talking to @jgabry - looks like we're going to get free credits for AWS - but if Azure is better and also free, that would be great.

**Comment by mitzimorris** [comment]
pinged the current SGB via discourse, closing this.
