### ISSUE TITLE
simplify/generalize model compilation options

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#217]
#### Summary:
https://github.com/stan-dev/cmdstanr/issues/121

#### Description:
CmdStanR provides flags to the CmdStanModel `compile` function for opencl and use of `DSTAN_THREADS` - add this functionality to CmdStanPy but in the most general way possible.

#### Additional Information:
related issues:

- https://github.com/stan-dev/cmdstanpy/issues/202
- https://github.com/stan-dev/cmdstanpy/issues/186

**Comment by mitzimorris** [comment]
the only exposing OPENCL and stanc3 compiler flags.
`STAN_THREADS` seems problematic.

**Comment by ahartikainen** [comment]
What keywords are they using?

OpenCL --> does this some flags for model compilation. What about sampling / runtime?
threading --> this is purely sampling / runtime things

Should we also support MPI?

**Comment by mitzimorris** [comment]
> Should we also support MPI?

yes we should - checking with @rok-cesnovar?

> OpenCL --> does this some flags for model compilation. What about sampling / runtime?

the CommandStan makefile has logic that sets stanc3 compiler flags properly is `STAN_OPENCL` is specified.

**Comment by mitzimorris** [comment]
update to previous comment - yes, we are supporting MPI.

**Comment by rok-cesnovar** [comment]
> yes we should - checking with @rok-cesnovar?

I would say yes. But I think that is a separate issue and would derail the rest of what we are trying to achieve here. MPI requires a different way of calling the model executable as well as the STAN_MPI make flag. 

But supporting that would be great. Running and using MPI is tedious and super unfriendly. Also see https://github.com/stan-dev/cmdstanr/issues/117

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/219
