### ISSUE TITLE
investigate granularity of exceptions required for subprocesses as well as CmdStan return codes - are they useful?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#22]
#### Summary:
Reviewer comments on PR https://github.com/stan-dev/cmdstanpy/pull/21 raise several good points - 

> If return codes from CmdStan are semantic (1 -> unable to initialize, 2 -> max iters w/o convergence, …), they would be best translated to specific exceptions. If they aren't, a RuntimeException would be appropriate, with a separate method for returning stderr lines. Return an error msg full of retcodes here isn't going to be particularly valuable.

and:

> It's sometimes useful to use an API specific Exception subclass to ensure you don't catch things you shouldn't be catching. Python mostly gets this right for you, e.g. you won't catch a KeyboardInterrupt, but if there are other exceptions that should bubble up to the user, it may be preferable to catch a more specific set of exceptiosn e.g. OSError, subprocess.CalledProcessError.

Breaking this out into an issue to be addressed in its own PR.

#### Additional Information:
Provide any additional information here.

**Comment by seantalts** [comment]
Hey, I'm not sure if this issue covers this, but the error messages from CmdStan are swallowed:
```
start chain 1.  
finish chain 1.  
Traceback (most recent call last):
  File "silly.py", line 34, in <module>
    chains=1)
  File "silly.py", line 10, in wrapper
    res = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cmdstanpy/cmds.py", line 165, in sample
    raise Exception(msg)
Exception: Error during sampling, chain 0 returned error code 70
```
This happens any time something goes wrong from CmdStan, in this case I just passed in data that was the wrong shape. Should I make a new issue?

**Comment by maedoc** [comment]
@seantalts this is a problem for me as well.  There doesn't seem to be a way to retrieve the `StanFit` object, where the stderr is being stored, which is a local variable in the `sample` method, when the exception is raised.  A workaround could be to catch the exception and go back a few frames to dig out the local vars, but ideally the stderr should be easy to see, especially in interactive usage.

One way to keep the API as it is, would be to avoid blocking in the `sample` method, and just return the fit object with the chains running.  When any call on the `StanFit` API requires results, block until CSV files are validated.  This would allow the user to check progress on the fit object as well.  If there are errors, the user can query the fit object for what you've called the console files to see what's up.

**Comment by seantalts** [comment]
That seems nice!

**Comment by mitzimorris** [comment]
blocking on the `sample` method isn't necessary, as invalid inputs will cause the sampler to fail quite quickly.  the problem is that the error messages to the console are lost and aren't returned as part of the exception.  @maedoc - would adding the output from stderr to the message be OK?

**Comment by maedoc** [comment]
> would adding the output from stderr to the message be OK?

This seems OK, but it could also force user to extract and parse the exception message for more complex errors. But at least it'll be accessible.

**Comment by mitzimorris** [comment]
do you have examples of the kinds of extraction/parsing that would be useful?
agreed that CmdStan error msgs could use some help.

**Comment by maedoc** [comment]
For a model with ADVI, I had enough problems with the ELBO integral not working that I implemented a restart loop which grepped for that specific error.  If I had looped on any error then I'd have an infinite loop for truly (more) problematic cases.

Another example is during initialization there are sometimes intermittent messages that should go away when sampling but could also lead to failure after 100 attempts.

This is getting a little pedantic though and I don't want to hold up the simple fix.  A compromise would be an exception subclass with the StanFit object as an attribute that the user could inspect (if they catch the exception). Wdyt ?

**Comment by mitzimorris** [comment]
> compromise would be an exception subclass with the StanFit object as an attribute that the user could inspect (if they catch the exception). Wdyt ?

excellent idea - will implement.

**Comment by mitzimorris** [comment]
returning an object, because at this point, there really isn't any object to return.  Instead, dumping the information in the Runset object and printing error messages from the output streams (stdout, stderr).

https://github.com/stan-dev/cmdstanpy/pull/280
