### ISSUE TITLE
documentation-related suggestions, corrections, comments - evergreen

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#225]
#### Summary:
Note gaps in documentation here and/or suggestions for improvements

#### Description:
Perpetually open issue

**Comment by mitzimorris** [comment]
noted here: https://github.com/stan-dev/cmdstanpy/issues/173#issuecomment-597215511

I installed cmdstanpy on another windows 10 x64 machine. The only part where the instructions are unsatisfying (for a naive user like me) is
Prerequisites \n CmdStanPy requires an installed C++ toolchain.

I figured the way to use the cmdstanpy.install_cxx_toolchain, but had to restart / set the path variable for the make file in order to get it running.

**Comment by mitzimorris** [comment]
comment brom Ben Bales on CmdStanR - same goes for CmdStanPy

https://github.com/stan-dev/cmdstanr/issues/200#issuecomment-644159362

**Comment by tomwphillips** [comment]
I wasn't sure whether to create a new issue, so thought I'd post here. I would find it useful to be able to view the online documentation for the different versions of cmdstanpy. On a few occasions I've read the latest documentation online and found methods I would like to use, but then found that they're not in the latest pypi release.

Similarly, many other Python packages use GitHub releases to tag the commit corresponding to each version, which makes it easy to browse the code for a particular version, but that workflow isn't used here.

I have experience building CI/CD pipelines in Python projects at work (using CircleCI, but they're all quite similar), so I might be able to help out with some improvements if it's wanted. 🙂

**Comment by mitzimorris** [comment]
> On a few occasions I've read the latest documentation online and found methods I would like to use, but then found that they're not in the latest pypi release.
 
not sure what you mean by latest documentation online?  my understanding is that whenever a release is uploaded to pypi, that's what readthedocs is showing?  is that not the case?

**Comment by mitzimorris** [comment]
> Similarly, many other Python packages use GitHub releases to tag the commit corresponding to each version, which makes it easy to browse the code for a particular version,

https://github.com/stan-dev/cmdstanpy/issues/122 - just following the `master` / `develop` etc, so we can tag releases.
going forward, will tag whenever a new version is uploaded to PyPi.

**Comment by tomwphillips** [comment]
> > On a few occasions I've read the latest documentation online and found methods I would like to use, but then found that they're not in the latest pypi release.

I can't for the life of me find the function I was looking at. Sorry, I should have provided more detail in the first place.

> not sure what you mean by latest documentation online? my understanding is that whenever a release is uploaded to pypi, that's what readthedocs is showing? is that not the case?

Yes, readthedocs always shows the latest version on `master`. It would be useful to be able to [read the documentation for the specific version](https://docs.readthedocs.io/en/stable/versions.html) I'm using.

**Comment by mitzimorris** [comment]
thanks alot for the link - I will get this working ASAP!

**Comment by mitzimorris** [comment]
expose helper functions API section of the docs


- set_cmdstan_path,
- cmdstan_path,
- set_make_env,
-  install_cmdstan

**Comment by mitzimorris** [comment]
host CmdStanPy docs via GitHub as well as on readthedocs website -

- should this be just the Sphinx docs or something more comprehensive?
- how can we integrate this with Stan / CmdStan release process?

@serban-nicusor-toptal  - need your help here.

also related - tried to address above comment: 
```
Yes, readthedocs always shows the latest version on master. It would be useful to be able to read the documentation for the specific version I'm using.
```

cannot get the damn thing to get latest tagged version showing up.  any thoughs?

**Comment by mitzimorris** [comment]
Document use of "--include_paths" as one of the stanc_options

**Comment by serban-nicusor-toptal** [comment]
Hey @mitzimorris 
We can have the docs be updated when we do a new release (tag) in Jenkins. Let me how we should update the docs and if there are any other requirements. 
We already have the one in github automated afaik ( [build-docs](https://jenkins.mc-stan.org/blue/organizations/jenkins/BuildDocs/detail/BuildDocs/41/pipeline/8) ) I'm a bit unsure about how to do the readthedocs one.
I will look into the versioning for readthedocs see if I can figure it out!

**Comment by serban-nicusor-toptal** [comment]
Is it possible for you to give me access to the project dashboard in ReadTheDocs @mitzimorris ?
I think we need to either modify something in the dashboard or play around with the [conf.py](https://github.com/stan-dev/cmdstanpy/blob/develop/docs/conf.py)

**Comment by mitzimorris** [comment]
just gave you access to readthedocs - also tried changing setting to `stable`, but it doesn't seem to be picking up the version tag.

**Comment by mitzimorris** [comment]
@serban-nicusor-toptal - tagging you for above message

**Comment by serban-nicusor-toptal** [comment]
I've activated the v0.9.66 version ( created a tag in github ) and ran a build, after the build it shows up in the public list [here](https://readthedocs.org/projects/cmdstanpy/). 
I'll implement this into Jenkins so we can use their [api](https://docs.readthedocs.io/en/stable/api/v3.html#versions) to activate a version and build it.

**Comment by mitzimorris** [comment]
@serban-nicusor-toptal - just a heads up - I'm going to move stuff around so that we'll also have docs via github pages - following instructions here:  https://www.docslikecode.com/articles/github-pages-python-sphinx/

**Comment by mitzimorris** [comment]
docs are now available at:  https://mc-stan.org/cmdstanpy/

what needs to be done for `readthedocs.io` config?

**Comment by serban-nicusor-toptal** [comment]
For readthedocs we can either have a trigger on cmdstanpy and when a new release(tag) is pushed we'll automatically use this [job](https://jenkins.mc-stan.org/job/ReadTheDocs/build?delay=0sec) to activate and build that specific version on readthedocs or use the [job](https://jenkins.mc-stan.org/job/ReadTheDocs/build?delay=0sec) by hand after a release.

From what I understood [here](https://docs.readthedocs.io/en/stable/versions.html) is that we have selected develop for latest, which means latest will point to the newest code in develop ( head commit ) at any time. For stable, it will always point to the latest release (tag)

**Comment by mitzimorris** [comment]
> From what I understood here is that we have selected develop for latest, which means latest will point to the newest code in develop ( head commit ) at any time. For stable, it will always point to the latest release (tag)

this makes sense - exactly what we need.

> They support webhook integration and automation rules. I've created a new rule that will activate and build any new tag created in github.

excellent!

just created an issue w/r/t capturing this information - for now, put it into a wiki and hope that we can keep it up-to-date.

**Comment by mitzimorris** [comment]
>   I've created a new rule that will activate and build any new tag created in github.

nice!  one nagging readthedocs question:  why doesn't stable show the tag?  presumably, https://cmdstanpy.readthedocs.io/en/stable/ is 0.9.66 because it's linked to from PyPi - the previous version docset does show the tags:  https://cmdstanpy.readthedocs.io/en/stable-0.9.65/

**Comment by serban-nicusor-toptal** [comment]
I would say that because stable always points to the latest release but showing it as stable, didn't find a way to override this. To make it look nicer we can disable `stable` and only have `latest` + releases (tags). What do you think? @mitzimorris

**Comment by mitzimorris** [comment]
> disable stable and only have latest + releases (tags)

much better - completely explicit and removes question of what is meant by `stable`

**Comment by serban-nicusor-toptal** [comment]
I've changed default version [here](https://readthedocs.org/dashboard/cmdstanpy/advanced/) to latest and removed stable from the list. ( de-activated the version in versions list )

**Comment by mitzimorris** [comment]
great - this guy is asking the same question as I have - tldr:  the answer seems to be "not possible" -
https://github.com/readthedocs/readthedocs.org/issues/4529

```
When I locally build the documentation, I see the version number displayed in the top-left, under the project name, as expected.

But when I look at the read-the-docs documentation, this version number is replaced with "latest".
```

**Comment by serban-nicusor-toptal** [comment]
Sadly I don't think we can change that, it's worth always keeping in mind that latest will point to the latest (head) commit in develop not to the latest release.
![image](https://user-images.githubusercontent.com/48496524/93794421-5a34cf80-fc38-11ea-9e15-1dc838498682.png)

If `latest` is the trouble we can try the following:

1. We remove latest, and keep our naming convention only ( based on git tags ) without stable. In this way we can manually and through the api ( I think ) set the default version ( as in the above pic )
2. We remove latest, put back stable which will always point to the stable version ( latest tag in github ) plus our naming convention. In this way we don't need to change default version as it would always point to stable version (the latest release).

What do you think @mitzimorris  ?

**Comment by mitzimorris** [comment]
if we can set the default version through the api, that would be nice, as readthedocs and github pages would match.

what would be ideal would be a release script for CmdStanPy that would, given a release tag:

 - create an appropriately tagged branch
 - update the file `cmdstanpy/_version.py` setting `__version__` to the tag
 - upload to PyPi
 - update readthedocs default version

@serban-nicusor-toptal - how does this get set up?  also, repo has file `https://github.com/stan-dev/cmdstanpy/blob/develop/.gitlab-ci.yml`.  this file is a holdover from "pycmdstan", an earlier incarnation of this project.  use this or delete?

**Comment by ahartikainen** [comment]
`.gitlab-ci.yml` can be deleted.

GH Actions can handle those requirements.

**Comment by mitzimorris** [comment]
just created issue #295 for release - 

@ahartikainen  and @serban-nicusor-toptal let me know what you need - I can send PyPi info

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/issues/282

**Comment by mitzimorris** [comment]
#304

**Comment by mitzimorris** [comment]
installation:  must be able to download from GitHub via script - disable VPN - cf https://github.com/stan-dev/cmdstanpy/issues/302

**Comment by imadmali** [comment]
> installation: must be able to download from GitHub via script - disable VPN - cf #302

It's good to have that as a suggestion, although it might not always be the case (and will probably vary based on VPN settings).

**Comment by mitzimorris** [comment]
troubleshooting installation - this was Linux, Jupyter notebooks - make needs to know about compiler, tbb:

https://github.com/stan-dev/cmdstanpy/issues/374#issuecomment-819031019

**Comment by mitzimorris** [comment]
need a clearer overview of CmdStanMCMC accessor functions - https://mc-stan.org/cmdstanpy/examples/MCMC%20Sampling.html#Accessing-the-sampler-outputs

summarize use cases / data types

**Comment by WardBrian** [comment]
Everything previously mentioned in this issue seems to be resolved, and going forward I think it's easier to track if documentation issues get their own issue each time (which we have more or less been doing as of late)
