### ISSUE TITLE
CMDSTAN now CMDSTAN_PATH

### ISSUE THREAD

**Issue by seantalts** [stan-dev/cmdstanpy#23]
#### Summary:
Looks like now cmdstanpy uses the CMDSTAN_PATH env variable instead of the CMDSTAN env variable to track the path of cmdstan. I think this just needs the docs and possibly tutorial ipython notebook to be updated.

[edit] actually apparently you can't set the cmdstan location anymore! I would personally really like to be able to set it...

[edit 2] I lied, you can set it:
```python
import cmdstanpy
cmdstanpy.CMDSTAN_PATH = "/path/to/cmdstan/
```

**Comment by mitzimorris** [comment]
fixed by PR #36, closing
