### ISSUE TITLE
expose method 'diagnose'

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#233]
#### Summary:
CmdStan provides method 'diagnose' for testing sampler behavoir.   Expose this by adding method `diagnose` to the CmdStanModel class.

#### Description:
Implementation parallels that of methods `sample`, `optimize`, etc.

- create class `DiagnoseArgs` in file `cmdstan_args.py` 
- add method `diagnose` to CmdStanModel class
- add documentation and notebook

#### Additional Information:
Provide any additional information here.

**Comment by mitzimorris** [comment]
The only available diagnostic is gradients of the log probability function, two arguments:

- epsilon=<real> Finite difference step size Valid values: 0 < epsilon (Defaults to 1e-6)
- error=<real> Error threshold Valid values: 0 < error (Defaults to 1e-6)

To invoke in CmdStan: 
```
 > ./my_model diagnose  test=gradient epsilon=<real> error=<real> \
                        data file=<string> iniit=<string> random seed=<int>
```

**Comment by mitzimorris** [comment]
documentation now online in CmdStan User's guide:

https://mc-stan.org/docs/2_24/cmdstan-guide/diagnosing-hmc-by-comparison-of-gradients.html

**Comment by WardBrian** [comment]
This is not considered useful, so we're closing the issue. If you really need it, open a new issue telling us how!
