### ISSUE TITLE
Runtime error when using custom list of chain IDs in sampling

### ISSUE THREAD

**Issue by xw363** [stan-dev/cmdstanpy#235]
I ran sampling with a custom list of chain IDs using `CmdStanModel.sample()` but got `TypeError: 'int' object is not iterable` on the following line:

https://github.com/stan-dev/cmdstanpy/blob/53aedc97ffce23064e9740b562c6a6b627a3e371/cmdstanpy/model.py#L599

Changing it to `for i in chain_ids:` should fix the issue.

Also, a suggestion regarding chain IDs: allow 0 as chain ID. Currently, cmdstanpy only allows positive integer IDs. In pystan, however, chain ID starts from 0 by default.

**Comment by ahartikainen** [comment]
0 chain id: That is also what is default for cmdstan.

**Comment by mitzimorris** [comment]
proposal is to remove "chain_id" as an option from the interface and handle this automatically.
https://docs.google.com/spreadsheets/d/1lU6vcY3GF_ftlFdCe2kDhr5FC4YJPWauC5bp2D9zz74

**Comment by mitzimorris** [comment]
CmdStan only runs one chain, therefore it default of zero makes sense.
User-facing indexing in CmdStanPy is 1-based, therefore this should also be 1-based.

**Comment by mitzimorris** [comment]
changing this to bug - testing on latest version 0.9.62 - "chain_id" not used in filename as advertised.
will fix.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/docs/pull/253
