### ISSUE TITLE
Runtime issue on Github Actions [Windows]

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#237]
#### Summary:

I have a model here, that just doesn't work on Windows. Some seeds let it go 3/4 "normally" but the last chain never really starts. Or is really slow. If I use 1 chain, same thing.

PyStan also struggles but can sample from this.

Any idea what is going on? Is this a threading issue? Should I call CmdStanPy some other way?

See 

- [Repo](https://github.com/ahartikainen/stan_performance_testing)
- [CmdStanPy setup](https://github.com/ahartikainen/stan_performance_testing/blob/master/.github/workflows/workflow-CmdStanPy.yml) 
- [CmdStanPy model and sampling](https://github.com/ahartikainen/stan_performance_testing/blob/master/run_CmdStanPy.py)
- [Github Actions](https://github.com/ahartikainen/stan_performance_testing/actions)

#### Additional Information:
Provide any additional information here.

Linux samples fine
macOS samples ... ok

PyStan same, but Windows works.

#### Current Version:

pypi version (0.9.5)

**Comment by mitzimorris** [comment]
I took a quick read through your model and data - 
what are you trying to test?  
is this model designed to be challenging to fit?  computationally intensive?

**Comment by ahartikainen** [comment]
It is challenging to fit. It is 2-3 times faster on Linux vs Windows/macOS.

It is an example from discourse.

https://discourse.mc-stan.org/t/large-cmdstan-performance-differences-windows-vs-linux/14415

**Comment by ahartikainen** [comment]
I mean, I'm not sure, but I think CmdStan might crash, but CmdStanPy don't see it (or it is a github actions thing).

I really need to test this locally.

**Comment by mitzimorris** [comment]
@ahartikainen - OK to close this?
