### ISSUE TITLE
`chains=` argument to `sample` doesn't seem to run chains in parallel

### ISSUE THREAD

**Issue by seantalts** [stan-dev/cmdstanpy#24]
#### Summary:
I'm running sample(model, data=dict(...), chains=4) and it just starts 1 chain at a time.

#### Current Version:
develop as of 6cfbc99

**Comment by maedoc** [comment]
The default number of CPU cores [used is now 1](https://github.com/stan-dev/cmdstanpy/commit/6cfbc9980db91154bd7f4401829ad3f8880294e8#diff-b8d077ea1a2451e04f2bd3bafeeb7bb1R57), try `sample(..., cores=4)`.

If desirable, the number of cores could be set automatically with `multiprocessing.cpu_count()`

**Comment by ahartikainen** [comment]
PyStan uses

    min(cpu_count, nchain)

**Comment by mitzimorris** [comment]
unit tests run 4 chains on 2 cores - this works.

**Comment by seantalts** [comment]
I guess this is just another "the docs are outdated" issue, haha. Sorry about that.
