### ISSUE TITLE
CmdStanMCMC object - add function `get_var` and `get_vars`

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#245]
#### Summary:

For container program variables, i.e., vectors, matrices, and arrays, users need to be able to get the draws for that variable structured accordingly. For scalar variables, this is easy; it is just one column's worth of data and the variable name matches the column name.
For structured variables, we need to assemble all element of the container.

This corresponds to the RStan function `extract`.

**Comment by ahartikainen** [comment]
Should this be similar as in PyStan3?

cc @riddell-stan

**Comment by mitzimorris** [comment]
> Should this be similar as in PyStan3?

how is this done in PyStan3?

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/252
