### ISSUE TITLE
chain 1 returned error code -11

### ISSUE THREAD

**Issue by JohannesBuchner** [stan-dev/cmdstanpy#246]
#### Summary:
Unknown error code during sampling.

#### Description:
I was able to compile, but not sample from a model. The output is merely:

```
Chain 1 -   done:   0%|                                                                                                                        | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "myfile.py", line 44, in <module>
    fit = sm.sample(data2, chains=1, iter_sampling=250, show_progress=True)
  File "/home/user/.local/lib/python3.6/site-packages/cmdstanpy/model.py", line 712, in sample
    raise RuntimeError(err_msg)
RuntimeError: Error during sampling.
chain 1 returned error code -11
```

Simplifying to `sm.sample(data2)` yields the same result.

I then tried to find a listing of error codes by searching the cmdstan manual and the cmdstanpy docs for "error code", "exit", "return", but was not able to find anything.

#### Current Version:
cmdstan-2.23.0
cmdstanpy-0.9.5

**Comment by JohannesBuchner** [comment]
Potentially be caused by a segfault: https://github.com/stan-dev/cmdstan/issues/881

**Comment by mitzimorris** [comment]
do you want to make this issue about better error handling for CmdStanPy?

that -11 is indeed indicating segfault - https://stackoverflow.com/questions/53100218/python-subprocess-in-which-case-a-segfault-program-returns-11-or-139

**Comment by JohannesBuchner** [comment]
Either improved error handling, error message or documentation. I also created this issue so others can search for the error message and find an explanation.

**Comment by mitzimorris** [comment]
will work on all of the above.  the error handling is driven off of a notion of standard kinds of errors, but most of the distinctions are lost on end users.

**Comment by mitzimorris** [comment]
@jgabry this is an example of program error codes greater than 128 reported as negative return codes under python.
also note than when CmdStan segfaults, it won't return an error code, the system will.

evidently python expects return codes to be a signed 8-bit int, therefore 128 is -0 and 129 is -1, etc.

**Comment by mitzimorris** [comment]
not sure that CmdStan dumps out any useful information on segfault, but if it does, then it will be reported as part of the error message - https://github.com/stan-dev/cmdstanpy/pull/280
