### ISSUE TITLE
reduce_sum + STAN_NUM_THREADS has no effect on tutorial model runtime

### ISSUE THREAD

**Issue by grburgess** [stan-dev/cmdstanpy#247]
#### Summary:
Please provide a short couple sentence summary.
STAN_NUM_THREADS seems to have no effect on run time. 

#### Description:
Describe the issue as clearly as possible.
I have tried to run the example here:
https://mc-stan.org/users/documentation/case-studies/reduce_sum_tutorial.html

via CmdStanPy. But see no effect when changing the number of threads via the environment variable. I have compiled the model with these lines:
```python
model = CmdStanModel(stan_file="logit.stan", cpp_options={'STAN_THREADS': True})
```
I have modified make/local to contain:

CXXFLAGS += -DSTAN_THREADS

but nothing seems to affect the run time of the model

#### Additional Information:
Running in a Jupyter notebook via MacOS
2.9 GHz 6-Core Intel Core i9

#### Current Version:
'0.9.5'
Cmdstan version 2.23.0

**Comment by ahartikainen** [comment]
Hi, you need to compile CmdStan with '-DSTAN_THREAD`

If you are able to follow CmdStan manual (and use cmdline) then it is probably easiest to do that way. I'm not really sure, if we have code for recompiling cmdstan.

I think we should add functionality for that.

**Comment by mitzimorris** [comment]
agreed - we will add function - CmdStanR has this - I think it's called `rebuild_cmdstan()`.

**Comment by grburgess** [comment]
Thanks, this was what I was curious about. The manual (in cmdstan) was not super clear on this. So, the cpp_options just turn on a flag that is picked up by Stan *if* it is compile that way?

**Comment by grburgess** [comment]
That solved the issue. Cheers!

**Comment by grburgess** [comment]
It is incredibly easy to get around by rebuilding. I think the issue is that it is not clear what triggers the threading . I saw in some issues that reduce_sum is grepped and threading is turned on. So I was not sure if it was working. 

Also, reduce_sum works without threading being active. I've just switched from pystan and not used to this so was not intuitive. Now it makes perfect sense.
