### ISSUE TITLE
Allow use of Dockerized CmdStan

### ISSUE THREAD

**Issue by maedoc** [stan-dev/cmdstanpy#25]
#### Summary:

CmdStan on Windows is (still) a pain, see [here for example](https://discourse.mc-stan.org/t/cant-make-cmdstan-2-18-in-windows/5088/44), but generally toolchains are a "system" thing, testing différent versions would be also easier if Dockerized.

Cmdstanpy invokes CmdStan exécutables via command line, and it should be straightforward to swap out a direct invocation for a invocation via Docker: compilation & running go from

```shell
make -C $CMDSTAN_PATH O=3 path/to/bernoulli 
path/to/Bernoulli sample $args
```
to
```shell
docker run stan/cmdstan make -C $CMDSTAN_PATH O=3 path/to/bernoulli 
docker run stan/cmdstan path/to/Bernoulli sample $args
```
There's some path mapping to think about but it's certainly easier than trying to compile CmdStan wtih MSVC.

Most of it should be transparent to the user who would specify `CMDSTAN_PATH=docker` or similar.

**Comment by mitzimorris** [comment]
how much of discussion in https://github.com/stan-dev/cmdstanpy/issues/7 is relevant here?

**Comment by maedoc** [comment]
Windows (& macOS) have their proprietary runtimes and you can't ship your own toolchain which #includes & links to that runtime, so getting a C++ toolchain is always a bear, macOS just makes it a little easier than Windows.

This issue was a bit speculative, I'd admit.  I have usually just setup a VM to run stuff on shared folders and not worried about it, but this is challenging for some users

**Comment by WardBrian** [comment]
At this point in the project we have a lot of strong alternatives for toolchain installation, so we've decided this is not necessary at this time. If there is a future use which requires this we can reevaluate then
