### ISSUE TITLE
Ability to change confidence intervals in summary

### ISSUE THREAD

**Issue by petulla** [stan-dev/cmdstanpy#250]
#### Summary:
Hi, wondering if there is a way to pass in the `probs` argument to summary, as in stansummary. I'd like to alter the CIs.

#### Additional Information:
For example, ideally we could do..
```py
bino_fit.summary(probs=[0.025,0.975])
```

#### Current Version:
0.9.5

**Comment by mitzimorris** [comment]
> "as in stansummary" 

are you referring to the RStan implementation?  the CmdStan `bin/stansummary` utility has these hardcoded - https://github.com/stan-dev/cmdstan/blob/fd7262ec6e7a987d8b386dfd8817eff323dfaa36/src/cmdstan/stansummary.cpp#L110-L111

but it would be easy to change this on the CmdStan side.   will file an issue.

**Comment by petulla** [comment]
yeah, I noticed rStan/PyStan [takes the probs argument](https://pystan.readthedocs.io/en/latest/api.html#pystan.StanFit4model.stansummary). I read CMDstan calls stansummary, so just thinking the API's could mirror each other's kwargs.

**Comment by bob-carpenter** [comment]
+1 for this feature---I use it all the time in RStan.

**Comment by mitzimorris** [comment]
great - will try to get this in for 2.24 release

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/265
