### ISSUE TITLE
document workflow encapsulation of model, data, output files

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#251]
#### Summary:
Generalize "save_csvfiles" to "save_fit" which saves Stan program sources, input data (json), and outputs into a named directory which can be compressed as a tgz file

#### Description:
Complication: if model has includes, need to be able to capture expanded program.

#### Additional Information:
Provide any additional information here.

**Comment by jgabry** [comment]
Here are some similar functions in CmdStanR for reference: 

http://mc-stan.org/cmdstanr/reference/fit-method-save_output_files.html

**Comment by mitzimorris** [comment]
snapshot?
checkpoint?

**Comment by ahartikainen** [comment]
tgz? gzip?

**Comment by mitzimorris** [comment]
> tgz? gzip?

@ahartikainen - you mean as alternative output formats?  good call.

**Comment by mtwest2718** [comment]
It would be worthwhile to have an equivalent `unpack` method.

**Comment by mitzimorris** [comment]
as of #432, docs have section "CmdStanPy workflow" and example notebooks are online.
further tooling to encapsulate an analysis is beyond the scope of the CmdStanPy package.
