### ISSUE TITLE
release schedule?

### ISSUE THREAD

**Issue by seantalts** [stan-dev/cmdstanpy#255]
Just wondering - is this going to be released soon? Would love to start using @mitzimorris's new stan_var functions and saw 2.24 come out a couple days ago.

**Comment by mitzimorris** [comment]
no there's not an official release schedule.  coordinating with CmdStanR - there's two things:  get all names the same with consistent levels of verbosity - `stan_variable` and `stan_variable_dims` - and more docs with examples.

if you have suggestions on the docs, that would be much appreciated.

**Comment by seantalts** [comment]
Ah gotcha, thanks!

**Comment by mitzimorris** [comment]
hi @seantalts - just released a new version of CmdStanPy which exposes `stan_variable` etc - 0.9.62

trying to reduce the list of issues and will be submitting a lot of small pull requests.  if you have spare cycles for code review, would be happy to get your feedback.
