### ISSUE TITLE
Address any Arviz integration issues

### ISSUE THREAD

**Issue by maedoc** [stan-dev/cmdstanpy#26]
#### Summary:

> [ArviZ](https://github.com/arviz-devs/arviz) (pronounced "AR-vees") is a Python package for exploratory analysis of Bayesian models. Includes functions for posterior analysis, model checking, comparison and diagnostics.

from #14, the previous pycmdstan included some plotting code that was agreed better replaced by a downstream library in a typical workflow, ArviZ came up. It would be nice to 

- [ ] address any integration issues
- [ ] include in a short guide showing how easy it is

**Comment by ahartikainen** [comment]
For now there are a few possibilities

### `az.from_cmdstan`
Read CmdStan csv files with `az.from_cmdstan`

    import arviz as az
    # input a list of filepaths or glob string (takes * or [0-9])
    idata = az.from_cmdstan(posterior="path/to/files/model_output_[0-9].csv")
    # traceplot
    az.plot_trace(idata)
    # summary
    summary = az.summary(idata)

### `az.from_dict`
Create InferenceData object with `az.from_dict` that eats dictionaries with parameter names as keys and ndarrays as values (shape=(nchain, ndraw, *shape)


    import arviz as az
    idata = az.from_dict(posterior={"alpha" : alpha, "Beta" : beta})
    # traceplot
    az.plot_trace(idata)

In future I want to implement `from_cmdstanpy`. Is there any way to check if the input is from `cmdstanpy`? If there is some way to validate it, we can implement the functionality so, that it automatically reads parameters/sampler params correctly.

https://arviz-devs.github.io/arviz/generated/arviz.from_cmdstan.html
https://arviz-devs.github.io/arviz/generated/arviz.from_dict.html

**Comment by maedoc** [comment]
>  implement from_cmdstanpy. Is there any way to check if the input is from cmdstanpy?

The `sample` function returns a `PosteriorSample` object which seems appropriate argument to `from_cmdstanpy`.  The [unit test](https://github.com/stan-dev/cmdstanpy/blob/master/test/test_posterior_sample.py#L49) has useful example, 
```python
        post_sample = sample(model, data_file=jdata)
        self.assertEqual(post_sample.chains,4)
        self.assertEqual(post_sample.draws,1000)
        self.assertEqual(post_sample.column_names, tuple(column_names))
        post_sample.sample
        self.assertEqual(post_sample.sample.shape,(1000, 4, 8))
```

**Comment by ahartikainen** [comment]
Yes, that is perfect.

**Comment by ahartikainen** [comment]
Hi, I implemented `from_cmdstanpy`.

It is currently on master but we are doing new release (includes new rhat/ess etc) in a few days.

https://github.com/arviz-devs/arviz/pull/671

Now both of these work

    import arviz as az

    idata = az.from_cmdstanpy(fit)
    az.plot_trace(idata)

and

    az.plot_trace(fit)

**Comment by ahartikainen** [comment]
I will close this, once cmdstanpy hits pypi (is not beta anymore) and I can create tests for arviz.

**Comment by ahartikainen** [comment]
Basic tests are implemented and ArviZ (GitHub master) works with cmdstanpy. Next release in August.
