### ISSUE TITLE
How to access debug (stdout/stderr) when model fails

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#267]
#### Summary:
Please provide a short couple sentence summary.

How to access debug (stdout/stderr) when model fails?

#### Description:
Describe the issue as clearly as possible.

> stan_example.stan
```stan
parameters {
    real y;
}
model {
    target += normal_lpdf(y | 0, 1);
}
```

```python
import cmdstanpy
model = cmdstanpy.CmdStanModel(stan_file="stan_example.stan")
# this fails
fit = model.sample(iter_sampling=10, iter_warmup=0, chains=1)
```

```
RuntimeError: Error during sampling.
chain 1 returned error code 78
```

#### Additional Information:
Provide any additional information here.

Manual access to `cmdstanpy._TMPDIR`

```python

import os
import platform
import subprocess

def open_file(path):
    if platform.system() == "Windows":
        os.startfile(path)
    elif platform.system() == "Darwin":
        subprocess.Popen(["open", path])
    else:
        subprocess.Popen(["xdg-open", path])

open_file(cmdstanpy._TMPDIR)
``` 

#### Ideas

Should we add a function to read latest stdout?
Also are we missing `verbose` argument?

Maybe a similar function as _read_progress but only for printing (and if progress bar is used, then printing with `pbar.write`)

```python
    def _verbose_progress(
        self, proc: subprocess.Popen, idx: int
    ) -> bytes:
        try:
            # iterate while process is sampling
            while proc.poll() is None:
                output = proc.stdout.readline()
                stdout += output
                output = output.decode('utf-8').strip()
                print("Chain {idx}: {output}")
        ...
```

We could then even filter output msg that are for progress, if progressbar is enabled.

#### Current Version:

github master
W10 RTools40

**Comment by mitzimorris** [comment]
the set of output files produced by function `_run_cmdstan` in `model.py` are here:  https://github.com/stan-dev/cmdstanpy/blob/e0cb9a2a718c2b0d3e0e609fc35cc8934d99ff99/cmdstanpy/stanfit.py#L51-L85

do we want an easy way to expose them?

**Comment by ahartikainen** [comment]
Some way to access would be nice. When compilation fail, exception is raised and no fit object is created.

**Comment by mitzimorris** [comment]
if the return code is non-zero, we should definitely print stderr to the console.

the problem with the return codes is that the Stan services layer defines the return codes in terms of a set of posix return codes which are not appropriate for end users.  also different platforms expect them to be a signed short in (8-bits) so any return code greater than 127 is reported as a negative number, which is very confusing - I think I've seen this for reports of out-of-memory errors?
also, segfault short-circuits this - no more process, no more pipes.

**Comment by mitzimorris** [comment]
OK, now I understand the question:  when compilation fails, what happens?

- compilation called from CmdStanModel constructor 
- compilation called via `compile` function

> When compilation fail, exception is raised and no fit object is created

when compilation fails during construction, no model object is created, right?
when compilation fails from call to `compile` function, model object exists, but `exe_file` should be `None` - will check that that always happens

if `exe_file` is none, then call to `sample` method should return a sensible error message - will check.

**Comment by ahartikainen** [comment]
Yes, I also now see that description is wrong... Yeah, no model object is created.

**Comment by mitzimorris** [comment]
marking this as a duplicate because it's subsumed by https://github.com/stan-dev/cmdstanpy/issues/152.
