### ISSUE TITLE
`sample` function should allow CmdStan `engaged` argument

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#27]
#### Summary:
CmdStan's HMC sampler has argument `engaged` which controls whether or not the sampler does adaption.  when `engaged=0` the sampler skips adaptation altogether and will use whatever values the `stepsize` and `mass_matrix` are set to.

#### Description:

+ Add `engaged` attribute to `SamplerArgs` object - update functions `validate` and `compose_command` accordingly
+ Add `engaged` argument to `sample` command

#### Additional Information:
Extensive discussion of proper use of options engaged/ num_warmups here: https://github.com/stan-dev/cmdstan/pull/604

**Comment by mitzimorris** [comment]
The CmdStanPy equivalent of CmdStan’s `engaged` arg is `do_adaptation`

CmdStanPy is lacking args for `init_buffer`, `window`, and `term_buffer`.
These should all be positive integer values.

If `do_adaptation` is False, all adaptation args should be None - `validate` function should check these.

**Comment by bob-carpenter** [comment]
> If do_adaptation is False, all adaptation args should be None - validate function should check these.

Is there a way to structure a single argument to remove the dependency?  These things become very hard to document and test very quickly.

**Comment by maedoc** [comment]
Grouping complex arguments might be done better with a [`dataclass`](https://docs.python.org/3/library/dataclasses.html) instead of trying to munge a flat set of interdependent arguments.

**Comment by mitzimorris** [comment]
thanks @maedoc - will do.

**Comment by mitzimorris** [comment]
will roll this into work done on issue #28

**Comment by mitzimorris** [comment]
fixed via https://github.com/stan-dev/cmdstanpy/pull/52
