### ISSUE TITLE
How to install cmdstan to a specific directory and then use that install

### ISSUE THREAD

**Issue by seantalts** [stan-dev/cmdstanpy#275]
#### Summary:
I'm confused about the workflow for CmdStanPy if I would like it to manage my cmdstan for me. 

#### Description:
What I want to type is something like
```python
import cmdstanpy
cmdstanpy.install_cmdstan(dir="~/blah/")
```

But I'm having I think 3 separate issues:
1. Installing cmdstan does not set the cmdstan path
2. Using "~" seems to throw an error
3. The error is logged somewhere (I can't find it using this from a python notebook) so for me it is effectively swallowed (this happens [here](https://github.com/stan-dev/cmdstanpy/blob/5f4256e5c20dcc79ac4fbc42e13c6e5f471ee84e/cmdstanpy/utils.py#L910))

So I'm using this right now and I think it's working:
```python
import cmdstanpy
cmdstanpy.install_cmdstan(dir="/fast_drive/.cmdstanpy")
cmdstanpy.set_cmdstan_path("/fast_drive/.cmdstanpy/cmdstan-2.24.0")
```
(Note the additional version at the end of the last one)

#### Current Version:
0.9.63

**Comment by mitzimorris** [comment]
will investigate and fix as part of addressing issues https://github.com/stan-dev/cmdstanpy/issues/227  and https://github.com/stan-dev/cmdstanpy/issues/262

regarding the difference between path - directive
```
cmdstanpy.install_cmdstan(dir="/fast_drive/.cmdstanpy")
```
by default finds the latest release and installs it.

for anything other than the default path - $HOME/.cmdstanpy/<latest release> - the full path is required - guessing is too hard.

**Comment by seantalts** [comment]
Thanks, that makes sense about the version number.

**Comment by ahartikainen** [comment]
have you tried

    python -m cmdstanpy.install_cmdstan --dir ~/blah

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/301  - better documentation as part of PR

**Comment by seantalts** [comment]
The issue is still valid in my opinion - I would expect this to work but it does not work:
```python
import cmdstanpy
cmdstanpy.install_cmdstan(dir="~/blah/")
```

From Python, what you have to use instead is:
```python
import cmdstanpy
cmdstanpy.install_cmdstan(dir="/fast_drive/.cmdstanpy")
cmdstanpy.set_cmdstan_path("/fast_drive/.cmdstanpy/cmdstan-2.24.0")
```
Except that obviously the version number changes with each release.

**Comment by mitzimorris** [comment]
reopening - will close when documentation is sufficiently clear one what "dir" and "version" mean.

**Comment by mitzimorris** [comment]
would renaming "dir" to "base_dir" remove confusion?
@seantalts, @jgabry

**Comment by seantalts** [comment]
@mitzimorris 100% agree with current design as you've put it. I think the one thing I'd change (sorry I wasn't clear on this earlier) is that we shouldn't have to call `cmdstanpy.set_cmdstan_path("/fast_drive/.cmdstanpy/cmdstan-2.24.0")` after installing, in my opinion.

**Comment by mitzimorris** [comment]
agreed, this would be smoother and more natural, and easy to implement: the last thing function `install_cmdstan` does is set environment var `CMDSTAN_PATH`.

however, this won't persist beyond the session - setting this permanently would require a using a package like python-dotenv (https://pypi.org/project/python-dotenv/).  it should be an optional dependency, similar to use of tqdm and ujson.

**Comment by ahartikainen** [comment]
What if we add a config file to `.cmdstan` or package dir that is read at import?

I don't like that python envs touch global settings.

**Comment by mitzimorris** [comment]
> I don't like that python envs touch global settings.

exactly.

> What if we add a config file to .cmdstan or package dir that is read at import?

there's a lot of things we *could* do.  I prefer to implement as few features as possible when there are decent workarounds.  in this case, workaround is that production scripts call `set_cmdstan_path` or otherwise set the environment variable `CMDSTAN_PATH` - which is perfectly explicit and therefore easy to troubleshoot and maintain,
both on the package side and on the user application side.

**Comment by seantalts** [comment]
I'm not sure if this was clear from the report but `install_cmdstan(dir=...)` doesn't set the cmdstan_path to the path that it just immediately installed to, for some reason. This just seems like a small bug? Here's what this looks like in action:
```
>>> cmdstanpy.install_cmdstan(dir="~/sars/")
Installing CmdStan version: 2.24.1
Install directory: ~/sars/
Downloading CmdStan version 2.24.1
Download successful, file: /tmp/tmpvdif4hlr
Unpacked download as cmdstan-2.24.1
Building version cmdstan-2.24.1
Test model compilation
Installed cmdstan-2.24.1
deleting tmpfiles dir: /tmp/tmpxvnogcdw
done

True
>>> cmdstanpy.CmdStanModel(stan_file="~/test.stan")
INFO:cmdstanpy:compiling stan program, exe file: /home/xitrium/test
INFO:cmdstanpy:compiler options: stanc_options=None, cpp_options=None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xitrium/stanpyenv/lib/python3.8/site-packages/cmdstanpy/model.py", line 162, in __init__
    self.compile()
  File "/home/xitrium/stanpyenv/lib/python3.8/site-packages/cmdstanpy/model.py", line 295, in compile
    do_command(cmd, cmdstan_path(), logger=self._logger)
  File "/home/xitrium/stanpyenv/lib/python3.8/site-packages/cmdstanpy/utils.py", line 140, in cmdstan_path
    raise ValueError(
ValueError: no CmdStan installation found, run command line script "install_cmdstan"
```
