### ISSUE TITLE
`stan_variable` return pandas dataframe to allow for named columns

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#276]
#### Summary:
`stan_variable` function returns a numpy.nd array, but a pandas dataframe would allow us to keep the column names from the Stan csv file.

#### Description:
Describe the issue as clearly as possible.

#### Additional Information:
Provide any additional information here.

**Comment by LukasNeugebauer** [comment]
Hey!
I haven't ever contributed any code to anything, but I would like to start doing that and this seems like a reasonable first problem.
One question I have is wether the function should return a pd.Series if the variable is a scalar or a Nx1 pd.DataFrame for consistency? 
May I have it?

**Comment by mitzimorris** [comment]
please do!

**Comment by mitzimorris** [comment]
> One question I have is wether the function should return a pd.Series if the variable is a scalar or a Nx1 pd.DataFrame for consistency?

good question - according to SO: https://stackoverflow.com/questions/26047209/what-is-the-difference-between-a-pandas-series-and-a-single-column-dataframe

my instinct is to go with all pd.DataFrames for consistency as long as this doesn't incur performance or memory penalties.  here I rely on @ahartikainen's superior Python knowledge - I'm really an old school Java programmer at heart.

**Comment by ahartikainen** [comment]
Could you describe a bit the output format? A table with chains stacked in a wide format (wide format == cmdstan output)?

both dataframe and series are fine, but consistent output is better than conditional one.

**Comment by LukasNeugebauer** [comment]
> my instinct is to go with all pd.DataFrames for consistency as long as this doesn't incur performance or memory penalties. here I rely on @ahartikainen's superior Python knowledge - I'm really an old skool Java programmer at heart.

That's also my intuition. 

> Could you describe a bit the output format? A table with chains stacked in a wide format (wide format == cmdstan output)?
> 

Sure. The output of stan_variable() is a numpy array of post-warmup samples with chains concatenated. So a vector[2] variable with 4 chains of 1000 samples each would become a 4000X2 array. Right now, scalar variables produce arrays without singleton dimension. 

> both dataframe and series are fine, but consistent output is better than conditional one.

I'll go with DataFrames in both cases.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/287
