### ISSUE TITLE
Better error message when compilation fails due to toolchain problems

### ISSUE THREAD

**Issue by lwiklendt** [stan-dev/cmdstanpy#282]
#### Summary:
Running the example script shown on the front page (after deleting `bernoulli.exe` from the examples path) results in a compilation error.

#### Description:
```
ERROR:cmdstanpy:file C:\Users\Luke\.cmdstanpy\cmdstan-2.24.1\examples\bernoulli\bernoulli.stan, exception ERROR
 'cut' is not recognized as an internal or external command,
operable program or batch file.
'cut' is not recognized as an internal or external command,
operable program or batch file.
process_begin: CreateProcess(NULL, rm -f C:/Users/Luke/.cmdstanpy/cmdstan-2.24.1/examples/bernoulli/bernoulli.o, ...) failed.
```

**Comment by ahartikainen** [comment]
I recommend you install RTools (4.0 by default)

    python -m cmstanpy.install_cxx_toolchain
    # you might need to accept installation from popup window

And then When starting script (before compile), do

    import cmdstanpy
    cmdstanpy.utils.cxx_toolchain_path()
    # add rest of the code here

**Comment by lwiklendt** [comment]
Fantastic, that solved the error, thanks!

**Comment by mitzimorris** [comment]
many thanks @ahartikainen !  we should put this into the docs

**Comment by ahartikainen** [comment]
Yes we should.

**Comment by mitzimorris** [comment]
this is a failure in the `compile` command - https://github.com/stan-dev/cmdstanpy/blob/798e178833a92a1959953595312416374bbf8c76/cmdstanpy/model.py#L283-L289

because compilation happens by default on model instantiation, the current error message is not explicit enough - it should be changed to something like the following:
```
Unable to compile Stan model.  
See <documentation link> on troubleshooting compiler.
Model file {}
Error message {}
```

suggestions welcome on wording of line 2 of this error message.

**Comment by mitzimorris** [comment]
updated title to reflect the problem.

**Comment by WardBrian** [comment]
Error messages have improved a lot since the last activity here, so we're closing this issue. Thanks!
