### ISSUE TITLE
Specify path for compiled Stan program

### ISSUE THREAD

**Issue by imadmali** [stan-dev/cmdstanpy#289]
Hi - With `cmdstanpy` it would be great to be able to specify the path in `CmdStanModel` to where the compiled Stan program will be saved, similar to the way you can use the `output_dir` argument in `CmdStanModel.sample()`?

(FYI - I first raised this issue on discourse [here](https://discourse.mc-stan.org/t/specifying-path-to-compiled-stan-program-with-cmdstanpy/17986).)

**Comment by ahartikainen** [comment]
Thanks for the issue.

I wonder if there is a way to select output folder already at the compilation step or do we need to move the executable after the compilation?

**Comment by ahartikainen** [comment]
These are just notes for devs, no need to answer:


- `output_dir` should probably go to `CmdStanModel.__init__`, but maybe we need also a method to set it.
- if `exe_file` is used, `output_dir` needs to be ignored.

```
        if exe_file is not None:
            self._exe_file = os.path.realpath(os.path.expanduser(exe_file))
            if not os.path.exists(self._exe_file):
                raise ValueError('no such file {}'.format(self._exe_file))
            _, exename = os.path.split(self._exe_file)
            if self._name is None:
                self._name, _ = os.path.splitext(exename)
            else:
                if self._name != os.path.splitext(exename)[0]:
                    raise ValueError(
                        'Name mismatch between Stan file and compiled'
                        ' executable, expecting basename: {}'
                        ' found: {}.'.format(self._name, exename)
                    )
```

So, we need another step here for `shutil.copy`

```
    with TemporaryCopiedFile(self._stan_file) as (stan_file, is_copied):
            exe_file, _ = os.path.splitext(os.path.abspath(stan_file))
            exe_file = Path(exe_file).as_posix() + EXTENSION
            do_compile = True
            if os.path.exists(exe_file):
                src_time = os.path.getmtime(self._stan_file)
                exe_time = os.path.getmtime(exe_file)
                if exe_time > src_time and not force:
                    do_compile = False
                    self._logger.info('found newer exe file, not recompiling')

            if do_compile:
                self._logger.info(
                    'compiling stan program, exe file: %s', exe_file
                )
                if self._compiler_options is not None:
                    self._compiler_options.validate()
                    self._logger.info(
                        'compiler options: %s', self._compiler_options
                    )
                make = os.getenv(
                    'MAKE',
                    'make'
                    if platform.system() != 'Windows'
                    else 'mingw32-make',
                )
                cmd = [make]
                if self._compiler_options is not None:
                    cmd.extend(self._compiler_options.compose())
                cmd.append(Path(exe_file).as_posix())
                try:
                    do_command(cmd, cmdstan_path(), logger=self._logger)
                except RuntimeError as e:
                    self._logger.error(
                        'file %s, exception %s', stan_file, str(e)
                    )
                    compilation_failed = True

            if not compilation_failed:
                if is_copied:
                    original_target_dir = os.path.dirname(
                        os.path.abspath(self._stan_file)
                    )
                    new_exec_name = (
                        os.path.basename(os.path.splitext(self._stan_file)[0])
                        + EXTENSION
                    )
                    self._exe_file = os.path.join(
                        original_target_dir, new_exec_name
                    )
                    shutil.copy(exe_file, self._exe_file)
                else:
                    self._exe_file = exe_file
                self._logger.info('compiled model file: %s', self._exe_file)
            else:
                self._logger.error('model compilation failed')
```

**Comment by imadmali** [comment]
Cool, also I'd be more than happy to contribute and create a PR if you like.

Also my suggestion would be to have it print a message (or error) if both `exe_file` and `output_dir` are specified. Similarly if `exe_file` and `stan_file` are both specified. The reason being that a user specifying both is assuming a certain behavior and the conditional is fixing that without letting them know that their assumption is wrong.

**Comment by ahartikainen** [comment]
Sure, you can do the PR.

Similar warning for exe_file and output_dir is fine.

I don't think we need to worry anything else than those parts of code (compilation step). After that `exe_file` is only used to call the executable.

So we need to define `self.output_dir` and add a method `.set_output_dir`.

I think we need to add here a check if output_dir is defined, then use it as `original_target_dir ` otherwise do the current procedure. (https://github.com/stan-dev/cmdstanpy/blob/develop/cmdstanpy/model.py#L293)

```
                original_target_dir = os.path.dirname(
                        os.path.abspath(self._stan_file)
                    )
                    new_exec_name = (
                        os.path.basename(os.path.splitext(self._stan_file)[0])
                        + EXTENSION
                    )
                    self._exe_file = os.path.join(
                        original_target_dir, new_exec_name
                    )
```

What is the key used on CmdStanR? `dir`? I'm fine with that too.

Is there something else that `dir` does in CmdStanR?

**Comment by imadmali** [comment]
Yeah it looks like cmdstanr uses `dir` as the the argument in this case. @jgabry is there any reason for the argument difference between specifying a write path in sampling and compiling. In [sampling](https://mc-stan.org/cmdstanr/reference/model-method-sample.html) it's `output_dir` and in [compile](https://mc-stan.org/cmdstanr/reference/model-method-compile.html) it's `dir`. It seems a little inconsistent to me. Or is this something that's been adopted from cmdstan?

**Comment by jgabry** [comment]
Yeah you're right it's a bit inconsistent. We also use `dir` in `install_cmdstan()` because `output_dir` didn't quite feel right as an argument name specifying an installation location. To me the argument for the compile method seemed more similar to installation (both involve building executables) than to writing csv output files, so we went with `dir` for that one to match `install_cmdstan()`. 

But yeah I guess it's a bit weird to have both `output_dir` and `dir`. If we want to unify the names then we should go with `dir` instead of `output_dir` for all of them. That way it also makes sense for installation. 

What do you all think?

**Comment by mitzimorris** [comment]
> `output_dir` didn't quite feel right as an argument name specifying an installation location. 
agreed.

for sampling, there's a lot of files involved - inputs, inits, outputs.  since (currently) there's only a single input data and init params file across all chains, specifying full path to these files is OK.

**Comment by imadmali** [comment]
> If we want to unify the names then we should go with dir instead of output_dir for all of them. That way it also makes sense for installation.

I agree. It will make the user experience better; they can assume the name of certain args.

**Comment by mitzimorris** [comment]
just plain `dir` makes sense instead of `output_dir`

**Comment by jgabry** [comment]
Ok cool. I'll open an issue for cmdstanr to deprecate `output_dir` in favor of `dir`.

**Comment by mitzimorris** [comment]
so the convention is that the arguement name `dir` is used whenever the user can override a default location _for methods which write something to disk_

**Comment by imadmali** [comment]
Another thing to consider is that `dir()` is a [built in function](https://docs.python.org/3/library/functions.html#dir) that is used to access the names of variables in scope. Is this being used (or has plans to be used) anywhere in the compile or sampling methods?

**Comment by ahartikainen** [comment]
It is fine to overwrite `dir` function, we don't plan to use it and function arguments / variables doesn't affect users functions.

**Comment by mitzimorris** [comment]
> I wonder if there is a way to select output folder already at the compilation step or do we need to move the executable after the compilation?

you need to move the exe after compilation - the CmdStan makefile assumes that the Stan file, the generated hpp file, and the output file are all in the same directory.

CmdStanPy and CmdStanR seem to do different things w/r/t to temp dirs.  CmdStanPy's handling of tmp dirs (implemented by some Prophet folks), handles potential problems with spaces in the file path via utility methods "TemporaryCopiedFile". 

also, in order to keep track of hpp file, we need to keep track of both stan src dir and exe dir - this is where just calling things "dir" gets tricky - we have both a source and a target dir here.

**Comment by mitzimorris** [comment]
@jgabry - is CmdStanR copying stan file over to tmp dir in order to do compilation by default?  see above comment - trying to work through all the implications of this proposal and how it impacts exposing location of hpp file.

**Comment by mitzimorris** [comment]
perhaps we really want a more specific name for `dir` everywhere.
and really, the `dir` option should be `exe_dir`, we track location of `src_dir`, and CmdStanR function should eliminate `dir` arg to `save_hpp_file` - by default, hpp file is saved to whatever location source file is in.  (and if you can't write to that dir, so be it).

**Comment by imadmali** [comment]
@ahartikainen @mitzimorris I wanted to check a few things based on the discussion in this thread (assume for the moment that the output directory defined by the user is `output_dir`). Here are the things that need to be done.

1. Add the attribute `self._output_dir` to `CmdStanModel.__init__`.
2. Error check if both `exe_file` and `output_dir` are defined.
3. Move the exe/hpp files to `output_dir` and delete the exe/hpp files in the the same directory that contains the Stan program.

I'm not sure if (3) should be done in `is_copied` [here](https://github.com/stan-dev/cmdstanpy/blob/develop/cmdstanpy/model.py#L292) or in a following `elif` clause. If I do it in the `is_copied` condition then I would have to set it to `True` prior to reaching that condition. Tbh I'm not really sure what triggers `is_copied` to be true.

**Comment by mitzimorris** [comment]
I think this is too complicated.
the API already provides the necessary functionality to do this:  

- the `exe_file` property exposes the full path to the model executable
- you can instantiate a CmdStanModel object by just specifying the `exe_file` arg.

once the exe file is moved away from the src dir,  then you can no longer use just the CmdStan makefile to get automatic recompilation whenever the src file changes; by the same token, if you have an exe file in some directory,  there's no way to match it up to the Stan src file.

I realize there's a mismatch between CmdStanPy and CmdStanR - @jgabry, in CmdStanR, can you instantiate a model just from the exe file?

**Comment by jgabry** [comment]
> @jgabry - is CmdStanR copying stan file over to tmp dir in order to do compilation by default? see above comment - trying to work through all the implications of this proposal and how it impacts exposing location of hpp file.

Good question. I forget off the top of my head. @rok-cesnovar implemented this so he may be able to answer immediately, but if he doesn't have time I can look into it.

**Comment by rok-cesnovar** [comment]
Yes. cmdstanr copies the stan file over to the tmp dir, compiles it there and move the exe file back. We do not copy the hpp file, except if the user demands it via hpp_file().

**Comment by imadmali** [comment]
> in short, it's fine if a user wants to do this, but we don't need to do it for them.

So I know I kicked this whole thing off, but the more I think about it I think it's totally fine to not have a user defined output directory for the binary generated by Stan (that is different from where the Stan program lives). If cmdstanpy is supposed to be a wrapper for cmdstan then I guess it shouldn't have additional features like this (that are not present in cmdstan).

**Comment by jgabry** [comment]
Ok great, thanks for clarifying Rok!

**Comment by markjrieke** [comment]
Howdy folks --- not necessarily looking to reopen the issue, but attaching some workaround code here in case future cmdstanpy users who run across this gh issue find it useful.

This is a small CmdStanModel extension that that \~mostly\~ mimics the cmdstanr behavior of allowing users to specify a `dir` where the executable will be created. The difference is that the model at `stan_file` is also copied over (for me, personally, this is fine, since I normally compile to a gitignored exe/ directory). The model is only recompiled when you make changes to `stan_file`. 

```python
from typing import Optional
from os.path import basename, dirname, join
from os import listdir, remove
from shutil import copy

import cmdstanpy as stan

class CmdStanModel(stan.CmdStanModel):

    """
    A small wrapper class around cmdstanpy's `CmdStanModel` class that adds
    functionality for generating an executable in a new directory. While this is
    functionally similar to the `cmdstan_model()` function in R, it differs in
    that the stan file is *also* copied to the new directory.
    """

    def __init__(
        self,
        stan_file: str,
        dir: Optional[str] = None,
        **kwargs
    ):

        if dir:
            # Check if the dir file needs to be updated
            if basename(stan_file) in listdir(dir):
                source_lines = open(stan_file).readlines()
                destination_lines = open(join(dir, basename(stan_file))).readlines()
                if source_lines != destination_lines:
                    copy(stan_file, dir)
            else:
                copy(stan_file, dir)

            # Init CmdStanModel object with new file location reference
            model_dir = dirname(stan_file)
            stan_file = join(dir, basename(stan_file))

            # Append stanc_options with model_dir in include-paths
            if 'stanc_options' in kwargs.keys():
                stanc_options: dict = kwargs.get('stanc_options')
                if 'include-paths' in stanc_options.keys():
                    include_paths = stanc_options.get('include-paths')
                    if type(include_paths) == str:
                        kwargs['stanc_options'].update({'include-paths': [include_paths, model_dir]})
                    elif type(include_paths) == list:
                        kwargs['stanc_options']['include-paths'].append(model_dir)
                    else:
                        raise TypeError('include-paths must be of type str or list.')
                else:
                    kwargs['stanc_options'].update({'include-paths': model_dir})
            else:
                kwargs.update({'stanc_options': {'include-paths': model_dir}})

        # Init the CmdStanModel object
        super().__init__(
            stan_file=stan_file,
            **kwargs
        )
```
