### ISSUE TITLE
Naming convention for objects that return pandas data frame

### ISSUE THREAD

**Issue by imadmali** [stan-dev/cmdstanpy#290]
Hi - The method `CmdStanMCMC.draws_as_dataframe` and attribute `CmdStanGQ.generated_quantities_pd` return the same type (a pandas data frame object). However the naming conventions are different. Is there a reason for this? Is it because one is a function an the other is a variable? If not can we choose one or the other? (My preference is `*_pd` since it's more concise.)

**Comment by mitzimorris** [comment]
good catch.

I think that the CmdStanMCMC method was named to match CmdStanR - will check.

**Comment by mitzimorris** [comment]
>  If not can we choose one or the other? (My preference is *_pd since it's more concise.)

agreed that "_pd" is more concise.  the question is how closely should CmdStanPy match CmdStanR?  put another way, is the interface more python-centric or more stan-centric?

**Comment by imadmali** [comment]
Good point. Normally I'd suggest keeping the cmdstan* interfaces consistent but `pd` (just like `np` for numpy) is such a commonly used alias (it's like almost a standard).

**Comment by mitzimorris** [comment]
> such a commonly used alias (it's like almost a standard)

agreed.

**Comment by imadmali** [comment]
It looks like this attribute would need to be renamed to `_draws_pd`
https://github.com/stan-dev/cmdstanpy/blob/798e178833a92a1959953595312416374bbf8c76/cmdstanpy/stanfit.py#L332
and this method would need to be renamed `draws_pd`
https://github.com/stan-dev/cmdstanpy/blob/798e178833a92a1959953595312416374bbf8c76/cmdstanpy/stanfit.py#L692
As well as changes made to where these two are referenced in the package. Is that right? Am I missing anything?

**Comment by mitzimorris** [comment]
nope, not missing anything - 

```
~/github/stan-dev/cmdstanpy (develop)> grep  -n "dataframe" */*.py
cmdstanpy/model.py:807:            sample_drawset = mcmc_sample.draws_as_dataframe()
cmdstanpy/model.py:852:                sample_drawset = sample_fit.draws_as_dataframe()
cmdstanpy/stanfit.py:692:    def draws_as_dataframe(
test/test_generate_quantities.py:120:            bern_fit.draws_as_dataframe().shape, bern_gqs.mcmc_sample.shape
test/test_sample.py:478:        draws_df = fit.draws_as_dataframe()
test/test_sample.py:538:        phis = fit.draws_as_dataframe(params=['phi'])
test/test_sample.py:540:        phi1 = fit.draws_as_dataframe(params=['phi[1]'])
test/test_sample.py:542:        mo_phis = fit.draws_as_dataframe(
test/test_sample.py:546:        phi2095 = fit.draws_as_dataframe(params=['phi[2095]'])
test/test_sample.py:551:            fit.draws_as_dataframe(params=['phi[2096]'])
test/test_sample.py:553:            fit.draws_as_dataframe(params=['ph'])
```

**Comment by imadmali** [comment]
Alright, I'll work on a PR.

**Comment by ahartikainen** [comment]
I'm fine with this.

I have not seen similar use before (for numpy I have seen this).

pd could mean dataframe or series.

df is a short for dataframe

ser is a short for series (or serial etc)

**Comment by imadmali** [comment]
> pd could mean dataframe or series.
df is a short for dataframe

That's a really good point. Now you got me thinking `*_df` or `` is better.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/296
