### ISSUE TITLE
package release tasks

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#295]
#### Summary:

automate and document procedure for creating distro package and docset for new releases of CmdStanPy.

#### Description:

It would be nice to have a release script for CmdStanPy that would, given a release tag:

- handle GitHub tags
- generate html docs for version and update `docs` dir contents for github pages
- update the file cmdstanpy/_version.py setting __version__ to the tag
- upload to PyPi
- update readthedocs default version so that readthedocs shows latest version number
- generate html docs for version and update `docs` dir contents for github pages
generate html docs for develop branch to republish github pages

#### Additional Information:
discussion leading up to this was in issue https://github.com/stan-dev/cmdstanpy/issues/225#issuecomment-696192382 - moving to its own issue

**Comment by ahartikainen** [comment]
For pypi we need the secret token which is then used together with `__token__` key. This token can be created in pypi.org and should be kept secret. It goes to github cmdstanpy settings --> secrects.

See twine section here: https://github.com/ahartikainen/pystan-jupyter/blob/main/.github/workflows/workflow.yml

**Comment by serban-nicusor-toptal** [comment]
Hey, I can setup a Jenkins job that would do all of that.

Can you please help me a bit @mitzimorris with what I need to run for:
`generate html docs for version and update docs dir contents for github pages`
`generate html docs for develop branch to republish github pages`

Also a pypi token so I can use it together with twine. Thanks!

**Comment by mitzimorris** [comment]
hi, just put credentials on GitHub following instructions here:  https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/  section "Saving Credentials on GitHub".  tokens for pypi and test_pypi - pypi account is CmdStanPy,  test_pypi account name is mmorris

> Can you please help me a bit @mitzimorris with what I need to run for:
> generate html docs for version and update docs dir contents for github pages
> generate html docs for develop branch to republish github pages

in the directory `docsrc` there's a makefile with target 'github' - this will generate html pages into dir `_build` and copy them over to top-level dir `docs`.
therefore what you need to do is this:

```
cd docsrc
make github
```
and then merge whatever branch that's been done on back into develop

@serban-nicusor-toptal - hope this makes sense

**Comment by serban-nicusor-toptal** [comment]
I've created a [PR](https://github.com/stan-dev/cmdstanpy/pull/297) to handle this, I need to wait a few hours for the Jenkins queue to finish so I can change the default linux image ( I've added cmdstanpy deps like sphinx, numpy ... ) then I will test it to ensure everything is ready for the merge.
Readthedocs do not have an API endpoint for the default version ( I didn't find one in their docs ) so I had to write this into a python script using requests and sessions, let me know if this is alright @mitzimorris please.  You can find this script in the PR mentioned above.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/297
