### ISSUE TITLE
test_multi_proc is too brittle

### ISSUE THREAD

**Issue by imadmali** [stan-dev/cmdstanpy#298]
@mitzimorris helped me identify ([here](https://github.com/stan-dev/cmdstanpy/pull/296#issuecomment-697145511)) that `test_multi_proc` is too brittle when running unit tests on a local machine.
https://github.com/stan-dev/cmdstanpy/blob/develop/test/test_sample.py#L229-L318

**Comment by ahartikainen** [comment]
Should it just create couple more chains than `os.cpu_count`?

**Comment by imadmali** [comment]
This is just a first pass so I may have missed something but...

If `os.cpu_count <= parallel_chains` then the test should pass since the calculation in the [source code](https://github.com/stan-dev/cmdstanpy/blob/develop/cmdstanpy/model.py#L639) matches the calculation in the [test](https://github.com/stan-dev/cmdstanpy/blob/develop/test/test_sample.py#L305).

But if `os.cpu_count > parallel_chains` then it will fail because of this [logic](https://github.com/stan-dev/cmdstanpy/blob/develop/cmdstanpy/model.py#L617) in the source code.

I think if this logic `max(min(cpu_count(), chains), 1)` is reflected in the test then it'll be more robust.
