### ISSUE TITLE
refactor code base - rename files, classes, methods

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#3]
#### Summary:
Change names to match functional spec - see https://github.com/stan-dev/design-docs/blob/master/designs/0002-cmdstanpy_func_spec.md

#### Description:
The CmdStanPy  is copied from base https://github.com/maedoc/pycmdstan, as it is very close to what we want in a lightweight wrapper.   As the first step of the refactor, rename directories, files, classes and methods according to the spec.

**Comment by maedoc** [comment]
Do you want to push this to the Python package repos? Or will this be packaged with CmdStan itself?

**Comment by seantalts** [comment]
I think it seems best to have a PyPI package available.

**Comment by mitzimorris** [comment]
done vi PR #21
