### ISSUE TITLE
Provide sig_figs options to cmstanMCMC.summary

### ISSUE THREAD

**Issue by imadmali** [stan-dev/cmdstanpy#300]
The summary method executes cmstan's stansummary, and it would be good to pass `sig_figs` option to the summary method. This would make unit testing easier for developers building interfaces to cmstanpy since they can make sure their computations (e.g. their own summary output) line up with what cmdstan does.

https://github.com/stan-dev/cmdstanpy/blob/develop/cmdstanpy/stanfit.py#L616

**Comment by mitzimorris** [comment]
hi @imadmali,
I could implement this right now if you'd like

**Comment by imadmali** [comment]
Sorry been dealing with life things. Can you give me the day to push my branch?

**Comment by mitzimorris** [comment]
sure.

**Comment by imadmali** [comment]
@mitzimorris it looks like the summary method is writing the summary as a csv file and reading that back in. But in cmdstan, if you use the `--csv_filename` option in stansummary _and_ the `--sig_figs` option then the number of significant digits reported doesn't change. But if you use `--sig_figs` _without_ `--csv_filename` the number of significant digits reported will change (based on what the user requests). Is that behavior supposed to happen?

**Comment by mitzimorris** [comment]
> if you use the --csv_filename option in stansummary and the --sig_figs option then the number of significant digits reported doesn't change

are you running latest version of CmdStan develop branch?  sig-figs fix was merged yesterday.
I thought I saw a test for CSV files in that PR, so  if you call cmdstan/bin/stansummary and specify
`--sig_figs` and `--csv_filename`, the resulting csv file should have the information available.

wasn't the problem that CmdStanPy spits out the requested number of sig_figs, but CSV file was capped at 6?
else I'm not understanding your question.

**Comment by imadmali** [comment]
> are you running latest version of CmdStan develop branch?

Ooh. No I was using `cmdstan-2.24.0`. I tried running the develop branch version of cmdstan on my machine but couldn't because of this [issue](https://github.com/stan-dev/cmdstan/issues/933).

> wasn't the problem that CmdStanPy spits out the requested number of sig_figs, but CSV file was capped at 6?

Yep. Initially I thought that the stdout was being parsed to the user with the summary method... that's where my confusion came from.

**Comment by mitzimorris** [comment]
CmdStan develop is working again.

**Comment by mitzimorris** [comment]
on further investigation, CmdStan `stansummary` utility arg `sig_figs` only affects console output.  just changed by might be too late for 2.25 release.
