### ISSUE TITLE
Error with cmdstanpy.install

### ISSUE THREAD

**Issue by sfarHD14** [stan-dev/cmdstanpy#302]
#### Summary:
I am a new user to Stan.
I am trying to install cmdstanpy in an Anaconda environment but got an error.

#### Description:
Here are the steps I went through:
1. Setup a new env using Anaconda GUI
2. Opened up a terminal interface via that env
3. Ran the command from the docs to install cmdstanpy: `pip install --upgrade cmdstanpy`
4. Ran the command to install cmdstan
```
import cmdstanpy
cmdstanpy.install_cmdstan()
```
and received the following error:
```
INFO:cmdstanpy:Cannot connect to github.
INFO:cmdstanpy:HTTP Error 403: rate limit exceeded
INFO:cmdstanpy:retry (1/5)
INFO:cmdstanpy:Cannot connect to github.
INFO:cmdstanpy:HTTP Error 403: rate limit exceeded
INFO:cmdstanpy:retry (2/5)
INFO:cmdstanpy:Cannot connect to github.
INFO:cmdstanpy:HTTP Error 403: rate limit exceeded
INFO:cmdstanpy:retry (3/5)
INFO:cmdstanpy:Cannot connect to github.
INFO:cmdstanpy:HTTP Error 403: rate limit exceeded
INFO:cmdstanpy:retry (4/5)
INFO:cmdstanpy:Cannot connect to github.
INFO:cmdstanpy:HTTP Error 403: rate limit exceeded
INFO:cmdstanpy:retry (5/5)
INFO:cmdstanpy:Cannot connect to github.
INFO:cmdstanpy:HTTP Error 403: rate limit exceeded
WARNING:cmdstanpy:CmdStan installation failed
False
```

#### Current Version:
OS: Windows 10 Enterprise. Version: 1809
Python: 3.7.9

**Comment by imadmali** [comment]
JFYI, @sfarHD14 also tried installing from the terminal using the command provided in the doc (which is effectively the same thing, but we thought might as well give it a try).
```
python -m cmdstanpy.install_cmdstan
```

**Comment by mitzimorris** [comment]
checked out "403" and "Windows 10" - it might be a policy issue on your side - https://docs.microsoft.com/en-us/troubleshoot/azure/general/request-throttling-http-403#troubleshooting-steps

**Comment by imadmali** [comment]
Update

> checked out "403" and "Windows 10" - it might be a policy issue on your side - https://docs.microsoft.com/en-us/troubleshoot/azure/general/request-throttling-http-403#troubleshooting-steps

@mitzimorris good point. We tried installing again, this time with the VPN turned off, and ran into a different issue.

```
>>> import cmdstanpy
>>> cmdstanpy.install_cmdstan()
INFO:cmdstanpy:CmdStan version: 2.24.1
INFO:cmdstanpy:Install directory: C:\Users\ogalvisbalba\.cmdstanpy
INFO:cmdstanpy:Building cmdstan-2.24.1 binaries
INFO:cmdstanpy:Command "make build" failed
INFO:cmdstanpy:'cut' is not recognized as an internal or external command,
INFO:cmdstanpy:operable program or batch file.
INFO:cmdstanpy:'cut' is not recognized as an internal or external command,
INFO:cmdstanpy:operable program or batch file.
INFO:cmdstanpy:process_begin: CreateProcess(NULL, cp bin/windows-stanc bin/stanc.exe, ...) failed.
INFO:cmdstanpy:make (e=2): The system cannot find the file specified.
INFO:cmdstanpy:mingw32-make: *** [bin/stanc.exe] Error 2
WARNING:cmdstanpy:CmdStan installation failed
False
```

**Comment by mitzimorris** [comment]
This seems to be a problem with the Makefile calling unix command line utility `cut` - the solution is here:
https://discourse.mc-stan.org/t/errors-when-using-cmdstan-model/14984/21

> Try adding C:\RBuildTools\3.5\mingw_64\bin to PATH and restart RStudio.

@ahartikainen - does `install_cxx_toolchain.py` script do this automatically?

**Comment by mitzimorris** [comment]
we really need to document the `cut` problem *everywhere* - or make the Makefile smarter

**Comment by imadmali** [comment]
> Try adding C:\RBuildTools\3.5\mingw_64\bin to PATH and restart RStudio.

Oh interesting. Does this mean that a windows cmdstanpy user need to have R/RStudio/Rtools installed too? Or is simply adding that to PATH sufficient.

**Comment by mitzimorris** [comment]
> Oh interesting. Does this mean that a windows cmdstanpy user need to have R/RStudio/Rtools installed too? Or is simply adding that to PATH sufficient

I think it's just a matter of having mingw_64 installed - but it seems that the easiest way to get windows C++ toolchain is via Rtools - hence implementation of `install_cxx_toolchain.py` from @ahartikainen 

(_editorial - rant on_: we *really really* need to get a robust install solution here - this is a huge drain on the devs time - and we have no idea how many potential users  we're losing.  _rant off_)

**Comment by ahartikainen** [comment]
I have not found cut tool in conda, so we can not use conda-only solution.

I use tools with cmdstanpy

    python -m cmdstanpy.install_cxx_toolchain
    python -m cmdstanpy.install_cmdstan

And in python

    import cmdstanpy
    cmdstanpy.utils.cxx_toolchain_path()

**Comment by mitzimorris** [comment]
regarding `cut` - looks like October CmdStan release will have this fixed - 

discussion here:  https://discourse.mc-stan.org/t/errors-when-using-cmdstan-model/14984/24
PR here: https://github.com/stan-dev/math/pull/2126

**Comment by mitzimorris** [comment]
added note to docs, closing

**Comment by imadmali** [comment]
Has this been resolved with the latest cmdstan [release](https://github.com/stan-dev/cmdstan/releases/tag/v2.25.0)?

**Comment by mitzimorris** [comment]
given the PR, yes.  we don't have much in place to test these kinds of things.
