### ISSUE TITLE
Update docs for stan_variable() return type

### ISSUE THREAD

**Issue by mathDR** [stan-dev/cmdstanpy#304]
Current README states that stan_variable returns a numpy ndarray, but the code returns a pandas DataFrame.

**Comment by ahartikainen** [comment]
Yeah, we need to update README.

**Comment by mitzimorris** [comment]
where exactly does this say this on the README?

**Comment by mathDR** [comment]
Yes sorry:  https://cmdstanpy.readthedocs.io/en/latest/hello_world.html?highlight=stan_variable#access-the-sample

**Comment by mitzimorris** [comment]
good catch!  will most definitely fix

note: branch https://github.com/stan-dev/cmdstanpy/tree/feature/222-doc-fixes is the running set of doc fixes

**Comment by mitzimorris** [comment]
now correct, cf: https://cmdstanpy.readthedocs.io/en/v0.9.68/hello_world.html#access-the-sample
also corrected tutorial notebook - cmdstanpy_tutorial.ipynb
