### ISSUE TITLE
checkpointing with cmdstanpy

### ISSUE THREAD

**Issue by reznida** [stan-dev/cmdstanpy#305]
I am trying to implement checkpointing with cmdstanpy and I am unsure how to calculate the mass matrix from the csv output file in order to pass it as `metric` to next sampling cycles.
Is it possible? If so, can someone please point me to a tutorial or example?

Thank you!

**Comment by mitzimorris** [comment]
you don't need the csv file - the mass matrix is available from the CmdStanMCMC sample as per-chain property `metric`; you can pass it in to next cycle via argument `metric`.  you should also save `step-size` as well.

examples are in the CmdStan docs:  https://mc-stan.org/docs/2_24/cmdstan-guide/mcmc-config.html#examples

**Comment by reznida** [comment]
Thank you!!

**Comment by ahartikainen** [comment]
I could not get this working.

cc @mitzimorris 

```
import cmdstanpy
import numpy as np
import ujson as json
import arviz as az

model_code = """
data {
    int N;
    real y[N];
}
parameters {
    real alpha;
    real<lower=0> sigma;
}
model {
    alpha ~ normal(0,1);
    sigma ~ normal(0,1);
    y ~ normal(alpha, sigma);
}
"""

model_path = "./normal_model.stan"
with open(model_path, "w") as f:
    print(model_code, file=f)

model = cmdstanpy.CmdStanModel(stan_file=model_path)
stan_data = {
    "N": 10,
    "y": np.random.randn(10) * 3 + 2
}

seed = 100
fit = model.sample(data=stan_data, chains=4, seed=seed, iter_warmup=1000, iter_sampling=100)

idata = az.from_cmdstanpy(posterior=fit)

def get_inits(fit, checkpoint_name="init_checkpoint"):
    params_bool = [not item.endswith("__") for item in fit.column_names]
    params = [item for item in fit.column_names if not item.endswith("__")]
    names = []
    for i, init in enumerate([item[params_bool].tolist() for item in fit.draws()[-1]], 1):
        names.append(checkpoint_name + f"_chain_{i}" + ".json")
        with open(names[-1], "w") as f:
            json.dump(dict(zip(params, init)), f)
    return names

inits = get_inits(fit, checkpoint_name="init_checkpoint_round_0")

def get_stepsize(fit):
    return fit.stepsize.tolist()

stepsize = get_stepsize(fit)

def get_metric(fit, checkpoint_name="metric_checkpoint"):
    names = []
    for i, metric in enumerate([item.tolist() for item in fit.metric], 1):
        names.append(checkpoint_name + f"_chain_{i}" + ".json")
        with open(names[-1], "w") as f:
            json.dump({"inv_metric": metric}, f)
    return names

metric = get_metric(fit, checkpoint_name="metric_checkpoint_round_0")

seed += 4

new_fit = model.sample(
    data=stan_data,
    chains=4, 
    seed=seed, 
    inits=inits,
    step_size=stepsize,
    metric=metric,
    iter_warmup=0, 
    adapt_engaged=False, 
    iter_sampling=100
)

new_idata = az.from_cmdstanpy(posterior=new_fit)
idata = az.concat(idata, new_idata, dim="draw")
```

When we get this working, it is possible make this in loop.

**Comment by ahartikainen** [comment]
This didn't work even when data was in `.json` or a list of json files.

Also, notice you need current master for arviz

    pip install git+https://github.com/arviz-devs/arviz

**Comment by ahartikainen** [comment]
I could get it working for one chain and doing a lot of manual work. So I think there is a small bug how input data is handled in different cases.

**Comment by mitzimorris** [comment]
hi @ahartikainen, will investigate the above code. 

@reznida - what exactly do you mean by "checkpointing" and what is your use case?

**Comment by reznida** [comment]
@mitzimorris  -  my model takes many days to sample (with `reduce_sum` already implemented) and the wall time limit on the computing cluster that I use is 24 hours. So I must do the sampling in chunks with a job array, meaning every new sampling chunk must continue from the place where the previous one has stoped. I hope this is clear.

**Comment by mitzimorris** [comment]
checkpointing and restarting the sampler has been much discussed - 
critical question:  does warmup take more than 24 hours?

some discussion here:  https://discourse.mc-stan.org/t/current-state-of-checkpointing-in-stan/12348

(background reading on metric and stepsize here:  https://mc-stan.org/docs/2_24/reference-manual/hmc-algorithm-parameters.html)

if you're post-warmup, then you need to get stepsize, metric, and determine initial parameter values - which would be per-chain last draw just the parameter values.  I think all of this is doable directly in CmdStanPy - will try to put together a notebook and get this into the docs.

**Comment by ahartikainen** [comment]
@mitzimorris I have also some idea how to handle warmup, but it still needs some testing.

Were you able to test that adhoc code?

**Comment by mitzimorris** [comment]
@ahartikainen  - not yet - buried under other stuff ATM.

**Comment by reznida** [comment]
First of all, thank you both so much!
The warmup depends on the number of iterations - I can complete 500 iterations in 23 hours (with tree depth of 10 and adapt_delta of 0.9). I was thinking to get the warmup from one chain, and then running multiple chains with these parameters in 500 iteration chunks. If it would be possible to do checkpointing on warmup as well, this would be ideal!

**Comment by mitzimorris** [comment]
how long do sampling iterations take vs. warmup?
you need to test whether or not adaptation has reached the typical set.  

you could try running a single chain for N warmup iterations (as many as you think will run in under 24 hrs), and 1 sampling iteration, then using stepsize, metric, and that single draw as init values and then run 4 chains - with several hundred sampling iterations - and check diagnostics to see whether or not chains are mixing.

(assuming that you've thoroughly debugged your model and that there's a good reason why each iteration takes as long as it does)

**Comment by reznida** [comment]
This is exactly what I am trying to do right now. I am trying to implement initiation of multiple chains using external warmup parameters. But would having only several hundreds iterations per chain suffice? I hoped to run at least 2 chains with 1000 iterations each
I am fitting a pretty large model with more than 25k latent parameters and about 2 million observations, so I hope this is why the model samples so slowly and not because something is terribly wrong with it :)

**Comment by mitzimorris** [comment]
> I am trying to implement initiation of multiple chains using external warmup parameters

the problem is that during warmup you get the parameter and stepsize for each draw, but not the metric (a.k.a. inverse metric a.k.a. mass matrix).

you can do a short warmup, then use that to run a few chains post-warmup and check diagnostics, because once adaptation has terminated, the sampler reports the metric.

> I am fitting a pretty large model with more than 25k latent parameters and about 2 million observations

it's possible this is just too big for Stan to do in the allotted amount of time.  can you use INLA to do this?

overall, I'm not sure this is a CmdStanPy issue - it's a fundamental Stan issue - cf Forums discussion linked to above - I suggest that you ask more questions in that thread, because you'll get eyeballs from folks who might be able to help.

**Comment by reznida** [comment]
Yes, thank you so much! I don't really know INLA, but I found that if I reduce max_treedepth back to 10, sampling time reduces only to 72 hours. So this is great news. 
Is this generally fine to sample multiple chains using the same warmup? Also, how bad is it if I have only one chain (with 1000 samples)?
