### ISSUE TITLE
fit.num_draws not handled correctly

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#308]
#### Summary:

`fit = model.sample(save_warmup=True)`
`fit.draws_pd()`

```
...\cmdstanpy\cmdstanpy\stanfit.py in draws_pd(self, params, inc_warmup)
    714                 (self.num_draws * self.runset.chains),
    715                 len(self.column_names),
--> 716                 order='A',
    717             )
    718             self._draws_pd = pd.DataFrame(

ValueError: cannot reshape array of size 52000 into shape (8000,13)
```

Same error with `fit.stan_variables()`

#### Description:
There are some problems with `draws_pd` if `save_warmup` is `True` and `.draws_pd(inc_warmup=False)`.
Same problem is found when using `.stan_variables`

I think something is wrong with the handling of `self.num_draws` (it contains also warmup, even when it should not).

This works

`fit.draws_pd(inc_warmup=True)`

#### Current Version:

0.9.67/github master

**Comment by mitzimorris** [comment]
good catch.  will take a look at this logic now.

**Comment by mitzimorris** [comment]
> There are some problems with draws_pd if save_warmup is True and .draws_pd(inc_warmup=False).
> Same problem is found when using .stan_variables
> 
> I think something is wrong with the handling of self.num_draws (it contains also warmup, even when it should not).

I think you're correct here - adding logic and unit tests.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/311
