### ISSUE TITLE
draws_pd needs warmup column

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#309]
#### Summary:

We need a column with True/False for warmup information.

#### Description:

if `inc_warmup` is called, there is no indication which rows are warmup (non-valid mcmc draws) and which are not (valid mcmc draws)

#### Current Version:

GH master

**Comment by mitzimorris** [comment]
the default behavoir is to not save warmup draws, if saved, the default behavoir is to not include warmup.
therefore, if the user has requested warmup, there's a reason they want to use the warmup draws; marking things valid or invalid shouldn't be necesary.

that said, we could expose fields `_draws_warmup` and `_draws_sampling` as properties - would this be useful?

**Comment by ahartikainen** [comment]
That could be a start.

I'm just thinking of that DataFrame we output. That could have one extra column to show warmup rows and non-warmup rows.

**Comment by mitzimorris** [comment]
added properties `num_draws_warmup` and `num_draws_sampling` in addition to property `num_draws`.

**Comment by mitzimorris** [comment]
OK, just submitted PR for this one - pls review, at your leisure.

**Comment by mitzimorris** [comment]
closing this; num_draws_warmup and num_draws_sampling have been added.
