### ISSUE TITLE
Posix style path to make command

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#31]
#### Summary:
Calling CmdStan make needs posix style paths for it's argument.

To fix this, for all command calling `make` do:

    path.replace("\\", "/")

**Comment by mitzimorris** [comment]
should we be using `pathlib` ? 
https://realpython.com/python-pathlib/

**Comment by ahartikainen** [comment]
That is one option

**Comment by mitzimorris** [comment]
@ahartikainen - in a PR you said that  cmdstan only works with posix paths

is this still a problem for CmdStan 2.19? 
the makefiles for StanMath, Stan, and CmdStan were overhauled either in 2.18 or 2.19.

I'm looking at the changes in https://github.com/stan-dev/cmdstanpy/pull/32 - it seems like if this is a make problem, then there's only one place where it's necessary to have a posix path, and that would be in setting up the `make` command in `compile_model`.

another thing overlooked are the names of the CmdStan executibles - is it necessary to add a `.exe` suffix to the CmdStan binary names, e.g. `bin\stanc.exe`, `bin\summary.exe`, etc?

**Comment by ahartikainen** [comment]
I can tests these.

**Comment by mitzimorris** [comment]
see https://github.com/stan-dev/cmdstanpy/pull/39 - using Posix path for `make` command.

**Comment by mitzimorris** [comment]
fixed by https://github.com/stan-dev/cmdstanpy/pull/39
