### ISSUE TITLE
int variables are float

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#310]
#### Summary:

`int` parameters should be integer in pandas.DataFrame.

#### Description:
Currently pandas.DataFrame from `.draws_pd` are float, but there should a be way to transform them to int.

#### Additional Information:

I think there is a way to extract this information from Stanc3

#### Current Version:

GH/master

**Comment by mitzimorris** [comment]
Stan doesn't allow int parameters -

**Comment by ahartikainen** [comment]
I'm being liberal with the name parameter.

```
generated quantities {
    int x
...
```

**Comment by mitzimorris** [comment]
if the user knows that a variable declared in generated quantities block was declared as an int, we could add `as_int` flag to method `stan_variable`, e.g. `x_pd = fit.stan_variable(name='x', as_int=True)` ??

problem is, Stan CSV file doesn't have program variable type information.
the CSV headers are just column names - you have to stand on your head to figure out which columns are parameter values (hint:  do yoga.  then this: https://github.com/stan-dev/stan/blob/8270217be01003eb1174f4457aff20689540de66/src/stan/services/sample/standalone_gqs.hpp#L21-L51)

note that we're using a single ndarray to store the entire drawset - if we want to respect variable type, we'd need to peel off generated quantities variables and have a separate data structure for them, on a per-variable basis.  which might make sense - with better program i/o, maybe, which would require a big refactor, starting with generated c++ model code `write_array` method.

**Comment by ahartikainen** [comment]
I'm fine with keeping it float in the inner datastructure (ndarray).

column name yoga is not a problem.

Even accessing .stan file is not enough nowadays (`#include`), but maybe Stanc3 could give us the parameters (real or int), or Stanc3 could give the normalized model code (does it unpack includes). Extracting int from model code is possible.

**Comment by mitzimorris** [comment]
> Even accessing .stan file is not enough nowadays (#include), but maybe Stanc3 could give us the parameters (real or int), or Stanc3 could give the normalized model code (does it unpack includes). Extracting int from model code is possible.

it's not about column name yoga - that's trivial.  it's that the column name doesn't encode variable type, and only generated quantities variables can be type int - the information isn't in the csv file.  it could be gotten from the program source code, if available, but that would require some kind of interaction with the Stanc3 parser.

sorry - I'm a minimalist - if the user wants to do something with an int variable, we give them a hook to get it as an int.

**Comment by ahartikainen** [comment]
True.

Could model class contain this information?

**Comment by mitzimorris** [comment]
no.  checking code now - it has functions with 3-way switch -  the function looks like this:

```
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
```

call with bool args F,F, you get just the parameter block variables,  that plus combos T,F and T,T (or F,T) will let you figure out the declaring block.  that's it.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/stanc3/issues/808

closing this issue - when Stanc3 compiler has metadata and it's threaded through CmdStan, we can revisit.

**Comment by mitzimorris** [comment]
does numpy provide a way of converting an ndarray of type float to an ndarray of type int?  if so, we should document how to do this - if it's more than just a one liner, we could provide a convenience function for users.

**Comment by ahartikainen** [comment]
`arr = arr.astype(int)`

**Comment by mitzimorris** [comment]
thanks -  will use this in an extended example somehow.
