### ISSUE TITLE
generate quantities production workflow:  instantiate sample from drawset, not csv files

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#318]
#### Summary:
in a production environment, it should be possible to run generate quantities from the set of draws for all model parameters instead of relying on on-disk CSV files.

#### Description:
Use case and discussion on Discourse:  https://discourse.mc-stan.org/t/cmdstanpy-prediction-workflow-and-generated-quantitites/18305/4

A clean way to do this would be methods on CmdStanMCMC object:
 - `save_param_draws`
 - `save_fit_data`

#### Additional Information:
Provide any additional information here.

**Comment by ahartikainen** [comment]
Is there a way to extract needed parameters or does it work if there are variables from generated quantities?

**Comment by mitzimorris** [comment]
it should work given entire drawset

**Comment by mitzimorris** [comment]
Here's a quick refresher (for me, mainly) on running the genenerated quantities block using a set of draws.

What makes this challenging is that the model and generated quantities block computations work with the *unconstrained* parameters values but the fitted parameter values are reported the *constrained* scale - i.e., in terms of the model.

Because initial parameter values are specified on the *constrained* scale, the generated C++ code for a Stan program has function`transform_inits` which does the necessary constrained -> unconstrained transform.

The computations defined in the model's `generated quantities` block are transpiled to statements in the generated C++ code's `write_array` function.  This function takes the unconstrained parameters and applies the inverse transform back to the constrained scale.

Putting the above together, the `generate_quantities` method:

- instantiates the model
- (does a bunch of checking of the model against the supplied CSV drawset)
- calls method `transform_inits` on each draw to get the unconstrained param values
- feeds those values to the `write_array` function
- spits out the values for  *only* the generated quantities block variables on the unconstrained scale

Running the `generate_quantities` method requires:

- the model (Stan code or exe)
- any input data required to instantiate the model
- a set of draws (on the constrained scale, which is how they're reported) in CSV format.

In addition to shipping draws from fitted model to production environment, you need to ship model and inputs as well.  Furthermore, you need to first instantiate a CmdStanModel object from the model (src or exe), then call the `generate_quantities` object.

But as far as the `generate_quantities` method is concerned, it requires a CSV file of inputs.  the question is how simple can this CSV file be and can it be generated on the fly by the CmdStanPy `generate_quantities` method is the input is just a numpy ndarray?

**Comment by mitzimorris** [comment]
what would work is a workflow where fit from CmdStanMCMC object  is saved via `draws_pd` method (no warmup draws).
supplying draws_pd to `generate_quantities` method would suffice; we can write it out to `_TMPDIR` as a minimal csv file.

**Comment by mitzimorris** [comment]
testing - this will work once https://github.com/stan-dev/stan/pull/2969 goes in

**Comment by mitzimorris** [comment]
@imadmali - adding functionality via branch feature/318-save-fitted-params:

- CmdStanMCMC object has method `save_fitted_params` - produces a minimal CSV file that flattens all chains and saves just the parameter columns out of the drawset as CSV file which has header row of column names, data rows are parameter values for all samping iterations across all chains.

- Model method `generate_quantities` accepts either list of Stan CSV files as input or single CSV file; single CSV file can be either Stan CSV file w/ full sample or simple CSV file which just has fitted params values.

**Comment by mitzimorris** [comment]
will be fixed by PR https://github.com/stan-dev/cmdstanpy/pull/413
