### ISSUE TITLE
Error when calling methods stan_variable or stan_variables sampling with save_warmup = True 

### ISSUE THREAD

**Issue by jmaronas** [stan-dev/cmdstanpy#322]
#### Summary:
There is a problem when using `cmdstanpy.CmdStanMCMC.stan_variable` or `cmdstanpy.CmdStanMCMC.stan_variables` and samples have been obtained by setting save_warmup = True `sm.sample(data=gauss_dat,  iter_sampling=1000,  chains=1,  iter_warmup = 200, seed = 1, save_warmup = True)` 

#### Description:
The method raised the following error: `ValueError: cannot reshape array of size 2000 into shape (1200,2)`. If `save_warmup = False` then it works

#### Additional details. 
Code for reproduce:

```
from cmdstanpy import CmdStanModel
sm = CmdStanModel(stan_file='./stan_files/init_stan_infer_mean_gaussian.stan')
gauss_dat = {             
            }
fit_sampler    = sm.sample(data=gauss_dat,  iter_sampling=1000,  chains=1,  iter_warmup = 200, seed = 1, save_warmup = True)

print('=== Stan variable infered shape, in this case the mean: ',fit_sampler.stan_variable(name = 'mu').shape) 
print('=== Dict keys of all Stan variables infered: ', fit_sampler.stan_variables().keys())
```

#### Current Version:

0.9.67

**Comment by mitzimorris** [comment]
thanks for the detailed report - will investigate

**Comment by ahartikainen** [comment]
Is this still a problem with develop branch?

**Comment by mitzimorris** [comment]
yes - not sure what's going on.

**Comment by chaimolina** [comment]
Hi folks! New here... I was thinking I'd try and fix this, but when I forked from `stan-dev:develop`, this already seems fixed to me. 

I didn't find the `init_stan_infer_mean_gaussian.stan` file used in jmaronas's example, so here's what I used to test it out (based on the tutorial Jupyter notebook):
```
import os
import os.path
from cmdstanpy.model import CmdStanModel
from cmdstanpy.stanfit import CmdStanMCMC
from cmdstanpy.utils import cmdstan_path

bernoulli_dir = os.path.join(cmdstan_path(), 'examples', 'bernoulli')
bernoulli_path = os.path.join(bernoulli_dir, 'bernoulli.stan')
bernoulli_model = CmdStanModel(stan_file=bernoulli_path)

bern_json = os.path.join(bernoulli_dir, 'bernoulli.data.json')
bern_data = { "N" : 10, "y" : [0,1,0,0,0,0,0,0,0,1] }

bern_fit = bernoulli_model.sample(data=bern_data, save_warmup=True)
print(bern_fit.runset)
```

The csvs generated by this contain 1000 warmup draws and 1000 post-warmup draws (not attached since csv is not supported here... I could rename as txt and upload if needed). 

If I'm missing something and there's work to do here, I'd be very happy to try and help out!

**Comment by mitzimorris** [comment]
not a problem on current develop, ran:

```
import os
from cmdstanpy.utils import cmdstan_path, set_cmdstan_path
from cmdstanpy.model import CmdStanModel

cmdstan_path()
# set_cmdstan_path(os.path.expanduser(os.path.join('~', 'github', 'stan-dev', 'cmdstan')))

bernoulli_path = os.path.join(cmdstan_path(), 'examples', 'bernoulli', 'bernoulli.stan')
bernoulli_model = CmdStanModel(stan_file=bernoulli_path)
bern_data = { "N" : 10, "y" : [0,1,0,0,0,0,0,0,0,1] }

bern_fit = bernoulli_model.sample(data=bern_data, save_warmup=True, iter_warmup=200)
```

call to:  `bern_fit.stan_variable('theta').shape` returns (4000, 1) - all post-warmup draws for variable `theta`

call to:  `bern_fit.draws(inc_warmup=True).shape` returns (1200, 4, 8).  - all draws from all chains for sampler params and
variables in the stan model (`theta`).

**Comment by mitzimorris** [comment]
hi @chaimolina - we're always glad to have more contributors.  are you new to using Stan?
new eyes are very valuable in terms of helping with documentation and tutorials.

how much Python and other kinds of programming have you done?

**Comment by chaimolina** [comment]
@mitzimorris, I'm a relative stan-newbie, but using it quite a bit, interfacing both through R and Python (and use the latter two daily). I wouldn't say I'm a programming wizard by any means (and I do not know C++ at all), but I probably know enough to be useful :-) 

Documentation/tutorials would probably be a good place for me to start (e.g., the cmdstanpy tutorial Jupyter notebook does not run error-free out of the box, but other suggestions welcome). I'll follow up under [issue 65](https://github.com/stan-dev/cmdstanpy/issues/65) after I've played around with the cmdstanpy tutorial a bit more (and hopefully fixed a thing or two).

**Comment by ahartikainen** [comment]
Feel free to attack any issues you want. If not certain what to do we can discuss the best approach in the issue (or stan slack).
