### ISSUE TITLE
Test sig_figs argument

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#330]
To test sig_figs, we need to parse csv as a str and check the results.

**Comment by mitzimorris** [comment]
we don't need to test exact values - we trust that the system software that does str to float conversion works -
as long as that value is approximately correct and that the string is the corect length, all's good.

**Comment by mitzimorris** [comment]
hi @ahartikainen - can we close this?

**Comment by mitzimorris** [comment]
closing - checks we have are adequate.
