### ISSUE TITLE
pin numpy to avoid error on import

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#332]
#### Summary:

there's a problem with Numpy 1.19.4 (currently the latest) - https://github.com/numpy/numpy/issues/17726
```
RuntimeError: The current Numpy installation fails to pass a sanity check due to a bug
```

current setup requirements are:  `numpy>=1.15` add `>1.19.4` as well?

#### Additional Information:

I've hit this on mac and windows recently.

**Comment by ahartikainen** [comment]
`numpy>=1.15,!=1.19.4`

**Comment by mitzimorris** [comment]
fixed on develop.
