### ISSUE TITLE
Travis CI script to build CmdStan is failing

### ISSUE THREAD

**Issue by maedoc** [stan-dev/cmdstanpy#34]
#### Summary:
Travis CI script to build CmdStan is failing

#### Description:
The CI script to build CmdStan seems [to be failing](https://travis-ci.org/stan-dev/cmdstanpy/builds/533765215#L230):
```
$ ./make_cmdstan.sh
~/build/stan-dev/cmdstanpy/releases ~/build/stan-dev/cmdstanpy
release dir: /home/travis/build/stan-dev/cmdstanpy/releases
latest cmdstan: 
download rc code: 0
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
tar rc 2
./make_cmdstan.sh: line 40: cd: cmdstan: No such file or directory
make: *** No rule to make target 'build'.  Stop.
installed cmdstan-
ls: cannot access 'releases/*': No such file or directory
```

#### Additional Information:
Affecting PR #32 

#### Current Version:

**Comment by maedoc** [comment]
Btw, I don't get [why the `make_cmdstan.sh`](https://github.com/stan-dev/cmdstanpy/blob/master/make_cmdstan.sh#L18) is always getting the latest tag.  It'd be better to use a build matrix if it's really expected to support N-1 to N versions.

**Comment by mitzimorris** [comment]
build failing is some problem w/ Travis and or the AWS container it's running in.

agreed that `make_cmdstan.sh` need work.
how about adding 2 arguments: 
  * `$1` -  install location - defaults to ~/.cmdstanpy/releases
  * `$2` - version - defaults to latest version

**Comment by mitzimorris** [comment]
Travis running OK - problems seem to be external - closing for now.
