### ISSUE TITLE
summary function - should call CmdStan using arg `csv_filename` not `csv_file`

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#340]
#### Summary:

Call to the utility `bin/stansummary` use argument `csv_file` but it should be `csv_filename`; this now breaks in for CmdStan 2.26.

#### Description:

CmdStan utility bin/stansummary has option:

```
  -c, --csv_filename [file]   Write statistics to a csv file.
```

CmdStan 2.24-2.25 used command line arg parsing library boost::program_options, which allows "chopped words" - https://stackoverflow.com/questions/10188973/why-is-boostprogram-options-accepting-chopped-words

CmdStan 2.26 uses command line arg parsing library cli11 which doesn't allow this; therefore change the call here:
https://github.com/stan-dev/cmdstanpy/blob/66f22fe791cdc4441b59275600512e3148f843a9/cmdstanpy/stanfit.py#L711

#### Additional Information:
Provide any additional information here.

**Comment by bbbales2** [comment]
Fixed in #341
