### ISSUE TITLE
allow user to create CmdStanMCMC et al from output csv files

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#345]
#### Summary:

If a user wants to work with a saved sample, it should be possible instantiate a fitted model object
from CSV files and user inputs.

#### Description:

We're doing this in both standalone generated quantities and in unit tests -

https://github.com/stan-dev/cmdstanpy/blob/68be06ed75d7d85b3ce22b11352b34e5d621cbdf/cmdstanpy/model.py#L853

Example from unit test:
```
       # construct fit using existing sampler output
        exe = os.path.join(DATAFILES_PATH, 'logistic' + EXTENSION)
        rdata = os.path.join(DATAFILES_PATH, 'logistic.data.R')
        sampler_args = SamplerArgs(iter_sampling=100)
        cmdstan_args = CmdStanArgs(
            model_name='logistic',
            model_exe=exe,
            chain_ids=[1, 2, 3, 4],
            seed=12345,
            data=rdata,
            output_dir=DATAFILES_PATH,
            sig_figs=17,
            method_args=sampler_args,
        )
        runset = RunSet(args=cmdstan_args)
        runset._csv_files = [
            os.path.join(DATAFILES_PATH, 'logistic_output_1.csv'),
            os.path.join(DATAFILES_PATH, 'logistic_output_2.csv'),
            os.path.join(DATAFILES_PATH, 'logistic_output_3.csv'),
            os.path.join(DATAFILES_PATH, 'logistic_output_4.csv'),
        ]
        retcodes = runset._retcodes
        for i in range(len(retcodes)):
            runset._set_retcode(i, 0)
        fit = CmdStanMCMC(runset)
```

In order to make this a user-facing utility, we need to determine
the minimum number of piece of information user needs to supply
in addition to list of Stan CSV files from a run, plus method.

#### Additional Information:
Provide any additional information here.

**Comment by mitzimorris** [comment]
the CmdStanMCMC et al objects don't provide much functionality other than `summary` and `stan_variables`, given this, what are the compelling use cases?

**Comment by ahartikainen** [comment]
This code needs better settings handling.
(from https://github.com/arviz-devs/arviz/blob/main/arviz/tests/external_tests/test_data_cmdstanpy.py )
```
from cmdstanpy import CmdStanMCMC
from cmdstanpy.stanfit import RunSet
from cmdstanpy.model import CmdStanArgs, SamplerArgs

args = CmdStanArgs(
                "dummy.stan",
                "dummy.exe",
                list(range(1, 5)),
                method_args=SamplerArgs(iter_sampling=100),
            )
            runset_obj = RunSet(args)
            runset_obj._csv_files = paths
            obj = CmdStanMCMC(runset_obj)
            obj.validate_csv_files()
            obj._assemble_draws()
```

**Comment by mortonjt** [comment]
If there needs to be compelling use cases, we do have a couple of scenarios we are weighing, namely

1. Handling data that may be sensitive - the data may not be possible to ship, but it could be possible to ship the CmdStanMCMC object (i.e. a hacky way to enable federated learning)
2. Obtain the out-of-distribution statistics to evaluate how much of the variability in the held-out data can be explained by the fitted CmdStanMCMC object

**Comment by mitzimorris** [comment]
agreed - there are many compelling use cases  will try to get this one done ASAP!

**Comment by mitzimorris** [comment]
proposal: a utility function which given a list of CSV files, returns a CmdStanMCMC object where the draws and meta-data are instantiated.
CmdStanR has utility - `read_cmdstan_csv` would go with this name;  include argument `files` but not other arguments which seem CmdStanR specific.
@mortonjt, @jgabry, @rok-cesnovar - opinions

**Comment by mortonjt** [comment]
A list of CSV files to instantiate a CmdStanMCMC may just do the trick - I like it better than pickling since versioning becomes less of an issue.  

If this becomes the standard for checkpointing / sharing, keeping track of the csvs may require additional bookkeeping.
A method that takes a gzipped file of csvs as input may be more approachable.  That being said, having instantiating CmdStanMCMC objects from csvs would be a stepping stone for such functionality.

**Comment by mitzimorris** [comment]
>  keeping track of the csvs may require additional bookkeeping.

please say more - what are the problems you're thinking of?

we've baked a certain amount of bookkeeping into the CSV file names - from the docs:

> Output files are either written to a temporary directory or to the specified output directory. Output filenames correspond to the template ‘<model_name>-\<YYYYMMDDHHMM\>-<chain_id>’ plus the file suffix which is either ‘.csv’ for the CmdStan output or ‘.txt’ for the console messages, e.g. ‘bernoulli-201912081451-1.csv’. Output files written to the temporary directory contain an additional 8-character random string, e.g. ‘bernoulli-201912081451-1-5nm6as7u.csv’.

also, Stan CSV files now have information about the Stan version, which could be parsed from the CSV header comments and put into the metadata.

anything else?

**Comment by mortonjt** [comment]
Its less about whether it'll work, more about if we were to share csv files with collaborators.  It would add an extra layer of confusion if collaborators have to load multiple csv files to instantiate a model.

I think this is a problem for a later date, which should be easier to address once the proposed `read_cmdstan_csv` method is in place.

**Comment by mitzimorris** [comment]
understood - if we were to operate at the directory level, then you could zip up the directory of outputs - agreed - let's start with files and then get fancy.

**Comment by mortonjt** [comment]
Hi @mitzimorris , any luck with the serialization? We have another use case that may be able to take advantage of this with embarrassingly parallel workflows (see here: https://github.com/gibsramen/BIRDMAn/issues/51).

**Comment by mitzimorris** [comment]
thanks for the reminder - haven't had time for this yet, will try to make some, and soon.

**Comment by mortonjt** [comment]
:+1: thanks! If you have any pointers on where to start, we could take a look as well.

**Comment by mitzimorris** [comment]
@mortonjt - please take a look at https://github.com/stan-dev/cmdstanpy/pull/402 - adding utility function `from_csv` -
you supply directory of CSV files, optionally, specify method.  question:  would you want to do this with output from standalone generated quantities?
