### ISSUE TITLE
migrate package release from Jenkins to GitHub actions

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#350]
#### Summary:
current package release script is Jenkinsfile: https://github.com/stan-dev/cmdstanpy/blob/develop/Jenkinsfile
migrate this to GitHub actions.

#### Description:

similar to work done here: https://github.com/stan-dev/cmdstanpy/pull/329

https://docs.github.com/en/actions/learn-github-actions/migrating-from-jenkins-to-github-actions

#### Additional Information:
We need to release a new version of CmdStanPy ASAP.

**Comment by serban-nicusor-toptal** [comment]
On it
