### ISSUE TITLE
install_cmdstan verbose flag fails

### ISSUE THREAD

**Issue by gibsramen** [stan-dev/cmdstanpy#351]
#### Summary:
When trying to use the `install_cmdstan` function, passing `verbose=True` does not properly install `cmdstan`. Keeping `verbose=False` seems to install correctly.

#### Description:

The following command fails:

```python
cmdstanpy.install_cmdstan(verbose=True)
```

with the following error message:

```python
deleting tmpfiles dir: /var/folders/1c/vd4s85fn44q78l5vrmmwn06c0000gn/T/tmpwgd3etty
done

WARNING:cmdstanpy:CmdStan installation failed.
WARNING:cmdstanpy:usage: install_cmdstan.py [-h] [--version VERSION] [--dir DIR] [--overwrite] [--verbose] [--progress]
install_cmdstan.py: error: unrecognized arguments: TRUE

False
```

I have successfully installed and used `cmdstanpy` by keeping the default `verbose=False`.

#### Current Version:

`cmdstanpy=0.9.68`
`python=3.7.9`

**Comment by mitzimorris** [comment]
thanks, will investigate.  what OS?

**Comment by gibsramen** [comment]
Thanks - this was on macOS BigSur v11.1.
