### ISSUE TITLE
Errors from some CmdStanMCMC methods

### ISSUE THREAD

**Issue by cmgoold** [stan-dev/cmdstanpy#353]
#### Summary:
`cmdstanpy.CmdStanMCMC.summary()` and `cmdstanpy.CmdStanMCMC.draws_as_dataframe()` are returning errors. 

#### Description:
I have ran a simple linear model using `cmdstanpy` but calling the `summary()` and `draws_as_dataframe()` methods on the fitted object results in errors. From `summary()`, I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cmdstanpy/stanfit.py", line 658, in summary
    do_command(cmd, logger=self.runset._logger)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cmdstanpy/utils.py", line 778, in do_command
    raise RuntimeError(msg)
RuntimeError: ERROR
 The following argument was not expected: --csv_file=/var/folders/7w/865y75kn6739v3ynt32w9tsm0000gn/T/tmphy171jqh/stansummary-linear-model-4-chain-r0k7w41b
.csv

Run with --help for more information.
```

and from `draws_as_dataframe` I get a 'no attribute' error, but looking through the repo it seems this method has been removed anyway. 

However, `summary()` is still defined. 

#### Additional Information:
A reproducible example:

```
// linear-model.stan
data{
  int<lower=0> N;
  vector[N] y;
}

parameters{
  real mu;
  real<lower=0> sigma;
}

model{
  target += normal_lpdf(mu | 0, 1);
  target += normal_lpdf(sigma | 0, 1) - 1 * normal_lcdf(0 | 0, 1);
  target += normal_lpdf(y | mu, sigma);
}
```

```
# .py file
import cmdstanpy as cp
import numpy as np

model = cp.CmdStanModel(stan_file="linear-model.stan")

# simulate data
y = np.random.normal(size=100)

fit = model.sample(
    data={
        'N': 100, 'y': y
    }
)

fit.diagnose()
fit.summary()
```

#### Current Version:
`0.9.67`, on Mac OSX Catalina 10.15.7

**Comment by ahartikainen** [comment]
Summary error might be related to this

https://github.com/stan-dev/cmdstanpy/pull/341

What CmdStan version do you have?


For draws use `fit.draws()` or `fit.draws_pd()` depending what you want.

**Comment by cmgoold** [comment]
Ah yes, thanks. I should have searched harder. I'm using CmdStan 2.26.0
