### ISSUE TITLE
when subprocess throws error, try to get system message; make sure error code prints correctly

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#357]
#### Summary:
When a subprocess fails, the error code is an unsigned int (?) but is printed as a signed int - error codes > 127 become negative, e.g. '-11'.  add mode logic to get system error message for the error code and cast return code to prevent manglinag.

#### Description:
Describe the issue as clearly as possible.

#### Additional Information:
Provide any additional information here.

**Comment by mitzimorris** [comment]
still how to interpret return codes above 127.   e.g., running CmdStan via bash shell with segfault terminated by signal -6 is reported as return code 134  - 128 + 6 or ???
in any case, PR https://github.com/stan-dev/cmdstanpy/pull/358 will improve error reporting.

**Comment by mitzimorris** [comment]
maybe this is the answer to some problems: https://stackoverflow.com/a/13789263

**Comment by ahartikainen** [comment]
`np.uint8(np.int8(-6)) == 250` ?

**Comment by mitzimorris** [comment]
hi @ahartikainen - context?

https://docs.python.org/3/library/subprocess.html#subprocess.CompletedProcess.returncode
question:  on which architectures are posix threads used?  or never?

**Comment by ahartikainen** [comment]
Hah, nevermind. So `'-11'` -> `11` on posix systems?

**Comment by mitzimorris** [comment]
so it would seem.
