### ISSUE TITLE
CmdStan does not work with open MPI

### ISSUE THREAD

**Issue by jmaronas** [stan-dev/cmdstanpy#360]
#### Summary:
CmdStan does not work with open MPI c++ compiler feature

#### Description:
When compiling a stan program to compile and use open MPI, as:

```
cpp_options = {
                'STAN_MPI'           : True ,      
              }

sm = CmdStanModel(stan_file='./stan_files/BNN.stan', cpp_options = cpp_options )

```

The model fails to successfully compile the program (after installing open mpi)

#### Additional Information:
The solution was to add the following lines to the cmdstan/make/local file:

```
TBB_CXX_TYPE=gcc
CXX=mpicxx
```

So in order to allow cmdstanpy to compile using mpi, the class `CompilerOptions` in file `compiler_opts` should add those flags

##### IMPORTANT NOTE

With this modification, the mpi compilation is invoqued. However, the program fails to compile but I think that is on the cmdstan side, and not the cmdstanpy. Will figure that out and come back.

**Comment by jmaronas** [comment]
Okay, figured it out. The model was not being compiled because the `file.hpp` that stan generates needs to be overwritting. So the following things needs to be done so that `cmdstanpy` compiles using openMPI:

1) Need to check if `file.hpp` and if so, then this file needs to be replaced

2) The method `CompilerOptions` in the `compiler_opts.py` file needs to set the following variables in the main/local or equivalent flags in the compiler command line
```
TBB_CXX_TYPE=gcc
CXX=mpicxx
```

**Comment by mitzimorris** [comment]
previous issue and discussion here:  https://github.com/stan-dev/cmdstanpy/issues/274

**Comment by mitzimorris** [comment]
removing this from release 1.0.

given that CmdStan will soon have multichain sampling, is this feature still needed?

**Comment by WardBrian** [comment]
I'm going to close this issue. We now have `compile='force'` which solves problem 1 above, and I do not believe we should be setting make variables (in particular, there is more than one MPI C++ compiler, so we cannot do this in general).

I believe the correct thing to do in this case is 
```
cpp_options = {
                'STAN_MPI'           : True ,      
                'CXX': 'mpicxx',
                'TBB_CXX_TYPE': 'gcc'
              }

sm = CmdStanModel(stan_file='./stan_files/BNN.stan', cpp_options = cpp_options, compile='force')

**Comment by brentmorgan1987** [comment]
@WardBrian @mitzimorris 

the post on may 16, 2022, executes without error but it doesn't run my MPI nodes.  

i am able to get get my MPI nodes running with this command:

    subprocess.run([
        'mpirun', '-np', '20', '-f', '/node_config_file', model.exe_file,
        'sample', 'num_samples=1000', 'num_warmup=500',
        'data', 'file={}'.format(stan_data_file),
        'output', 'file=output.csv'
    ])
  
but when I do   
fit = cmdstanpy.from_csv('output.csv')

it says the output.csv is corrupted.  It seems like the output format from subprocess.run() and cmdstanpy is different.
