### ISSUE TITLE
`CmdStanMCMC`'s function `stan_variable` does not handle arrays of vectors correctly.

### ISSUE THREAD

**Issue by funko-unko** [stan-dev/cmdstanpy#361]
#### Summary:

Calling `stan_variable` to access data which in `stan` is represented as an array of vectors (i.e. `vector[no_states] predicted_states[no_timesteps];`) misshandles memory alignment. 

#### Description:

As above. The returned `numpy` array has the right shape, but the values are not in the right cells. As an example, if we have a `stan` variable

`vector[2] predicted_states[3];`

with values 

```
[
[a,b],
[c,d],
[e,f]
]
```
calling `stan_variable` returns
```
[
[a,c],
[e,b],
[d,f]
]

```

#### Additional Information:

MWE:

python
```
import cmdstanpy
import numpy as np

model = cmdstanpy.CmdStanModel(stan_file='mwe.stan')
ts = np.linspace(0,1,4)[1:]
u0 = [1e6,1e-6]
data = dict(
    no_states=len(u0),
    no_timesteps=len(ts),
    ts=ts,
)

sim = model.sample(
    data,
    fixed_param=True,
    inits=dict(initial_states=u0),
    iter_sampling=1
)
print(open(sim.runset.stdout_files[0]).read())
print(sim.stan_variable('true_states'))
```
Stan
```
functions {
  vector dydt(real t, vector y){
    return -y;
  }
}
data {
  int no_states;
  int no_timesteps;

  real ts[no_timesteps];
}
parameters {
  vector[no_states] initial_states;
}
generated quantities {
  vector[no_states] true_states[no_timesteps] = ode_rk45(
    dydt, initial_states, 0, ts
  );
  print(true_states);
}
```
Stan Output
```
Iteration: 1 / 1 [100%]  (Sampling)
[[716531,7.16531e-07],[513417,5.13417e-07],[367880,3.6788e-07]]


 Elapsed Time: 0 seconds (Warm-up)
               0 seconds (Sampling)
               0 seconds (Total)
```
Python Output
```
[[[7.16531e+05 5.13417e+05]
  [3.67880e+05 7.16531e-07]
  [5.13417e-07 3.67880e-07]]]
```
#### Current Version:
0.9.68

**Comment by funko-unko** [comment]
Actually, this only appears to happen if we take exactly one sample. With everything the same but `iter_sampling=2` we get:

Stan output
```
Iteration: 1 / 2 [ 50%]  (Sampling)
[[716531,7.16531e-07],[513417,5.13417e-07],[367880,3.6788e-07]]

Iteration: 2 / 2 [100%]  (Sampling)
[[716531,7.16531e-07],[513417,5.13417e-07],[367880,3.6788e-07]]
```
Python output
```
[[[7.16531e+05 7.16531e-07]
  [5.13417e+05 5.13417e-07]
  [3.67880e+05 3.67880e-07]]

 [[7.16531e+05 7.16531e-07]
  [5.13417e+05 5.13417e-07]
  [3.67880e+05 3.67880e-07]]]
```

which is correct.

**Comment by ahartikainen** [comment]
np.reshape(..., order="A") does something wrong. I think we could go with "F" always.

**Comment by funko-unko** [comment]
Maybe, I don't know. However, Stan has different orders for arrays and matrices, doesn't it? Not sure whether this affects the output or `numpy`s handling.

**Comment by ahartikainen** [comment]
This is numpy problem. I think when there is only 1 draw and 1 chain and "A" used in reshape the inner order can be C or F and they would look similar --> numpy translates it to C. Maybe that is a bug in numpy handling. But adding explicit F to reshape fixes this issue.

**Comment by mitzimorris** [comment]
excellent catch!  agreed that for samples, order should explicitly be 'F' everywhere, and we need unit tests for these kinds of edge cases.

**Comment by mitzimorris** [comment]
> Stan has different orders for arrays and matrices, doesn't it?

no it doesn't.  this is about the order in which elements of a multi-dimensional variable are reported (model's `write_array` function, sent to Stan CSV output file):

```
generated quantities {
  array[2, 3] real gq_2d_arr;
  for (i in 1:2) {
    for (j in 1:3) {
      gq_2d_arr[i,j] = i*10 + j;
    }
  }
  matrix[4, 5] gq_matrix;
  for (i in 1:4) {
    for (j in 1:5) {
      gq_matrix[i,j] = i*10 + j;
    }
  }
}
```

resulting outputs:

```
gq_2d_arr ******************* elements of gq_matrix
11,21,12,22,13,23, ***** 11,21,31,41,12,22,32,42,13,23,33,43,14,24,34,44,15,25,35,45
11,21,12,22,13,23, ***** 11,21,31,41,12,22,32,42,13,23,33,43,14,24,34,44,15,25,35,45
```

**Comment by funko-unko** [comment]
Hm, but it does store them differently internally, doesn't it? Anyways, good that the output (and input I guess) is uniform.

**Comment by ahartikainen** [comment]
While in C++?

**Comment by funko-unko** [comment]
Yes, as described eg here https://mc-stan.org/docs/2_18/stan-users-guide/indexing-efficiency-section.html

**Comment by mitzimorris** [comment]
yes, in C++, vectors and matrix operations use the Eigen library, while arrays use std::vector.   there's quite a bit of work being done on the math library to make things more efficient.

but as far as outputs go, a container variable is a container variable, and indexing is column-major.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/363
