### ISSUE TITLE
Add a 'to_frame' method to convert draws to a pandas dataframe

### ISSUE THREAD

**Issue by vnijs** [stan-dev/cmdstanpy#373]
One method from the `pystan` package that is quite convenient is `to_frame`. I'm not sure if a direct translation of that method is easily feasible so I put the rudimentary function below together as a demonstration of the desired functionality. The `fit` argument in the function below is the result from the `sample` method in `cmdstanpy`. It would be wonderful if you would consider adding a method that produces a dataframe of draws.

```
def to_frame(fit):
    """
    Create a Pandas dataframe with draws for all variables
    """
    thePars = []
    for var, shape in fit.stan_vars_dims.items():
        
        if len(shape) == 0:
            df = pd.DataFrame(fit.stan_variable(var))
            df.columns = [var]
        elif len(shape) == 1:
            df = pd.DataFrame(fit.stan_variable(var))
            df.columns = [f"{var}.{c+1}" for c in df.columns]
        elif len(shape) == 2:
            df = pd.DataFrame(np.reshape(fit.stan_variable(var), (-1, shape[0]*shape[1])))
            df.columns = [f"{var}.{c1+1}.{c2+1}" for c1 in range(shape[0]) for c2 in range(shape[1])]
        else:
            print("Shape of array is not (yet) handled properly by the extract function")
            return pd.DataFrame()
        
        thePars.append(df)

    thePars = [pd.DataFrame({"draws": np.arange(thePars[0].shape[0])})] + thePars
    return pd.concat(thePars, axis=1).set_index("draws")
```

**Comment by ahartikainen** [comment]
`fit.draws_pd()`

**Comment by mitzimorris** [comment]
hi @vnijs, please consider putting together a PyStan to CmdStanPy cheatsheat - this would be a great addition to the documentation - and glad you're using CmdStanPy!  we welcome contributors - would any of the ones here https://github.com/stan-dev/cmdstanpy/projects/1 - be useful to you?

**Comment by mitzimorris** [comment]
closing issue - feature exists.

**Comment by vnijs** [comment]
@mitzimorris I'm just starting out with stan and have been mostly an R user for many years. Doing more with python now and so looking at the different options for stan in python so don't have much experience with pystan yet either. Thanks for making these great tools easily accessible!

Thanks @ahartikainen! I looked for `to_frame` and didn't find it ... which leads to the following question.

**Question:** Is there a reason that function/method names and function/method arguments differ across different interfaces to stan?  e.g., pystan uses `to_frame` and cmdstanpy uses `draws_pd`? Also, pystan uses `Omega.1.2` for column names and `cmdstanpy` uses  `Omega[1,2]`. rstan uses `iter`, `warmup`, `chains` as argument names for the `sampling` function, pystan uses `num_chains`, `num_samples`, `num_warmup` for the `sample` method, and cmdstanpy uses `chains`, `iter_warmup`, `iter_sampling` for the `sample` method.

**Comment by mitzimorris** [comment]
The CmdStan interface diverged from PyStan and RStan a long time ago.  CmdStanPy and CmdStanR can be used with any version of CmdStan, including the latest.  The CmdStanPy and CmdStanR names more-or-less follow CmdStan names - there's been much back and forth on which names are clear and unambiguous.

As a Stan user, I used RStan, and found dealing with the R `stanfit` object and especially the `extract` function extremely confusing.  So in CmdStanPy, there was a conscious decision not follow the RStan names if more descriptive ones were available.  the name `draws` describes the information you get back.  the name `to_frame` just tells you the data type.  I think `draws` is more descriptive, but opinions differ.
