### ISSUE TITLE
Compilation of STAN model fails, "Need to set TBB_CXX_TYPE"

### ISSUE THREAD

**Issue by washiloo** [stan-dev/cmdstanpy#374]
#### Summary:
I'm getting an error when trying to compile a very simple STAN program from a _.stan_ file. I'm running python 3 inside Jupyter Lab.

#### Description:
I'm just trying to test a very simple model described in the official Stan's User Guide. However, the code fails when trying to compile the model. I'm using python 3 inside a notebook in Jupyter Lab. Here's my code:

```
from cmdstanpy import CmdStanModel as stan_model

stan_script = '''data {
    int<lower=0> N;
    vector[N] x;
    vector[N] y;
}
parameters {
    real alpha;
    real beta;
    real<lower=0> sigma;
}
model {
    y ~ normal(alpha + beta * x, sigma);
}
'''

with open('stan_linear.stan','w+') as file:
  file.writelines(stan_script)

sm = stan_model(stan_file ='stan_linear.stan')
```

This last line of code won't work, and the error message is:

```
INFO:cmdstanpy:compiling stan program, exe file: /home/washiloo/Documents/Work/Knowledge/Bayes/STAN/stan_lin
INFO:cmdstanpy:compiler options: stanc_options=None, cpp_options=None
ERROR:cmdstanpy:file /home/washiloo/Documents/Work/Knowledge/Bayes/STAN/stan_lin.stan, exception ERROR
stan/lib/stan_math/make/libraries:117: *** "Need to set TBB_CXX_TYPE for non-standard compiler other than gcc or clang.".  Stop. 
ERROR:cmdstanpy:model compilation failed
```

I tried the following two things: (1) created a file named `local` in the CmdStan `make` subdirectory, and added the line `TBB_CXX_TYPE=clang`; (2) replaced `clang` with `gcc` in the same file. In both cases, the compiler _does something_ (it creates two files with extensions `.o` and `.hpp`). However, a new error appears, namely:

```
INFO:cmdstanpy:compiling stan program, exe file: /home/washiloo/Documents/Work/Knowledge/Bayes/STAN/stan_lin
INFO:cmdstanpy:compiler options: stanc_options=None, cpp_options=None
ERROR:cmdstanpy:file /home/washiloo/Documents/Work/Knowledge/Bayes/STAN/stan_lin.stan, exception ERROR
/home/washiloo/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: stan/lib/stan_math/lib/tbb/libtbb.so.2: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
make: *** [/home/washiloo/Documents/Work/Knowledge/Bayes/STAN/stan_lin] Error 1 
ERROR:cmdstanpy:model compilation failed
```

#### Additional Information:
I installed `cmdstanpy` as described in the [documentation](https://cmdstanpy.readthedocs.io/en/latest/getting_started.html#installation). I installed `cmdstan` using the `install_cmdstan` function from `cmdstanpy`. 

#### Current Version:
`cmdstanpy` 0.9.75
`cmdstan` 2.26.1
`python` 3.6.9
`g++` 7.5.0
`make` 4.1

**Comment by mitzimorris** [comment]
the `make/local` file with `TBB_CXX_TYPE=gcc` is what you need.

I think the problem is that the CmdStan install built the libraries and pre-compiled header files with clang, so the linker is unhappy.  what you need to do here is `make clean` then `make build` from the command line in the CmdStan installation directory - default location `~/.cmdstan/cmdstan-2.26.1`.  hope this helps

**Comment by mitzimorris** [comment]
and if this works, suggestions on how to describe your problem - we definitely need more on troubleshooting the installation in both CmdStanPy and CmdStan docs.

**Comment by washiloo** [comment]
> the `make/local` file with `TBB_CXX_TYPE=gcc` is what you need.
> 
> I think the problem is that the CmdStan install built the libraries and pre-compiled header files with clang, so the linker is unhappy. what you need to do here is `make clean` then `make build` from the command line in the CmdStan installation directory - default location `~/.cmdstan/cmdstan-2.26.1`. hope this helps

Thank you very much for your answer. As you suggested, I proceeded with `make clean` then `make build`, with the following output:

```
(base) washiloo@washiloo-Lenovo-V130-15IGM:~/.cmdstan/cmdstan-2.26.1$ make clean
rm -f -r test
rm -f 
rm -f 
rm -f 
rm -f 
(base) washiloo@washiloo-Lenovo-V130-15IGM:~/.cmdstan/cmdstan-2.26.1$ make build 
--- CmdStan v2.26.1 built ---
```

However, I still get the same error when trying to compile the model:

```
ERROR:cmdstanpy:file /home/washiloo/Documents/Work/Knowledge/Bayes/STAN/stan_lin.stan, exception ERROR
/home/washiloo/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: stan/lib/stan_math/lib/tbb/libtbb.so.2: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
make: *** [/home/washiloo/Documents/Work/Knowledge/Bayes/STAN/stan_lin] Error 1 
ERROR:cmdstanpy:model compilation failed
```

**Comment by mitzimorris** [comment]
@rok-cesnovar, @ahartikainen - TBB on linux problems?

**Comment by SteveBronder** [comment]
> `memcpy@GLIBC_2.14`

Are you compiling cmdstan in the same environment you are then compiling the model? A linker error like the above can usually mean the object files are being built with different versions of gcc

**Comment by rok-cesnovar** [comment]
This seems to be an issue with make not being able to find the OS variable. Can you run
```
make print-OS
make print-CXX
```

It should return 
```
OS = Linux
CXX = g++
```

**Comment by washiloo** [comment]
> > `memcpy@GLIBC_2.14`
> 
> Are you compiling cmdstan in the same environment you are then compiling the model? A linker error like the above can usually mean the object files are being built with different versions of gcc

@SteveBronder  Thank you very much. Unfortunately, I'm not sure how to answer your question. I just realized I didn't give a complete description of my problem. I'm running python from a notebook in Jupyter Lab. Could that be the problem?

I executed the command `!pip show cmdstanpy` inside the notebook, with the following output:

```
Name: cmdstanpy
Version: 0.9.75
Summary: Python interface to CmdStan
Home-page: https://github.com/stan-dev/cmdstanpy
Author: Stan Dev Team
Author-email: None
License: UNKNOWN
Location: /home/washiloo/anaconda3/lib/python3.6/site-packages
Requires: numpy, ujson, pandas
Required-by: 
```

However, when I execute `!pip show cmdstan`, the output is:

```WARNING: Package(s) not found: cmdstan```.

However, I installed `cmdstan` using `install_cmdstan()` from `cmdstanpy` inside Jupyter, and it worked. I just tried again and the output is as follows:

```
Installing CmdStan version: 2.26.1
Install directory: /home/washiloo/.cmdstan
CmdStan version 2.26.1 already installed
deleting tmpfiles dir: /tmp/tmplfsxmqc5
done
```

As explained in the documentation, the default for the `cmdstan` installation location is a directory named `.cmdstanpy` in my `home` directory. Nevertheless, the output of `sys.prefix` gives me `/home/washiloo/anaconda3`, and I believe this should be the actual environment where I'm executing all the code. What I don't really understand is:  when you talk about **compiling** `cmdstan`, do you mean if I installed it in the same environment where I execute the code? Sorry, but I'm an amateur in these things and I got a little confused here. If that's the case, would reinstalling `cmdstan` in `/home/washiloo/anaconda3/lib/python3.6/site-packages` (location of `cmdstanpy`) solve the problem?

**Comment by washiloo** [comment]
> This seems to be an issue with make not being able to find the OS variable. Can you run
> 
> ```
> make print-OS
> make print-CXX
> ```
> 
> It should return
> 
> ```
> OS = Linux
> CXX = g++
> ```

@rok-cesnovar Thanks! I tried it and the output is different from yours, namely:

```
OS = Linux
CXX = /home/washiloo/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++
```

**Comment by rok-cesnovar** [comment]
What if you set CXX=g++ in make/local?

**Comment by washiloo** [comment]
> What if you set CXX=g++ in make/local?

@rok-cesnovar Yeah! This worked! Thank you very much!

The final solution was to create variable `local` in CmdStan `make` subdirectory, with the following two lines:
```
CXX=g++
TBB_CXX_TYPE=gcc
```

Should I just close the issue or can I do something else to help?

Thank you all for your help!

**Comment by rok-cesnovar** [comment]
Great!

I think we can close. Not sure there is much else we can do here on CmdStan(py) side.

**Comment by mitzimorris** [comment]
thanks for working through this everyone.
this should go somewhere in the CmdStanPy / CmdStan docs.
