### ISSUE TITLE
Can't extract quantities of interest from output CSV files without hard-coding

### ISSUE THREAD

**Issue by washiloo** [stan-dev/cmdstanpy#376]
#### Summary:
I tried to open the `.csv` files generated with `CmdStanMCMC.save_csvfiles()` in order to extract the results of the inference, but I couldn't figure out a solution without hardcoding. Related to #345 but more elemental.

#### Description:
After running the sampler on a test model and getting the corresponding CmdStanMCMC object, I used the method `save_csvfiles()` to save the `.csv` files corresponding to each chain. I tried to open them with Pandas `read_csv()` method, but it didn't work (`ParserError: Error tokenizing data. C error: Expected 1 fields in line 43, saw 110`). Then I tried the more elemental `csv` module from _python_ and managed to read the information, but couldn't make it without a bit of hardcoding. Here's a very simple test code to generate the `csv` files, created solely for reproducing this issue:

```
from cmdstanpy import CmdStanModel as stan_model
import numpy as np

# Some parameters of a linear model
alpha_true = -2.5 # Intercept
beta_true = 1.3 # Slope
sigma_true = 0.65 # Standard deviation of gaussian error

# Data synthesis
x = np.linspace(-10,10,100) # Predictor
y = alpha_true + beta_true*x + np.random.normal(size = len(x),scale = sigma_true) # Target

# Data in Stan format
data = {"N": len(x),
        "x": x,
        "y": y}

# Model in Stan format
stan_script = '''data {
    int<lower=0> N;
    vector[N] x;
    vector[N] y;
}
parameters {
    real alpha;
    real beta;
    real<lower=0> sigma;
}
model {
    y ~ normal(alpha + beta * x, sigma);
}
generated quantities {
    vector[N] log_likelihood;
    for(i in 1:N){
        log_likelihood[i] = normal_lpdf(y[i] | alpha + beta * x[i], sigma);
    }
}
'''
model_name = 'model_lin' # Name of the model

with open(model_name + '.stan','w+') as file: # Create stan_file
  file.writelines(stan_script)

model_lin = stan_model(stan_file = model_name + '.stan') # Compile Stan model
model_fit = model_lin.sample(data = data,iter_sampling = 10,iter_warmup = 5,chains = 2,parallel_chains = 2) # Posterior sampling
model_fit.save_csvfiles(model_name + '.csv') # Save inference results
```

and here's my workaround to read all sampler and model parameters and quantities of interest:

```
import pandas as pd
import csv
from os import listdir

def load_stan_csv(filename): # Load inference results from file saved with CmdStanMCMC.save_csvfiles()
  with open(filename) as file: # Open the csv file
    reader = csv.reader(file,delimiter = ',') # Read the file
    rows_worth_reading = [row for idx, row in enumerate(reader) if idx == 42 or idx > 46] # Select the columns (hardcoding!)
  return pd.DataFrame(rows_worth_reading[:-5]) # More hardcoding!

# Load inference results
chain_files = [f for f in listdir(model_name + '.csv') if '.csv' in f] # Look for .csv files in folder model_name.csv
filename = model_name + '.csv/' + chain_files[0] # File name (first chain)
inf_results = load_stan_csv(filename) # Load first MC chain and store data in a dataframe

print(inf_results)
```
 
The result stored in `inf_results` is a dataframe with column names as given by `CmdStanMCMC.column_names()` (110 in this example) and as many rows as given by `iter_sampling` (10 in this example, not including warm-up). This is exactly what I wanted, so this approach does help me in this case. However, I needed to manually select the rows in the `csv_reader` iterator in order to get the desired information. Is there a way to do this automatically? I really think that the feature proposed in #345 is of greater convenience, but in the meanwhile it would be nice to get this information easily.

#### Current Version:
`cmdstanpy` 0.9.75
`cmdstan` 2.26.1
`python` 3.6.9

**Comment by ahartikainen** [comment]
Hi

Here is pandas solution (force the use of float --> there is possibility that some quantity could get stuck in e.g. 0 and then pandas would infer it to int): 

    df = pd.read_csv(path, comment="#", dtype=float)

I recommend trying arviz InferenceData
(please install current main from github -> there have been some fixes in Stan interfaces which are not yet in pypi; new release will be done somewhere in the next 2 months

`pip install git+https://github.com/arviz-devs/arviz`
)

    import arviz as az
    path_glob = "path/to/files_*.csv"
    # or use a list of paths
    idata = az.from_cmdstan(path_glob)

For more advanced use read more about InferenceData and its groups and use.

https://arviz-devs.github.io/arviz/getting_started/XarrayforArviZ.html

https://arviz-devs.github.io/arviz/api/generated/arviz.from_cmdstan.html

**Comment by ahartikainen** [comment]
Also, for manually reading the csv you can do (for 1 chain)

    data = []
    header = None
    comments = []
    with open(path) as f:
        for line in f:
            if not line.strip():
                continue
            if line.startswith("#"):
                comments.append(line.strip())
            else:
                if header is None:
                    header = line.strip().split(",")
                else:
                    data.append(line.strip().split(","))

    df = pd.DataFrame(data, columns=header)

Then you need to manually combine different chains.

**Comment by washiloo** [comment]
> Hi
> 
> Here is pandas solution (force the use of float --> there is possibility that some quantity could get stuck in e.g. 0 and then pandas would infer it to int):
> 
> ```
> df = pd.read_csv(path, comment="#", dtype=float)
> ```
> 
> I recommend trying arviz InferenceData
> (please install current main from github -> there have been some fixes in Stan interfaces which are not yet in pypi; new release will be done somewhere in the next 2 months
> 
> `pip install git+https://github.com/arviz-devs/arviz`
> )
> 
> ```
> import arviz as az
> path_glob = "path/to/files_*.csv"
> # or use a list of paths
> idata = az.from_cmdstan(path_glob)
> ```
> 
> For more advanced use read more about InferenceData and its groups and use.
> 
> https://arviz-devs.github.io/arviz/getting_started/XarrayforArviZ.html
> 
> https://arviz-devs.github.io/arviz/api/generated/arviz.from_cmdstan.html

Thank you **very much** for your extremely helpful answer! Pandas solution worked like a charm, but I definitely prefer the arviz `InferenceData` method. Actually I did try it before opening this issue, but it didn't work _because I was using ArviZ from PyPI_. Thanks to you, I already installed the newer version from github and it's working perfectly.

**Comment by mitzimorris** [comment]
for the record, the feature you're looking for would be this:  https://github.com/stan-dev/cmdstanpy/issues/345

**Comment by washiloo** [comment]
> for the record, the feature you're looking for would be this: #345

@mitzimorris yeah, I have seen it before and commented about it in the description of the issue, so that people can see the link. Thanks! :-)
