### ISSUE TITLE
Spaces in stan file path force recompilation (macOS Big Sur)

### ISSUE THREAD

**Issue by jerzybaranowski** [stan-dev/cmdstanpy#377]
#### Summary:
Spaces in path cause CmdStanModel.compile() to recompile model every time.

#### Description:
Whenever there are spaces in path, i.e.

'/Users/jerzybaranowski/GitHub/private/stan_public/cmdstanpy_spaces/with space'

Running 

``` 
from cmdstanpy import CmdStanModel 
model_ppc=CmdStanModel(stan_file='height_2_fit.stan')
```

results in:

```
INFO:cmdstanpy:compiling stan program, exe file: /var/folders/j5/wr2j95x534x62nm4sfx97cbc0000gn/T/tmp4fdpysap/tmprn0vm9sr
INFO:cmdstanpy:compiler options: stanc_options=None, cpp_options=None
INFO:cmdstanpy:compiled model file: /Users/jerzybaranowski/GitHub/private/stan_public/cmdstanpy_spaces/with space/height_2_fit
```

and repeated 

```
model_ppc.compile()
```

results in compilation:

```
INFO:cmdstanpy:compiling stan program, exe file: /var/folders/j5/wr2j95x534x62nm4sfx97cbc0000gn/T/tmpfzqqtjt5/tmpukol5478
INFO:cmdstanpy:compiler options: stanc_options=None, cpp_options=None
INFO:cmdstanpy:compiled model file: /Users/jerzybaranowski/GitHub/private/stan_public/cmdstanpy_spaces/with space/height_2_fit
```

Notebooks replicating this issue [are here](https://github.com/jerzybaranowski/stan_public/tree/master/cmdstanpy_spaces)
#### Additional Information:
Run on macOS Big Sur 11.2.3, MacBook Pro (16-inch, 2019), Intel Core i9
#### Current Version:
Python 3.7.10 64-bit
CmdStan 0.9.75

**Comment by mitzimorris** [comment]
will investigate ASAP - this shouldn't happen

**Comment by ahartikainen** [comment]
Do you have minimal working example for this?

**Comment by jerzybaranowski** [comment]
I've linked my public repo
