### ISSUE TITLE
`GenerateQuantitiesArgs.compose` rolls csv files. 

### ISSUE THREAD

**Issue by funko-unko** [stan-dev/cmdstanpy#378]
I believe this

```
    def compose(self, idx: int, cmd: List) -> str:
        """
        Compose CmdStan command for method-specific non-default arguments.
        """
        cmd.append('method=generate_quantities')
        cmd.append('fitted_params={}'.format(self.sample_csv_files[idx - 1]))
        return cmd
```
https://github.com/stan-dev/cmdstanpy/blob/develop/cmdstanpy/cmdstan_args.py

should be changed to 
```
cmd.append('fitted_params={}'.format(self.sample_csv_files[idx]))
```

`idx` runs from `0` to `chains-1`, does it not?

**Comment by funko-unko** [comment]
Also, here is an MWE:

**Stan**
```stan
parameters {
  real x;
}
model {
  x ~ normal(0,1);
}
generated quantities{
  real y = x;
}

```
**Python**
```python
import cmdstanpy

model = cmdstanpy.CmdStanModel(stan_file='gq.stan')
fit = model.sample(iter_sampling=1)
gq = model.generate_quantities(dict(), fit)
print(gq.sample_plus_quantities[['x', 'y']])
```

**Output**
```
          x         y
0 -0.031481  0.514543
1 -0.553526 -0.031481
2  0.399519 -0.553526
3  0.514543  0.399519
```

**Comment by funko-unko** [comment]
In case the severity of this has not become clear:

This generally completely breaks any relation between the parameters and the generated quantities.

Tagging because I'm impatient, sorry. @mitzimorris @ahartikainen

**Comment by funko-unko** [comment]
@mitzimorris No, thank you for building, maintaining and fixing everything!

I would have opened a pull request but am still not 100% sure how this works and thought this should just be communicated asap.

To be honest, I'm impressed that everything works as well as it does, the differences in indexing and storage order always trip me up...

**Comment by mitzimorris** [comment]
we welcome PRs!  some info is here: https://github.com/stan-dev/cmdstanpy/wiki#developers
