### ISSUE TITLE
logger not passed from CmdStanModel to CompileOptions

### ISSUE THREAD

**Issue by bwengals** [stan-dev/cmdstanpy#380]
#### Summary:
`logger` instance doesn't get passed from `CmdStanModel` to `CompileOptions`

#### Description:
It looks like in the code [here](https://github.com/stan-dev/cmdstanpy/blob/a4ffc6c5ff4966523a12b26ff9de8d6b1d3bd96d/cmdstanpy/model.py#L98-L101) that the `logger` instance isn't getting propagated through to `CompileOptions`, which itself accepts a `logger`, and will call `get_logger()` if `logger` is None.  

#### Additional Information:

This causes cmdstanpy to add a redundant stream handler with BasicConfig, even though `logger` is being passed in to `CmdStanModel`, causing dup messages.  Would be more than happy to submit a PR (if thats helpful of course)

#### Current Version:

Am running python 3.9, cmdstanpy 0.9.75, but looks like this is on `develop`.

**Comment by mitzimorris** [comment]
see https://github.com/stan-dev/cmdstanpy/issues/415 - we should get rid of logger attributes altogether

**Comment by mitzimorris** [comment]
will be addressed as part of issue https://github.com/stan-dev/cmdstanpy/issues/415

**Comment by bwengals** [comment]
gotcha, thank you!
