### ISSUE TITLE
Add seconds to the filenames of the output csv files

### ISSUE THREAD

**Issue by al-jshen** [stan-dev/cmdstanpy#383]
#### Summary:
Suggestion: change the datetime portion of the template output filenames from YYYYMMDDHHMM to YYYYMMDDHHMMSS.

#### Description:
I am running a small model on different subsets of data. If the model takes less than a minute to run, and I run it again on some new data, the old output csv files are overwritten. I need to either manually rename the files and change the filenames in the model (a pain to do), or wait a minute before I can rerun the model. 

#### Current Version:
Python 3.9.4
CmdStan 2.26.1
CmdStanPy 0.9.75

**Comment by ahartikainen** [comment]
CmdStan takes 7s to compile a model -> this is reasonable suggestion.

I wonder if we could add `fmt="%Y%m%d%H%M%S"` or something similar as a keyword

->

    "output"+datetime.now().strftime(fmt)
