### ISSUE TITLE
Support Non-UTF-8 terminal

### ISSUE THREAD

**Issue by akirayou** [stan-dev/cmdstanpy#384]
#### Summary:
Install_cmdstan and so on could not run on a non-UTF-8 terminal.
For example, Japanese/Chinese/Korean windows. 

#### Description:
The terminal encoding is normally sys.stdin.encoding. But CmdnStanPy hardcords 'utf-8'.
Here is the workaround. This workaround use CMDSTAN_ENCODING Environment value to override the terminal encoding. 
https://github.com/akirayou/cmdstanpy/commit/db1431c13ee5ab35e0c440d686ed1eb79e0815e3
 
#### Additional Information:
To test the above patch, you have to modify the test code like this.
Because Windows filesystem is a case insensitive filesystem. 
https://github.com/akirayou/cmdstanpy/commit/883ac4531fa3557a601e3387aa9d5b705610d7e3

#### Current Version:
https://github.com/stan-dev/cmdstanpy/commit/ecd844e9945ecf153be21ab69112d71862d2e0be

**Comment by akirayou** [comment]
Here is the error message.
WARNING:cmdstanpy:CmdStan installation failed.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\akira\anaconda3\envs\cmdstanpy_test\lib\site-packages\cmdstanpy\utils.py", line 986, in install_cmdstan
    logger.warning(stderr.decode('utf-8').strip())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 839: invalid start byte
>>>

**Comment by ahartikainen** [comment]
What if we would use chardet library to detect encoding?

**Comment by akirayou** [comment]
Encoding estimation is just an estimation. I do not recommend it.

For example "魍魎"(CP932/Japan : means 'goblins') == "敼斢"(CP950/Taiwan:means 'play music yellow') ==0xE9B1E9B2  .

Estimating encoding is not easy in a short sentence. 
So I think user-defined encoding or using system encoding is better.
And also, I don't want to add unnecessary dependencies.

**Comment by ahartikainen** [comment]
We could probably go with system encoding + error handling (.decode(..., errors="replace")?


ENV var is one option.

**Comment by akirayou** [comment]
In my environment, ENV is needed (Windows).
python 3.8.4 on win10 ignores the encoding setting for python.
If there is another method to get terminal encoding, It's ok but I don't know.

> C:\Users\akira>set PYTHONIOENCODING=cp932
> C:\Users\akira>python
> Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import sys
> >>> sys.stdin.encoding
> 'utf-8'
sys.stdin.encoding is 'utf-8' but ,I need 'cp932'.


In Ubuntu , sys.stdin.encoding is usable with PYTHONIOENCODING Environment value.
> $ PYTHONIOENCODING=cp932 python
> Python 3.8.3 (default, Jul  2 2020, 16:21:59)
> [GCC 7.3.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import sys
> >>> sys.stdin.encoding
> 'cp932'

**Comment by akirayou** [comment]
Sorry, I solved it myself.  

import platform
import sys
TERMINRL_ENCODING=sys.stdin.encoding # You can set this by PYTHONIOENCODING Environment
if platform.system()=="Windows": # In case of windows, you have to get it via Win32API
    import win32console
    TERMINAL_ENCODING="cp{}".format(win32console.GetConsoleCP())

**Comment by mitzimorris** [comment]
making sure I understand what's going on here:  is the fix is to get your environment variables set correctly?
if so, we should explain and document this for others in the CmdStanPy install docs

**Comment by akirayou** [comment]
In the previous messages, I proposed 2 types of solutions, one is with ENV, another is without ENV.
Both solutions are OK for me. Which one do you like?

1.With ENV: (set by CMDSTAN_ENCODING  /  need documentation for windows users) 
Implementation example:
https://github.com/akirayou/cmdstanpy/blob/db1431c13ee5ab35e0c440d686ed1eb79e0815e3/cmdstanpy/utils.py#L32-L34

Documentation example:
```
For non-English Windows users. You have to set the OS encoding (code page) via CMDSTAN_ENCODING environment variable. For example CMDSTAN_ENCODING=cp932 in Japan.
All configurable encodings are listed in  https://docs.python.org/3/library/codecs.html#standard-encodings .

```

2.Without ENV:(get OS encoding via win32API  / don't need documentation [detect encoding automatically])
Implementation example:
https://github.com/akirayou/cmdstanpy/blob/bugifx-candidate/terminal_encoding/cmdstanpy/utils.py#L33-L47

Documentation example:
None

**Comment by WardBrian** [comment]
Are you using Powershell or CMD.exe? In Powershell, you should not be using 'set'

Try:
```pwsh
C:\Users\akira> $Env:PYTHONIOENCODING=cp932
C:\Users\akira>python
```
