### ISSUE TITLE
Provide Source for cmdstanpy v0.9.68 in PyPI

### ISSUE THREAD

**Issue by elacy** [stan-dev/cmdstanpy#386]
#### Summary:
Source code package is available for 0.9.66 but not 0.9.68

https://pypi.org/project/cmdstanpy/0.9.66/#files
https://pypi.org/project/cmdstanpy/0.9.68/#files

Can you please add the source code tar.gz for the 0.9.68 version

**Comment by ahartikainen** [comment]
Hi, is there a reason why you need source tar?

We have fixed this issue in the upload workflow, so the next version will contain the source tar.

For now, you can access the source from the github

https://github.com/stan-dev/cmdstanpy/releases/tag/v0.9.68

https://github.com/stan-dev/cmdstanpy/archive/refs/tags/v0.9.68.tar.gz

**Comment by elacy** [comment]
Yes, we have a tool where I work that automatically downloads the source and builds it because they don't trust binaries. So it would be super great if you could upload the tar.gz onto pip.. would involve less reverse engineering on my part.

**Comment by mitzimorris** [comment]
@serban-nicusor-toptal - how hard would it be to put the source on pypi?

@ahartikainen is this a commonly done practice?  just curious.

**Comment by serban-nicusor-toptal** [comment]
Hey @mitzimorris not hard at all, I've opened a [PR](https://github.com/stan-dev/cmdstanpy/pull/387) for this issue.

**Comment by ahartikainen** [comment]
We can manually add source for old distributions if we want. Current workflow already does this for any new release.

https://docs.python.org/3/distutils/sourcedist.html

**Comment by ahartikainen** [comment]
Source code for the latest two releases are now in pypi.

https://pypi.org/project/cmdstanpy/0.9.68/#files
https://pypi.org/project/cmdstanpy/0.9.75/#files
