### ISSUE TITLE
"Hello, World" example could be explicit what is in bernoulli.stan and bernoulli.data.json

### ISSUE THREAD

**Issue by artturib** [stan-dev/cmdstanpy#390]
At the moment the contents of the files used in the example are not explicitly labeled.

Suggestion:

To exercise the essential functions of CmdStanPy we show how to run Stan's HMC-NUTS sampler to estimate the posterior probability of the model parameters conditioned on the data, using the example Stan model `bernoulli.stan` and corresponding dataset `bernoulli.data.json` which are distributed with CmdStan.

This is a simple model for binary data: given a set of N observations of i.i.d. binary data y[1] ... y[N], it calculates the Bernoulli chance-of-success theta. The contents of `bernoulli.stan` are:

```
data {
   int<lower=0> N;
   int<lower=0,upper=1> y[N];
 }
 parameters {
   real<lower=0,upper=1> theta;
 }
 model {
   theta ~ beta(1,1);  // uniform prior on interval 0,1
   y ~ bernoulli(theta);
 }
```

and similarly for bernoulli.data.json

**Comment by WardBrian** [comment]
The doc now features this information! Thank you
