### ISSUE TITLE
UnboundLocalError in utils.do_command

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/cmdstanpy#392]
#### Description:
If utils.do_command fails, in addition to the command exception it will raise 

`UnboundLocalError: local variable 'msg' referenced before assignment`

This is because of a simple typo here:
https://github.com/stan-dev/cmdstanpy/blob/f6a526807ea4d248844ac2f1a44e4c53bfca197c/cmdstanpy/utils.py#L879-L881

I believe the second 'msg' on line 880 should actually be 'cmd'

#### Current Version:
0.9.76

**Comment by mitzimorris** [comment]
who, thanks - good catch - fixing now.

**Comment by mitzimorris** [comment]
hi @WardBrian,  I submitted a PR.  if you'd like to do the code-review, I'll add you to the repo.  always glad to have more contributors.

**Comment by WardBrian** [comment]
Happy to, @mitzimorris

**Comment by mitzimorris** [comment]
@WardBrian great - just sent and invite
