### ISSUE TITLE
Enable STAN_NO_RANGE_CHECKS

### ISSUE THREAD

**Issue by rok-cesnovar** [stan-dev/cmdstanpy#394]
#### Summary:

The following should work:

```python
model = CmdStanModel(stan_file=model2, cpp_options={"STAN_NO_RANGE_CHECKS": True})
```

But I get:
```
.../cmdstanpy/compiler_opts.py", line 157, in validate_cpp_opts
    'unknown CmdStan makefile option: {}'.format(key)
ValueError: unknown CmdStan makefile option: STAN_NO_RANGE_CHECKS
```

Why is Cmdstanpy not just allowing any key to cpp_options? Updating a list of allowed options seems annoying for maintaining to me.

**Comment by mitzimorris** [comment]
you're right.
for the stanc options, I think we need to check, but not for the cpp options.
will fix.
