### ISSUE TITLE
CmdStanPy should check that utilities `stansummary` and `diagnose` have been built by install process

### ISSUE THREAD

**Issue by montealegredanny** [stan-dev/cmdstanpy#396]
#### Summary:
I followed the installation description here: https://cmdstanpy.readthedocs.io/en/v0.9.76/installation.html and when I was running the "Hello World" example, the program errored out when calling `bern_fit.summary()`

#### Description:
Following the example in: https://cmdstanpy.readthedocs.io/en/v0.9.76/hello_world.html but it fails on the line `bern_fit.summary()` with the error message: 

`FileNotFoundError                         Traceback (most recent call last)
~\anaconda3\lib\site-packages\cmdstanpy\utils.py in do_command(cmd, cwd, logger)
    839     try:
--> 840         proc = subprocess.Popen(
    841             cmd,

~\anaconda3\Lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    853 
--> 854             self._execute_child(args, executable, preexec_fn, close_fds,
    855                                 pass_fds, cwd, env,

~\anaconda3\Lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
   1306             try:
-> 1307                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1308                                          # no special security

FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

UnboundLocalError                         Traceback (most recent call last)
<ipython-input-14-e0c0ffa7d8b3> in <module>
----> 1 bern_fit.summary()

~\anaconda3\lib\site-packages\cmdstanpy\stanfit.py in summary(self, percentiles, sig_figs)
    879             csv_str,
    880         ] + self.runset.csv_files
--> 881         do_command(cmd, logger=self.runset._logger)
    882         with open(tmp_csv_path, 'rb') as fd:
    883             summary_data = pd.read_csv(

~\anaconda3\lib\site-packages\cmdstanpy\utils.py in do_command(cmd, cwd, logger)
    878             return msg
    879     except OSError as e:
--> 880         msg = 'Command: {}\nfailed with error {}\n'.format(msg, str(e))
    881         raise RuntimeError(msg) from e
    882     return None  # success

UnboundLocalError: local variable 'msg' referenced before assignment`

#### Additional Information:
Provide any additional information here.

#### Current Version:
cmdstan-2.27.0

**Comment by montealegredanny** [comment]
Never mind -- if anyone runs into this make sure that you have the `stansummary.exe` file in your bin folder. I had to do a build and I got the .exe file.

**Comment by mitzimorris** [comment]
we should always throw helpful errors.  re-opening/re-naming - add checks that cmdstan/bin programs exists.
