### ISSUE TITLE
Allow pandas objects as parts of data dicts

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/cmdstanpy#397]
#### Summary:
Passing a pandas object as part of a data dictionary currently leads to a TypeError, because the json module can't serialize the object. Calling `.to_numpy()` on the object resolves this, and I believe cmdstanpy should do this internally by default

#### Description:

Here's a MWE, presuming we have a dataset with 'height' as a variable:

```python
import pandas as pd
from cmdstanpy import CmdStanModel

model = CmdStanModel(...)
d = pd.read_csv(...)
fit = model.sample(data={"N": len(d), "heights": d.height)
```
This leads to a type error, but 

```python
fit = model.sample(data={"N": len(d), "heights": d.height.to_numpy())
```
works as expected.

#### Additional Information:

Our [json dump](https://github.com/stan-dev/cmdstanpy/blob/aea7cc45b2a4e26fa5b508a4220a5e758d1daf18/cmdstanpy/utils.py#L369) method already has some special logic to handle numpy arrays, which would compose well with this. I believe we could add something as simple as 

```python
if isinstance(val, (pd.Series, pd.DataFrame)):
    val = val.to_numpy()
```

_before_ the existing conditional and that should handle it.

I'm happy to submit a PR if this sounds like desirable behavior

#### Current Version:
0.9.76

**Comment by ahartikainen** [comment]
I think we could add these lines

```
        if type(value).__module__ == "numpy":
            data[key] = value.tolist()
        elif isinstance(value, collections.abc.Collection):
            data[key] = np.asarray(value).tolist()
```

**Comment by WardBrian** [comment]
That seems like a good general solution to me
