### ISSUE TITLE
implement wrapper function to cmdstan `bin/stansummary`

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#4]
#### Summary:
Implement the function described in the CmdStanPy Functional Spec:

https://github.com/stan-dev/design-docs/blob/master/designs/0002-cmdstanpy_func_spec.md#summary
`summary(runset = `sampler_runset`, output_file= "filename")`

**Comment by mitzimorris** [comment]
refactor code base as appropriate for this feature - e.g., make RunSet be its own file `runset.py`

code should be Python2 and Python3 compatible (pre issue #1)

**Comment by maedoc** [comment]
just a few comments/questions to clarify intent:

> much of current class RunSet goes away

The current `RunSet` class provides a convenience layer such that calling the summary explicitly isn't required, e.g. `assert all(model.run(chains=4).R_hat < 1.1)`.  I guess it's a little bit OO where you're going for array oriented.

> RunSet is a very lightweight wrapper around the chain id, and the list of output files

This is a little shallow, in my opinion: the current `Run` class manages the "lifecycle" of the process of invoking the compiled executable, monitoring when it stops, ensures it isn't invoked while running, returns its CSV etc.  `RunSet` is a container for `Run`s, but I don't think the implementation can be reduced further without causing headaches for users.

> `model` ~function~ method `run` should always return a RunSet object

this is already this case, except whens `chains=1` where a single `Run` is returned, but this is easily fixed

> have a known shared folder where we put the sampler's output_XX.csv files

This is a simple fix.  Is defaulting to a temp folder unless a path is provided ok?

**Comment by mitzimorris** [comment]
> This is a little shallow, in my opinion: the current Run class manages the "lifecycle" of the process of invoking the compiled executable, monitoring when it stops, ensures it isn't invoked while running, returns its CSV etc. RunSet is a container for Runs, but I don't think the implementation can be reduced further without causing headaches for users.

thanks for clarifying - agreed - RunSet wraps a list of Runs.

> The current RunSet class provides a convenience layer such that calling the summary explicitly isn't required, e.g. assert all(model.run(chains=4).R_hat < 1.1). I guess it's a little bit OO where you're going for array oriented.

I'd say it's a different OO design - it's a loose coupling between the model, the runset, and the posterior sample.

**Comment by monicayan** [comment]
> agreed - RunSet wraps a list of Runs.

Does `Runset` object wraps a list of `Run` objects? For my understanding, it only wraps the log data of `sample()` function (e.g. sampling parameters, output_file)

**Comment by maedoc** [comment]
The current implementation does, but its more of a implementation detail and isn’t in the spec (it doesn’t really affect usage).

**Comment by mitzimorris** [comment]
done as part of PR: https://github.com/stan-dev/cmdstanpy/pull/21
