### ISSUE TITLE
Unable to compile Stan model file

### ISSUE THREAD

**Issue by ArtemStrashko** [stan-dev/cmdstanpy#403]
#### Summary:
A similar issue as in #272, but the proposed solution doesn't seem to work in my case.

#### Description:
After installing CmdStanPy in a new environment following https://mc-stan.org/cmdstanpy/installation.html, 
i.e. `pip install --upgrade cmdstanpy[all]` and then `install_cmdstan`, in Jupyter notebook I run 
`import os`
`from cmdstanpy import cmdstan_path, CmdStanModel`
`bernoulli_stan = os.path.join(cmdstan_path(), 'examples', 'bernoulli', 'bernoulli.stan')`
`bernoulli_model = CmdStanModel(stan_file=bernoulli_stan)`

after which I get the following message:
```
INFO:cmdstanpy:compiling stan program, exe file: /Users/astrashko/.cmdstan/cmdstan-2.27.0/examples/bernoulli/bernoulli
INFO:cmdstanpy:compiler options: stanc_options=None, cpp_options=None
ERROR:cmdstanpy:file /Users/astrashko/.cmdstan/cmdstan-2.27.0/examples/bernoulli/bernoulli.stan, exception Command: ['make', '/Users/astrashko/.cmdstan/cmdstan-2.27.0/examples/bernoulli/bernoulli']
failed, returncode: 2, error: No such file or directory, stderr: clang-12: error: no such file or directory: 'stan/lib/stan_math/lib/tbb/libtbb.dylib'
clang-12: error: no such file or directory: 'stan/lib/stan_math/lib/tbb/libtbbmalloc.dylib'
clang-12: error: no such file or directory: 'stan/lib/stan_math/lib/tbb/libtbbmalloc_proxy.dylib'
make: *** [/Users/astrashko/.cmdstan/cmdstan-2.27.0/examples/bernoulli/bernoulli] Error 1 
ERROR:cmdstanpy:model compilation failed
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/7_/g_htm_814kl1d0z_7q115m5c0001h0/T/ipykernel_17526/1025654237.py in <module>
      3 
      4 # instantiate the model; compiles the Stan program as needed.
----> 5 bernoulli_model = CmdStanModel(stan_file=bernoulli_stan)
      6 
      7 # inspect model object

~/miniconda2/envs/Stan/lib/python3.9/site-packages/cmdstanpy/model.py in __init__(self, model_name, stan_file, exe_file, compile, stanc_options, cpp_options, logger)
    179             self.compile()
    180             if self._exe_file is None:
--> 181                 raise ValueError(
    182                     'Unable to compile Stan model file: {}.'.format(
    183                         self._stan_file

ValueError: Unable to compile Stan model file: /Users/astrashko/.cmdstan/cmdstan-2.27.0/examples/bernoulli/bernoulli.stan.
```

**Comment by mitzimorris** [comment]
what does the notebook say when you try to inspect the .cmdstan installation?
```
!ls ~/.cmdstan/cmdstan-2.27.0/stan
!ls ~/.cmdstan/cmdstan-2.27.0/stan/lib/stan_math/lib
```

**Comment by ArtemStrashko** [comment]
Thanks for a prompt reply. 

After running `!ls ~/.cmdstan/cmdstan-2.27.0/stan`, I get 
Jenkinsfile       RELEASE-NOTES.txt make              src
LICENSE.md        lib               makefile
README.md         licenses          runTests.py

After `!ls ~/.cmdstan/cmdstan-2.27.0/stan/lib/stan_math/lib`:
benchmark_1.5.1             tbb
boost_1.75.0                tbb_2020.3
cpplint_1.4.5               upgrade-boost.sh
eigen_3.3.9                 upgrade-google-benchmark.sh
opencl_2.2.0                upgrade-sundials.sh
sundials_5.7.0              upgrade-tbb.sh

**Comment by mitzimorris** [comment]
investigated - problem was user's `.bashrc` set $PATH environment variable to point to wrong toolchain.
closing issue.
