### ISSUE TITLE
Generalize `CmdStanMCMC.stan_variables` to CmdStanMLE, CmdStanVB, and CmdStanGQ

### ISSUE THREAD

**Issue by segasai** [stan-dev/cmdstanpy#405]
#### Summary:
The outputs of the MLE estimation cannot be easily used as inputs for sampling if some of the parameters are vectors/matrices

#### Description:
My model have many vector parameters and to save time, I always first run an MLE followed by sampling, i.e.
```
M = CmdStanModel('rvfit', 'rvfit.stan')
M.compile()
R = M.optimize(data=data,
                output_dir='tmp/',
                inits=dict(
                           lsigs=np.zeros(10) + 1.5)
                algorithm='BFGS',
                iter=10000,
                refresh=10)
init = QQ.optimized_params_dict
R1 = M.sample(data=data,
               inits=init.
               seed=6,
               chains=nchains,
               iter_warmup=5000,
               iter_sampling=5000,
               show_progress=True)
```
If I initialize the sampler with the params_dict directly it wil actually ignore all the vectors/arrays because all the vectors values are listed one by one with indices, while sample() obviously expects arrays

```
print (RR.optimized_params_dict)
Out[12]: 
OrderedDict([('lp__', -2530.56),
             ('vels[1]', -200.743),
             ('vels[2]', -178.027),
             ('vels[3]', -188.91),
             ('vels[4]', -193.634),
             ('vels[5]', -196.617),
```

So to be able to directly pass the outputs, I've had to parse the keys of optimized_params_dict and arrange them in arrays. Something like the code below. 
```
def convert_inits(x):
    ret = {}
    ret_arr = {}
    ret_notarr = {}
    for k, v in x.items():
        M = re.match(r'(.*)\[(\d+)\]', k)
        if M is not None:
            varname = M.group(1)
            if varname not in ret_arr:
                ret_arr[varname] = {}
            ret_arr[varname][int(M.group(2))] = (k, v)
        else:
            ret_notarr[k] = v
    for k, v in ret_notarr.items():
        ret[k] = v
    for k, v in ret_arr.items():
        npt = len(v)
        ids = list(v.keys())
        if npt == max(ids) and min(ids) == 1:
            curret = []
            for i in range(1, max(ids) + 1):
                curret.append(v[i][1])
            ret[k] = curret
        else:
            # something is off we just copy original
            for curv in v.values():
                ret[curv[0]] = curv[1]
    return ret
```

Dont you think that cmdstanpy should do that internally ?  (at least in pystan2 that was painless to reuse MLE output for initialization of MCMC) 
Or maybe we need an additional argument for the MLE result like
R.optimized_params_dict_array
that will be doing this merging of arrays.
I could try to provide a patch, if people think it's a good idea.

#### Additional Information:
Provide any additional information here.

#### Current Version:
0.9.76

**Comment by mitzimorris** [comment]
yes, this makes sense.   are you suggesting we should find ways to make this easier to do?  like export params as json so that they can be used as inits?

**Comment by segasai** [comment]
Yes, I think it should be indeed easier to use MLE output as inits.
What is the best way to implement this I am not 100% sure as I only recently switched to cmdstanpy from pystan, But my preferred way is to provide an additional attribute to the MLE result that return results as a dictionary with values being  properly shaped numpy arrays. 
I.e. something like {'x':1, 'y':np.array([2,3]), 'z':np.array([[2,3],[4,5]])}

**Comment by mitzimorris** [comment]
this isn't quite possible, but it should be.
right now, the CmdStanMLE object has method [`optimized_params_dict`](https://mc-stan.org/cmdstanpy/api.html#cmdstanpy.CmdStanMLE.optimized_params_dict)
but this won't do the right thing for container variables.

a while ago we added method `stan_variables` to the CmdStanMCMC object.
we need to do the same for the CmdStanMLE and CmdStanVB objects.
this is a very compelling use case, so we should do this.

**Comment by bob-carpenter** [comment]
+1 on making this easier.  It's really easy to do this in CmdStanR.  I've been doing this with either a max likelihood estimate (MLE) or a draw from an approximation variational posterior (ADVI).   For the MLE, you often need to define a different model because the MLE isn't defined for hierarchical models.  Or you'd at least need to cap number of iterations to get an implicitly regularized MLE.

**Comment by mitzimorris** [comment]
done in PRs https://github.com/stan-dev/cmdstanpy/pull/408 and  https://github.com/stan-dev/cmdstanpy/pull/413
