### ISSUE TITLE
method `sample` has parameter `validate_csv` - is this useful?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#407]
#### Summary:
Set up tests to profile performance to see whether or not
`validate_csv = False` makes any appreciable difference whatsoever.
If not, we should eliminate this option.  This will simplify logic in the CmdStanMCMC
methods.  Right now, there are checks all over the place, e.g.

```
if self._metadata is None:
            self.validate_csv_files()
```

If we always call validate_csv_files during initialization, the code would be much cleaner.

#### Description:
The CmdStanMCMC class processes the sample CSV output files in two stages:

 - `validate_csv` scans a set of CSV output files, makes sure that config and size and shape of the data are compatible.  by default, this is done during initialization.

 - `assemble_drawset` does a 2nd pass to get the draws and convert them from ascii csv to float.  this happens the first time that the user tries to access either the stepsize, metric, or draws.  this is not done automatically to save both memory and processing time.

The CmdStanModel method `sample` has boolean parameter:  `validate_csv`:

>  :param validate_csv: If ``False``, skip scan of sample csv output file.
>             When sample is large or disk i/o is slow, will speed up processing.
>             Default is ``True`` - sample csv files are scanned for completeness
>             and consistency.
> 

I'm not sure this is actually true or useful.  When the sample is large but disk i/o is good,
the scan reads the file line-by-line and most lines then undergo a `split` operation.
When the sample isn't large, even slow disk i/o is fine.
When the sample is large and disk i/o is slow, then the sampler run itself will be slow,
and the fraction of time spent validating the output CSV files might not be significant.
Likewise, for complex models, most of the time will be spent doing the sampling,
not validating the CSV files.

#### Additional Information:
Provide any additional information here.

**Comment by WardBrian** [comment]
Placing my comments here rather than in #408: I think it is entirely reasonable to remove this argument. When so many of the useful functions just end up calling `validate_csv_files` immediately anyway, it seems worthwhile to just call in the constructor. Even if there is a performance hit, which as you point out is dubious, I think it happening at initialization rather than at some semi-arbitrary point downstream when a method is called is for the best.

**Comment by mitzimorris** [comment]
incorporating this as part of #408
