### ISSUE TITLE
code cleanup - generate_quantities

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#409]
#### Summary:

Cleanup method `standalone_generate` and class `CmdStanGQ` so that we can naturally extend this to `stan_variables`

#### Description:

- refactor `CmdStanGQ` so that it has access to input metadata and input draws object - deprecate method `sample_plus_quantities`, method `stan_variable` should allow access to either input sample or generated quantities sample transparently; ditto method `stan_variables`

- `standalone_generate` does the work of `from_csv` - now that it's been added, we should call it instead -
replacing the following 30 lines or so of code: https://github.com/stan-dev/cmdstanpy/blob/90d86dc8c88d20dadd8b96ea816cee1bf1f2d006/cmdstanpy/model.py#L959-L989

**Comment by mitzimorris** [comment]
@jgabry and @rok-cesnovar  - when cmdstanr implements `stan_variables` - here's what I think would be simple and convenient for `CmdStanGQ` object.  what do y'all think?

**Comment by mitzimorris** [comment]
here is the decided on behavoir of CmdStan w/r/t samples which include warmup draws:  discussed here:  https://github.com/stan-dev/cmdstan/issues/1011#issuecomment-839419527

conclusion was as follows:

> draws in the fitted_params csv file will be used, all of them.
CmdStanPy will have to document this, and could also print info message to user that warmup draws are present.

checking whether or not CmdStanPy got around to doing this - I don't think so.   will add this as part of this refactor

**Comment by mitzimorris** [comment]
working through this refactor with the goal of harmonizing CmdStanMCMC and CmdStanGQ objects while not changing current (0.9.xxx) API for CmdStanGQ.

As currently implemented, CmdStanGQ assembles output for method `generate_quantities` into a 2D numpy array and exposes this via properties `generate_quantities` and `generate_quantities` pd.

We need to add methods to make it easy to interface to Arviz and handle implications of https://github.com/stan-dev/cmdstan/issues/1011#issuecomment-839419527.   I propose the following:

add methods `generate_quantities_draws` and `generate_quantities_draws_xr` (or `gq_draws` and `gq_draws_xr`). which have same signature as [`draws`](https://mc-stan.org/cmdstanpy/api.html#cmdstanpy.CmdStanMCMC.draws)   and [`draws_xr`](https://github.com/stan-dev/cmdstanpy/blob/c9d1c174b13127f593a62f310b10268d95dcd239/cmdstanpy/stanfit.py#L953-L955)

Branch https://github.com/stan-dev/cmdstanpy/tree/feature/409-stan-variables-standalone-gq adds methods `stan_variable` and `stan_variables` which have the same signature and behaviors as the CmdStanMCMC object,
including option `inc_warmup`

@ahartikainen  and @WardBrian - comments and/or suggestions?

**Comment by WardBrian** [comment]
This sounds good to me. I think it will make issues like https://github.com/arviz-devs/arviz/issues/1736 easier, and generally I think consistency in an API is incredibly useful

**Comment by mitzimorris** [comment]
OK, I think refactor is complete and ready for code review

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/413
