### ISSUE TITLE
windows install script or instructions for CmdStan

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#41]
#### Summary:

CmdStanPy requires a local install of CmdStan.  The environment variable `CMDSTAN` is used to specify the path to the CmdStan install.  If this variable isn't set, CmdStanPy uses default directory location `~/.cmdstanpy`.   The script `make_cmdstan.sh` downloads and compiles the latest release of CmdStan from GitHub.  By default it installs the latest version of CmdStan in the default directory.    Flags `-d` and  `-v` are used to specify the directory and version, respectively. 

Modify script `make_cmdstan.sh` as needed for Windows or create a Windows-appropriate install script or installer for CmdStan.

**Comment by ahartikainen** [comment]
This is a tricky one.

By default these are not installed

    sh
    tar

Symlinks are not a thing on Windows... at least they are not a thing we should be touching.

I personally use Cmder Full (https://cmder.net/) which has tar and sh installed by default. Also symlink works on W10, but it failed with too-long-path (some boost docs cause this on PyStan).

Then one option would be to do this with `batch`-file (`.bat`), but giving command line arguments is very tricky. The language is not great.

We could write this with powershell. That could maybe work.

I think our best option is to do this with python. With suitable commandline interface (https://click.palletsprojects.com/en/7.x/) we can create basically same experience as `make_cmdstan.sh` has on other systems.

With Python we could "stream" untar with https://docs.python.org/3/library/tarfile.html
It might be slower, but I have not yeat tested this.

So to tackle this with python we need

    tarfile
    request
    click
    subprocess
    os (`os.makedirs(....)`)
    shutil (maybe)

We can assume user has

    compiler (under `CC`/`CXX`?)
    make

**Comment by mitzimorris** [comment]
excellent suggestion -  of course install script should be written in python!
performance is not an issue here, so slower untar is fine.

we're using shutil already to do the cleanup on the TMPDIR.

**Comment by mitzimorris** [comment]
> Symlinks are not a thing on Windows... at least they are not a thing we should be touching.

OK, there are other ways to hack this.

**Comment by mitzimorris** [comment]
> Symlinks are not a thing on Windows... at least they are not a thing we should be touching.

agreed - symlinks are bad.   alternatives?

**Comment by mitzimorris** [comment]
the current logic for finding the install location:  https://github.com/stan-dev/cmdstanpy/blob/f1ae91622d27784526e6be2044398de999aa77a8/cmdstanpy/utils.py#L33-L44

the only thing that comes to mind is storing the version somewhere instead of making a symlink - a poor person's symlink.

**Comment by mitzimorris** [comment]
addressed by PR #45 - closing.
