### ISSUE TITLE
need utility function "stan_json" 

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#410]
#### Summary:
per discussion on Discourse:  https://discourse.mc-stan.org/t/various-observations-on-rstan-cmdstanr-pystan-and-cmdstanpy-after-teaching-with-all-in-parallel/23455/13

the utility function `jsondump` should be made public, w/ better name.

#### Description:

> I can’t comment on the internal data-file-writing functionality as it’s not in the API. It appears to call python json because it throws an error on numpy arrays in just the same way. It would be nice to have it available to all users. (I don’t know if “expose” is strictly the right term for that.) 

#### Additional Information:
Provide any additional information here.

**Comment by rok-cesnovar** [comment]
FWIW, cmdstanr exposes `write_stan_json`: https://mc-stan.org/cmdstanr/reference/write_stan_json.html

**Comment by WardBrian** [comment]
Do we need to change the functionality of the function at all, or just rename and expose it?

Do we want the same with `rdump`, or is that unnecessary?

**Comment by mitzimorris** [comment]
exposing this to users will require more checking the input data dictionary items and documenting allowed input types.
we should link documentation to this:  https://mc-stan.org/docs/2_27/cmdstan-guide/json.html

**Comment by rok-cesnovar** [comment]
CmdStanR does not use or handle `rdump`, except if a user supplies an existing rdump file to the `$sample()` call. The JSON reader is faster in CmdStan and there is no real reason to handle it. R has faster JSON readers/writers so no sense of duplicating work.

Thus I dont think CmdStanPy needs to add that.

**Comment by mitzimorris** [comment]
> Thus I dont think CmdStanPy needs to add that.

sounds good to me.  let's not expose rdump.
