### ISSUE TITLE
code cleanup - why do we have loggers as class attributes?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#415]
#### Summary:
Remove class attributes `logger` ~~and change calls `self._logger.info` etc. to `logging.info`~~ and instead use helper function `get_logger()`https://github.com/stan-dev/cmdstanpy/blob/5aac1d4c189e7d83839b463a7794a996f68370eb/cmdstanpy/utils.py#L45-L50

#### Description:
Some classes have logger attributes.  According to Python docs, better not to - cf.[ "Logging Cookbook"](https://docs.python.org/3/howto/logging-cookbook.html#using-loggers-as-attributes-in-a-class-or-passing-them-as-parameters):

> **Using loggers as attributes in a class or passing them as parameters**
> 
> While there might be unusual cases where you’ll need to do this, in general there is no point because loggers are singletons. Code can always access a given logger instance by name using logging.getLogger(name), so passing instances around and holding them as instance attributes is pointless. Note that in other languages such as Java and C#, loggers are often static class attributes. However, this pattern doesn’t make sense in Python, where the module (and not the class) is the unit of software decomposition.

**Comment by mitzimorris** [comment]
@ahartikainen and @WardBrian - is the above advice appropriate for CmdStanPy?

**Comment by WardBrian** [comment]
I am not 100% familiar with logging best practice, but I think you would then use `logger.getLogger('cmdstan').info(...)`, not `logging.info(...)`, as logging on the root logger is not as useful in general. I think this would be equivalent to what we do right now as default behavior, just perhaps a bit cleaner object model without having to pass around the logging object.

Not really a general remark, but worth noting that the way it is currently handled makes the output in [cmdstanjupyter](https://github.com/WardBrian/CmdStanJupyter) very simpler as I can pass a logger rather than having to mess with the cmdstan one. But it's far from necessary to do it this way (I can just call logger.getLogger('cmdstan') in that package as well).

**Comment by mitzimorris** [comment]
I like the idea of being able to call `logger.getLogger('cmdstan')` everywhere, and letting other packages do the same.

For other packages, how do we document this, and shouldn't name 'cmdstan' be 'cmdstanpy'?

**Comment by mitzimorris** [comment]
OK, now I see what's going on - we have function `get_logger`:  https://github.com/stan-dev/cmdstanpy/blob/5aac1d4c189e7d83839b463a7794a996f68370eb/cmdstanpy/utils.py#L45-L50


we should use this everywhere.

**Comment by WardBrian** [comment]
I think that the part of that function which enables logging by default is also technically against the standard advice, but it’s certainly a good idea regardless. 

But yes, you’re right about the name and how I think it should be implemented

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/413#pullrequestreview-720206358:

> Also, I think we should throw @functools.cache on utils.get_logger, that way we don't have to evaluate that if condition each and every call and the performance should be identical to what we were doing previously

**Comment by WardBrian** [comment]
To elaborate on this a bit, the cache would just mean that only the first call to this function would evaluate any code (including setting up the basic config if desired), and the following calls should just return the logger like it was a constant reference. This should mean that there's no extra evaluation compared to the present implementation (actually, even less). Without it, replacing all of the instances with `get_logger` calls would end up doing a lot more computation - generally a bad thing in logging
