### ISSUE TITLE
code cleanup - CmdStanMCMC and CmdStanGQ only store draws as ndarray, instantiate dataframe on demand

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#416]
#### Summary:
The rational for storing the draws array is that reading in CSV file data is slow.
Not sure there's a good reason for storing the corresponding pandas.DataFrame counterpart, is there?

#### Description:
Both CmdStanMCMC have CmdStanGQ try to cache both the numpy.ndarray and pandas.DataFrame objects.
It would be easier to only store the ndarray and instantiate and return a new dataframe as needed.

**Comment by WardBrian** [comment]
This seems reasonable to me - when implementing `draws_xr` I avoided caching the result for a couple reasons, both the ones you mention here and to avoid tighter coupling with an optional dependency
