### ISSUE TITLE
[1.0 Release] List of expiring deprecations

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/cmdstanpy#430]
This issue mainly serves to document what features are currently marked as deprecated for removal in the eventual 1.0 release of CmdStanPy.

* Deprecated keyword arguments
    * CmdStanMCMC.draws_pd: `params` deprecated in favor of `vars`
    * CmdStanMCMC.stan_variable, CmdStanMLE.stan_variable, CmdStanGQ.stan_variable, and CmdStanVB.stan_variable: `name` deprecated in favor of `var`
    * Logger parameters: CmdStanArgs, CompilerOptions, CmdStanModel, RunSet, and CmdStanMCMC all accept a `logger` parameter that has been ignored since #419 
* Deprecated properties: 
    * CmdStanMCMC:  .sample, .stan_vars_dims, .stan_vars_cols, .sampler_vars_cols, .warmup
    * CmdStanGQ: .generated_quantities, .generated_quantities_pd, .sample_plus_quantities
* Deprecated methods:
    * CmdStanMCMC: .sampler_variables()
* General:
    * Usages of ~/.cmdstanpy have been deprecated, ~/.cmdstan is the way forward

**Comment by mitzimorris** [comment]
thanks for documenting this
