### ISSUE TITLE
Is there a typo in the documentation for installing from GitHub

### ISSUE THREAD

**Issue by docsteveharris** [stan-dev/cmdstanpy#434]
#### Summary:
When I try installing as per the instructions [here](https://cmdstanpy.readthedocs.io/en/v0.9.76/installation.html#install-package-cmdstanpy):

```bash
pip install -e git+https://github.com/stan-dev/cmdstanpy@/develop
```

I get an error
```bash
ERROR: Could not detect requirement name for 'git+https://github.com/stan-dev/cmdstanpy@/develop', please specify one with #egg=your_package_name
```

#### Additional Information:
I got this to work by doing the following instead

```bash
pip install -e git+https://github.com/stan-dev/cmdstanpy@develop#egg=cmdstanpy
```

#### Current Version:
cmdstanpy-0.9.76

**Comment by mitzimorris** [comment]
fixed as part of docs updates - #432
