### ISSUE TITLE
Create GitHub Actions workflow for conda installation

### ISSUE THREAD

**Issue by gibsramen** [stan-dev/cmdstanpy#437]
#### Summary:

With #420 and the new `conda` recipes I think it would be useful to add a GitHub actions workflow ensuring this installation method works as intended with the CmdStan installation, unit tests, etc.

#### Description:

The current `main.yml` uses only `pip` - a `conda` version could catch bugs related to `conda` installations that may not arise with `pip`. I've used https://github.com/conda-incubator/setup-miniconda and it's worked well for me in the past.

**Comment by WardBrian** [comment]
This is handled by the CI at https://github.com/conda-forge/cmdstan-feedstock for the most part. It doesn't run the full unit tests, but it does run the example model to ensure everything compiles and runs whenever cmdstan changes.
