### ISSUE TITLE
Use universal names in example

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#446]
#### Summary:

Hi, could we go with `model` and `fit` names in the example on the readme?

#### Description:

I would just want to copy and paste the example code and then just change small amount of rows so that I can easily run my code.

#### Additional Information:

```
import os
from cmdstanpy import cmdstan_path, CmdStanModel

# specify locations of Stan program file and data
stan_file = os.path.join(cmdstan_path(), 'examples', 'bernoulli', 'bernoulli.stan')
data_file = os.path.join(cmdstan_path(), 'examples', 'bernoulli', 'bernoulli.data.json')

# instantiate a model; compiles the Stan program by default
model = CmdStanModel(stan_file=stan_file)

# obtain a posterior sample from the model conditioned on the data
fit = model.sample(chains=4, data=data_file)

# summarize the results (wraps CmdStan `bin/stansummary`):
fit.summary()
```

#### Current Version:

Github

**Comment by mitzimorris** [comment]
entirely reasonable.  we should do this as much as possible everywhere in the docs and notebooks.

suggestion: if we have situations where there's two models, or doing multiple runs of the inference engine, then
objects should have prefix "fit" and "model" and descriptive suffix.
