### ISSUE TITLE
unexpected output for parameter matrices

### ISSUE THREAD

**Issue by dharris10-chwy** [stan-dev/cmdstanpy#455]
#### Summary:

When I was using cmdstanpy to read a parameter matrix from CSV, it put the values in an unexpected order. In Numpy terms, I think that the data was being read in "c order" when it should be read in "fortran order".

Thanks in advance for taking a look at this!

#### Description:

Below, I've included a small Stan program that should output a matrix whose values match their row number.  So the first row should be all 1's, the second row should be all 2's, etc.

The stan CSV output looks correct to me: Each entry of `x` lines up with its corresponding row number. I've aligned the output below to make this easier to confirm visually.

```
lp__ ,x.1.1 ,x.2.1 ,x.3.1 ,x.4.1 ,x.1.2 ,x.2.2 ,x.3.2 ,x.4.2 ,x.1.3 ,x.2.3 ,x.3.3 ,x.4.3
0    ,  1     ,2     ,3     ,4     ,1     ,2     ,3     ,4     ,1     ,2     ,3     ,4
```

However, when I read this data in with cmdstanpy, I see this output:

```
array([[1., 2., 3.],
       [4., 1., 2.],
       [3., 4., 1.],
       [2., 3., 4.]])
```

I think that cmdstanpy could get the expected output by [telling Numpy to expect the numbers to be in Fortran's preferred ordering](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) with `order=F`. For this example, the code might look like this:

`np.array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]).reshape(4, 3, order = "F")`

#### Additional Information:

Stan code, saved as `weird.stan`:

```
transformed parameters {
    matrix[4, 3] x;
    for (row_num in 1:4) {
        for (col_num in 1:3) {
            x[row_num, col_num] = row_num;
        }
    }
}
```

Python code: 

```python
from cmdstanpy import CmdStanModel

model = CmdStanModel(stan_file="weird.stan")
fit = model.optimize()
print(fit.stan_variable("x"))
```

#### Current Version:
stanc3 v2.27.0

**Comment by mitzimorris** [comment]
> was using cmdstanpy to read a parameter matrix from CSV

how exactly were you doing this?

**Comment by dharris10-chwy** [comment]
The included python code provides a minimal reproducible example. I get the same results if I use cmdstsanpy.from_csv, though.

From: Mitzi Morris ***@***.***>
Date: Wednesday, September 8, 2021 at 3:20 PM
To: stan-dev/cmdstanpy ***@***.***>
Cc: David Harris ***@***.***>, Author ***@***.***>
Subject: Re: [stan-dev/cmdstanpy] unexpected output for parameter matrices (#455)

was using cmdstanpy to read a parameter matrix from CSV

how exactly were you doing this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://protect-us.mimecast.com/s/jj0bCW60v0HNJLyAU6pA0e?domain=github.com>, or unsubscribe<https://protect-us.mimecast.com/s/PgeVCXDlwlCkwPMxHVqqJu?domain=github.com>.
Triage notifications on the go with GitHub Mobile for iOS<https://protect-us.mimecast.com/s/TCfnCYEmxmujrW6zS9wLnM?domain=apps.apple.com> or Android<https://protect-us.mimecast.com/s/NejWCZ6nynHXJqo3HyPYcg?domain=play.google.com>.

**Comment by mitzimorris** [comment]
two things:

- the Stan io JSON parser assumes that its input is in row major format, which it converts internally to column major.
- CmdStanPy's `stan_variable` and `stan_variables` functions will return variables with the correct shape, so if you can extract the parameter variable's value as a matrix and dump it to JSON, it should work.

**Comment by mitzimorris** [comment]
OK, now I understand - this is really weird and I thought we had unit tests to check this.  thanks, will investigate.

**Comment by mitzimorris** [comment]
which version of cmdstanpy?

**Comment by ahartikainen** [comment]
I tried the example code and this is the output

```
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]
```

**Comment by dharris10-chwy** [comment]
I just recreated my example and confirmed. I'm on `0.9.77`, which I believe is the newest release.

**Comment by WardBrian** [comment]
My machine outputs correctly for the given code:

```
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]
```

This is very odd. Can we get some information about the system you're using (OS, etc) and any other packages (the output of something like `pip freeze`)?

**Comment by mitzimorris** [comment]
> However, when I read this data in with cmdstanpy, I see this output:

how are you reading the CSV data into Python?
you'll notice that the CSV output have the columns labelled column major, but the CSV reader is probably reading it in row major, unless you do the right thing by the CSV file.

**Comment by dharris10-chwy** [comment]
@mitzimorris In the example above, I use `fit.stan_variable()` to access the data. I get the same results if I use `cmdstsanpy.from_csv()`, though.

@WardBrian: I'm using the `python:3.9.6-buster` Docker image, so it's Debian Linux. I've included my `requirements.txt` and `pip freeze` below.

requirements.txt:

```
numpy==1.21.1
pandas==1.3.1
pyarrow==5.0.0
scipy==1.7.1
boto3==1.18.17
cmdstanpy
pytest==6.2.1
hypothesis==5.33.2
ipykernel
ipython==7.19.0
pre-commit==2.4.0
black==20.8b1
flake8==3.8.4
mypy==0.910
```

pip freeze: 

```
appdirs==1.4.4
attrs==21.2.0
backcall==0.2.0
backports.entry-points-selectable==1.1.0
black==20.8b1
boto3==1.18.17
botocore==1.21.37
cfgv==3.3.1
click==8.0.1
cmdstanpy==0.9.77
decorator==5.0.9
distlib==0.3.2
entrypoints==0.3
filelock==3.0.12
flake8==3.8.4
hypothesis==5.33.2
identify==2.2.13
iniconfig==1.1.1
ipykernel==5.5.5
ipython==7.19.0
ipython-genutils==0.2.0
jedi==0.18.0
jmespath==0.10.0
jupyter-client==7.0.2
jupyter-core==4.7.1
matplotlib-inline==0.1.3
mccabe==0.6.1
mypy==0.910
mypy-extensions==0.4.3
nest-asyncio==1.5.1
nodeenv==1.6.0
numpy==1.21.1
packaging==21.0
pandas==1.3.1
parso==0.8.2
pathspec==0.9.0
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==2.3.0
pluggy==0.13.1
pre-commit==2.4.0
prompt-toolkit==3.0.20
ptyprocess==0.7.0
py==1.10.0
pyarrow==5.0.0
pycodestyle==2.6.0
pyflakes==2.2.0
Pygments==2.10.0
pyparsing==2.4.7
pytest==6.2.1
python-dateutil==2.8.2
pytz==2021.1
PyYAML==5.4.1
pyzmq==22.2.1
regex==2021.8.28
s3transfer==0.5.0
scipy==1.7.1
six==1.16.0
sortedcontainers==2.4.0
toml==0.10.2
tornado==6.1
traitlets==5.1.0
typed-ast==1.4.3
typing-extensions==3.10.0.2
ujson==4.1.0
urllib3==1.26.6
virtualenv==20.7.2
wcwidth==0.2.5
```

**Comment by WardBrian** [comment]
Recreating your environment makes the problem pop up for me. I'll try to run it down, see if its us or a numpy change etc

**Comment by ahartikainen** [comment]
Ok, tested against pypi version and the problem can be replicated

```
[[1. 2. 3.]
 [4. 1. 2.]
 [3. 4. 1.]
 [2. 3. 4.]]
```

**Comment by WardBrian** [comment]
Strange, I guess #281 fixed this unintentionally? It works properly in 0.9.77 with `.sample` and works on `develop`

**Comment by ahartikainen** [comment]
Ok, you can compare these two lines

develop

```
if len(col_idxs) > 0:  # container var
            dims = (num_rows,) + self._metadata.stan_vars_dims[var]
            # pylint: disable=redundant-keyword-arg
            if num_rows > 1:
                result = self._all_iters[:, col_idxs].reshape(  # type: ignore
                    dims, order='F'
                )
            else:
                mle = np.expand_dims(self._mle, axis=0)  # hack for col indexing
                result = (
                    mle[0, col_idxs]
                    .reshape(dims, order='F')  # type: ignore
                    .squeeze(axis=0)
                )
        else:  # scalar var
            if num_rows > 1:
                result = self._all_iters[:, col_idxs]
            else:
                result = np.atleast_1d(mle[0, col_idxs])

        assert isinstance(result, np.ndarray)  # make the typechecker happy
        return result
```
0.9.77

```return np.array(xs).reshape(shape)```

https://github.com/stan-dev/cmdstanpy/blob/f237e8d518785f9046e4911bac42b1caa6019893/cmdstanpy/stanfit.py#L1333

Btw, we need to check other interfaces too (vb etc), I think  they still have the reshape bug.

**Comment by mitzimorris** [comment]
doh!!! sorry for being stupid - yes handling of optimizer output was doing the wrong thing, and now better.

**Comment by WardBrian** [comment]
Do we think this will affect the other methods/do we test for this?

**Comment by mitzimorris** [comment]
optimize and variational provide a point estimate - CSV file has single row of estimates.
sample and generate_quantities provide a sample,
but I will check for the case where the output contains only a single iteration, which is something folks might do.

**Comment by ahartikainen** [comment]
All interface are affected even when there is one row of data

e.g. in the csv file one row

    1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4

needs to be reshaped to a matrix shape. Sure there is no draw dimension needed.

**Comment by mitzimorris** [comment]
I lost several hours to understanding what numpy does w/r/t ndarrays that only have a single row, and it was frustrating - if I say I have an ndarray of shape (1, 10), I mean it - if I wanted an array, I would say so.  (but no more frustrating than R).

**Comment by ahartikainen** [comment]
Yeah, numpy doesn't really work with column / row vector "space". You can always create them, but in numpy 1D is still 1D. This is hard if one does matrix calculus. Not that hard if one doesn't do matrix calculus :D.

**Comment by mitzimorris** [comment]
> Stan code, saved as `weird.stan`:
> 
> ```
> transformed parameters {
>     matrix[4, 3] x;
>     for (row_num in 1:4) {
>         for (col_num in 1:3) {
>             x[row_num, col_num] = row_num;
>         }
>     }
> }
> ```

clever example - thanks!

**Comment by mitzimorris** [comment]
not a problem for sampler output adding model to test/data dir as `matrix_param.stan` -
```
test_dir = os.path.join('test', 'data')
stan_file = os.path.join(test_dir, 'matrix_param.stan')
model = CmdStanModel(stan_file=stan_file)
fit=model.sample(chains=1, iter_sampling=1)
fit.stan_variable("x")
```
result:
```
array([[[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]]])
```

**Comment by dharris10-chwy** [comment]
Thanks all of you for being so responsive. I really appreciate it.

Has there been any investigation into whether it would make sense for cmdstan itself to do some of this work so that it didn't have to be replicated (and tested) across all of the different interfaces? For example, maybe it could save each row of samples as a line of json instead of csv.

**Comment by mitzimorris** [comment]
short answer:  no
also,  per-draw JSON is hugely redundant

**Comment by WardBrian** [comment]
To add on: The problem with something like JSON is it's not streaming (i.e. building up a json file line by line leaves an invalid state until the final line closes the `{}` pair), which is one of the big advantages of these csv files - you can inspect them mid-run for something like MCMC which generates a lot of draws. You could avoid this by having each 'row' or draw being it's own json-style object, but then you're duplicating things like the column headers 4000+ times and actually reading it all in becomes even more of a hassle

**Comment by dharris10-chwy** [comment]
Yeah, that does sound like a very bad idea, now that you point it out.

**Comment by mitzimorris** [comment]
testing behavoir everywhere including generate quantities - looks like there's a bug in `CmdStanGQ.stan_variable` somewhere.  will fix along with this bug.
