### ISSUE TITLE
investigate whether or not `make` works on all supported platforms.

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#47]
#### Summary:

On some systems make is not called make. 
Investigate ways for users to set up their environment to deal with this.

#### Description:
see discussion here: https://github.com/stan-dev/cmdstanpy/pull/45#discussion_r291842496

**Comment by mitzimorris** [comment]
we need to find users in this situation to help test.

**Comment by ahartikainen** [comment]
`MAKE` env var can be used now. There is also set_make_env function.

**Comment by mitzimorris** [comment]
closing since we now have the install toolchain functions.
