### ISSUE TITLE
Feature / Run CmdStan in background

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#48]
#### Summary:

Start sampling, stop python; ... start python, get progress or read csv files

#### Description:

It could be helpful to have possibility to start cmdstan sampling to background and then later get the csv (or use some other interface).

#### Additional Information:

Similar interface as

    nohup model sample output.csv  > sample.log &

**Comment by maedoc** [comment]
would it be ok to
```
nohup python -m cmdstanpy.run model sample output.csv --log sample.log &
```
? quitting Python means serialized state to file e.g. pid file, and it seems a large overhead in terms of code, vs small cost of a Python process in background waiting for CmdStan executable to finish.

**Comment by WardBrian** [comment]
I realize this issue is old, but is this need resolved by using `from_csv` now?

**Comment by ahartikainen** [comment]
I wonder if there is a possibility we add `nohup` (or whatever is the correct way to do this for each platform) interface?

Maybe some special function that kind of calls `model.sample` (or whatever) and then when the return is empty --> crash (?) -> return None for user? Of course this would mean that the special function needs to have explicit location the output.

Then it is up to the user collect csv files when ready.

**Comment by WardBrian** [comment]
I'm not sure I follow what the use case is for this, really. Are you suggesting we make a version of `sample()` that is async?

**Comment by ahartikainen** [comment]
The nohup stuff is something I have done while starting sampling in servers over ssh which take a long time.

**Comment by ahartikainen** [comment]
But on the other hand, one could always create a python script and manually call that with nohup.

**Comment by WardBrian** [comment]
Is there any problem with using `nohup python my_script.py`?

**Comment by ahartikainen** [comment]
Probably not. maybe we should close this issue
