### ISSUE TITLE
function `sample` argument `inits` should allow initialization function

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#49]
#### Summary:
The `sample` command `inits` is used to specify some or all initial parameter values.

Add functionality as in [RStan](https://mc-stan.org/rstan/reference/stan.html):
> Set initial values by providing a function that returns a ~list~ Dict for specifying the initial values of parameters for a chain. The function can take an optional parameter chain_id through which the chain_id (if specified) or the integers from 1 to chains will be supplied to the function for generating initial values.

**Comment by ahartikainen** [comment]
In python R list --> dict

**Comment by mitzimorris** [comment]
right - sloppy cut and paste - will edit accordingly.

**Comment by MatsuuraKentaro** [comment]
I have a small comment, the argument name may be `init` instead of `inits` because rstan, pystan and cmdstanr use `init`.

**Comment by WardBrian** [comment]
See discussion in #324
