### ISSUE TITLE
investigate model compile method argument `force` - needs to do more somehow.

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#494]
#### Summary:
When model compile method `force=True`, model doesn't get recompiled if exe is newer than source file because GNU-Make is there to do this.  

#### Description:
We use makefile vars to set options, but these are ignored is the exe file exists:

here we compile ` bernoulli.stan` with no options:
```
~/.cmdstan/cmdstan-2.28.1> ./examples/bernoulli/bernoulli info
stan_version_major = 2
stan_version_minor = 28
stan_version_patch = 1
STAN_THREADS=false
STAN_MPI=false
STAN_OPENCL=false
STAN_NO_RANGE_CHECKS=false
STAN_CPP_OPTIMS=false
```
then we tell `make` to compile in order to add an option:
```
~/.cmdstan/cmdstan-2.28.1> make STAN_NO_RANGE_CHECKS=T examples/bernoulli/bernoulli
make: `examples/bernoulli/bernoulli' is up to date.
```

Therefore, the `compile` command needs to do extra work - updating the timestamp on the Stan src file should do the trick.

**Comment by WardBrian** [comment]
Why doesn’t removing the exe file suffice?

**Comment by mitzimorris** [comment]
that would work too.

**Comment by WardBrian** [comment]
Correct, we should delete both the .hpp file and executable. It's a minor quibble, but IMO mucking with the edited time on the `.stan` file feels overly invasive to me (especially if someone is ever trying to solve the "wait, which model did I write when?" workflow problem using said timestamps)

**Comment by WardBrian** [comment]
Do you want me to take this one?

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/496
