### ISSUE TITLE
Possible bug: reshaping of array of vectors in `optimize`

### ISSUE THREAD

**Issue by tillahoffmann** [stan-dev/cmdstanpy#498]
#### Summary:

I have observed some unexpected behaviour when using the `optimize` method for parameters that are arrays of vectors. Is this a bug or am I using it wrong?

#### Description:

Consider the following model simple model. It draws `n` random vectors from `p`-dimensional unit-variance normal distributions with a given mean. 

```stan
// debug_model.stan

data {
    int n;  // number of vectors
    int p;  // number of dimensions for each vector
    vector[p] locs[n];  // locations of the normals
}

parameters {
    vector[p] x[n];
}

model {
    for (i in 1:n) {
        x[i] ~ normal(locs[i], 1);
    }
    print("x1 is ", x[1]);  // log the value for debugging
}
```

What I would expect to see from running `optimize` is that `fit.stan_variable['x']` matches the `locs` provided as data. However, it seems that the output is not reshaped correctly. Let's first set up the data (all run in ipython).

```python
>>> n = 3
>>> p = 2
>>> locs = np.reshape(np.arange(n * p), (n, p))
>>> data = {'n': n, 'p': p, 'locs': locs}
>>> locs  # Show the expected MLE
array([[0, 1],
       [2, 3],
       [4, 5]])
```

Running the optimisation and obtaining the best estimate yields the correct estimates but in the wrong order.

```python
>>> model = cmdstanpy.CmdStanModel(stan_file='debug_model.stan')
>>> mle = model.optimize(data, seed=0)
>>> np.round(mle.stan_variable('x'), 15)  # round to 15 decimals for nicer display
array([[0., 2.],
       [4., 1.],
       [3., 5.]])
```

But we logged the value of `x[1]` in the stan program so can compare with what stan "sees" internally.

```python
>>> filename, = mle.runset.stdout_files
>>> ! grep $filename -e 'x1 is'
x1 is [-0.384764,0.00591807]
x1 is [-0.384764,0.00591807]
x1 is [-0.384764,0.00591807]
x1 is [-0.384379,0.00691215]
x1 is [-0.380916,0.0158589]
x1 is [-0.346287,0.105326]
x1 is [5.55112e-17,1]
```

So it seems like stan internally does what's expected but that cmdstanpy somehow gets confused about the order of the parameter values.

However, this works as expected when we run `sample` instead of `optimize`:

```python
>>> fit = model.sample(data=data, seed=0)
>>> fit.stan_variable('x').mean(axis=0)
array([[-0.00707148,  0.98821361],
       [ 1.99643607,  3.00865085],
       [ 4.00740782,  4.99579036]])
```

#### Additional Information:

- cmdstanpy version: 0.9.77
- cmdstan version: 2.28.1
- python version: 3.8.10
- numpy version: 1.21.3
- reproducible notebook here: https://gist.github.com/tillahoffmann/7b6a86c9745b8b80148bd63407ad47c2
- #455 may be related

**Comment by WardBrian** [comment]
Are you able to try on the develop branch? I think #455 was patched after the release of 0.9.77, but I could be misremembering

If not I can try tomorrow

Thanks for reporting!

**Comment by tillahoffmann** [comment]
#455 indeed fixes it. Should've tried `develop` first. Thanks for the quick response.

**Comment by WardBrian** [comment]
No worries, we’d much rather get false alarms than no reports, so thanks for putting together such a thorough issue!
