### ISSUE TITLE
Regression in `install_cmdstan` from 0.9.77 to develop

### ISSUE THREAD

**Issue by tillahoffmann** [stan-dev/cmdstanpy#499]
#### Summary:

Running `install_cmdstan` from the `develop` branch raises 

```python
Traceback (most recent call last):
  File "/usr/local/bin/install_cmdstan", line 8, in <module>
    sys.exit(main())
TypeError: main() missing 1 required positional argument: 'args'
```

#### Description:

Running `install_cmdstan` works as expected for `0.9.77`.

```bash
$ docker run --rm -it python:3.8 bash -c 'pip install cmdstanpy==0.9.77 && install_cmdstan -h'
[help message]
```

But it fails for the `develop` branch (and similarly for the `1.0.0rc2` on pypi).

```bash
$ docker run --rm -it python:3.8 bash -c 'pip install git+https://github.com/stan-dev/cmdstanpy && install_cmdstan -h'
[TypeError, see details above]
```

**Edit**: fixed a few typos.

**Comment by WardBrian** [comment]
`python -m cmdstanpy.install_cmdstan -h` seems to work just fine, the issue is with `setup.py`

**Comment by tillahoffmann** [comment]
I've had a little dig into the `setup.py`. Will send a patch shortly.

**Comment by WardBrian** [comment]
I think we could just add an `def entry(): main(parse_cmdline_args())` and then point to that instead of main? Not sure if there is a better way to do args.

This also affects install_cxx_toolchain in the same way
