### ISSUE TITLE
examples for conda?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#503]
#### Summary:
help out prophet team - https://github.com/facebook/prophet/issues/2041

>Do you have any examples of other packages using cmdstanpy on conda btw? It'll save me some time -- if not, all good.

**Comment by WardBrian** [comment]
From `$ conda depgraph --from-channels in cmdstan`:

```
  ┌─────────┐  ┌───────────┐   
  │nevergrad│  │u8darts-all│   
  └─┬───────┘  └─────┬─────┘   
    │                │         
    │   ┌────────────┘         
    │   │                      
    v   v                      
 ┌───────┐ ┌──────────────────┐
 │prophet│ │salesforce-merlion│
 └───┬───┘ └─────┬────────────┘
     │           │             
     └────────┐  │             
              │  │             
              v  v             
          ┌─────────┐          
          │cmdstanpy│          
          └────┬────┘          
               │               
               v               
           ┌───────┐           
           │cmdstan│           
           └───────┘           

```

It seems that salesforce-merlion is using fbprophet itself: https://github.com/conda-forge/salesforce-merlion-feedstock/blob/master/recipe/meta.yaml

**Comment by WardBrian** [comment]
I've been helping them out (https://github.com/conda-forge/prophet-feedstock/pull/21); I think we can close this
