### ISSUE TITLE
Failed compilation leaves process cwd in CmdStan folder

### ISSUE THREAD

**Issue by maedoc** [stan-dev/cmdstanpy#506]
#### Summary:
A failing compilation leaves the cwd in the CmdStan folder.

#### Description:
The [`do_command`](https://github.com/stan-dev/cmdstanpy/blob/0b50ae9a8bfdbe011cc9eb258a6f2477d7aefc90/cmdstanpy/utils.py#L1006) function uses a context manager which doesn't seem to restore the previous working directory, when a compilation failure occurs.

#### Additional Information:
The `pushd` context manager probably needs to catch the exception, restore the working directory and then re-raise the exception.

#### Current Version:
cmdstanpy-1.0.0

**Comment by WardBrian** [comment]
Closed by #507
