### ISSUE TITLE
Configure “algorithm=fixed_param” in new API

### ISSUE THREAD

**Issue by rndpolytope** [stan-dev/cmdstanpy#51]
#### Summary:
It seems not an option to configure algorithm=fixed_param in the new API.
In the old API, this is done by using [keyword argument](https://gitlab.thevirtualbrain.org/tvb/pycmdstan/blob/master/pycmdstan/model.py#L141). However, this is not an option as in the [new model class](https://github.com/stan-dev/cmdstanpy/blob/master/cmdstanpy/lib.py#L242).

#### Current Version:
Newest commit as of Jun 18.

**Comment by bob-carpenter** [comment]
I don't know if there's a roadmap doc anywhere, but the short version is that we're starting with NUTS and then moving on to the other algorithms.  They're not going to be configured the same way with one monolithic command, but all the useful ones like fixed parameters, variational inference, and optimization will eventually get added.  We probably won't add vanilla (static) HMC.

**Comment by rndpolytope** [comment]
Thanks, Bob.
