### ISSUE TITLE
Feature: write stan file from python.

### ISSUE THREAD

**Issue by tillahoffmann** [stan-dev/cmdstanpy#513]
Would there be interest in adding a convenience function to write a temporary stan file from python (happy to create a PR if so)? I've found this functionality useful for model iteration without modifying external files. In particular, I've been using the following snippet which

- computes the hash of the code
- writes the code to a hash-based filename in a given directory (defaults to the `models` subdirectory of the `cmdstanpy` directory)
- returns the path

```python
import cmdstanpy
import hashlib
import os


def write_stanfile(code: str, directory: str = None) -> str:
    """
    Write the model code to a file and return the path based on the code hash.

    Args:
        code: Code to write to a file.
        directory: Directory to write the code to (defaults to the cmdstanpy models directory).

    Returns:
        path: Path to the file containing the code.
    """
    # Generate the path based on the code and check whether it already exists.
    directory = directory or os.path.join(cmdstanpy.cmdstan_path(), 'models')
    digest = hashlib.sha256(code.encode()).hexdigest()
    stan_file = os.path.join(directory, f'{digest}.stan')
    if os.path.isfile(stan_file):
        return stan_file

    # Write the file to disk.
    os.makedirs(directory, exist_ok=True)
    with open(stan_file, 'w') as fp:
        fp.write(code)
    return stan_file
```

The function can be used like so

```python
model = cmdstanpy.CmdStanModel(stan_file=write_stanfile('[MODEL CODE HERE]'))
```

**Comment by mitzimorris** [comment]
I understand the use case, but I think that it opens the door to really really bad development practices.
this comes up frequently so if you put this somewhere as a gist, it would make a lot of people very happy.
I would prefer not to add this to the API.

**Comment by mitzimorris** [comment]
the Jupyter notebook stuff is nice, but it's equally dangerous.  I like Jupyter notebooks and use them alot.  I'm continually running some cells in a notebook out of order.  it's a scratch pad, and it can get saved in states that aren't at all consistent.  this becomes problematic when you go back to a notebook later and it doesn't work.

I realize that everyone works differently, and people have asked for this, so if there's consensus that this would do more good than harm, then it should be added.

**Comment by WardBrian** [comment]
I suspect part of the reason it's requested is I believe this is the default way of working in RStan and pystan. 

I think it is worth being cautious about, for the reasons you suggest, but there are also scenarios where it's useful

**Comment by tillahoffmann** [comment]
> the Jupyter notebook stuff is nice, but it's equally dangerous.

Yes, agreed that this sort of functionality *should* only be used for early experimentation rather than developing reproducible inference pipelines. Having said that, sometimes one just needs something quick and dirty.
