### ISSUE TITLE
Release 2.28.2 is unavailable from URL...

### ISSUE THREAD

**Issue by probit2011** [stan-dev/cmdstanpy#514]
#### Summary:
I am trying to complete the installation of the most recent version of CmdStanPy according to the instructions as listed here (https://mc-stan.org/cmdstanpy/installation.html). Both methods available for Linux environments fail.

#### Description:
I tried to complete the installation with the Python method and I obtained the following error message:

![cmdstanisunavailable](https://user-images.githubusercontent.com/44330046/149266308-5d6d42b4-7f1d-49e0-b7d2-13794f347ca1.png)

I checked the cmdstan github site, and this should be the correct version AND the correct address.

I then tried with the command line method and I obtained the following error message:

![cmdstancommandline](https://user-images.githubusercontent.com/44330046/149266377-9ba1e148-16c0-42ae-99c7-e9f0d5f7638d.png)

#### Additional Information:
My OS is Ubuntu 20.04. The Python install was attempted using IPython within Spyder 4.2.5 with Python 3.8.

**Comment by WardBrian** [comment]
I think Github may have had some uptime issues yesterday, could you try again in Python?

The command line issue you've noticed was #499

**Comment by probit2011** [comment]
I tried again in Python, same result.

I also tried the command line used in #499 but I obtained the following error message:

![cmdstancmdline](https://user-images.githubusercontent.com/44330046/149420707-ef39cad3-45a8-49d3-86d1-1f458d9d6b8b.png)

**Comment by ahartikainen** [comment]
That is just a warning.

Are you behind company network?

**Comment by probit2011** [comment]
Yes.

**Comment by ahartikainen** [comment]
There is a small probability that github is blocked by your network.

Is there a possibility to use conda?
You can always install CmdStan manually

Create a folder /home/.cmdstan/ and install CmdStan there (I will need to check what should be the correct folder name)

**Comment by probit2011** [comment]
Yes, I can use conda. What would be the correct command(s)?

**Comment by probit2011** [comment]
It looks like it worked this time. Thanks

**Comment by mitzimorris** [comment]
is there something we can do here to make this easier for others?     troubleshooting section of the docs?

**Comment by ahartikainen** [comment]
If we can make it so that user can manually download the tar and install it if found (check hash) then the company people have option other than conda.

Not sure if we can detect this any way.

**Comment by mitzimorris** [comment]
is the best we can do putting in the docs that firewalls are a potential problem, and listing workarounds?

**Comment by WardBrian** [comment]
I think we should just try to make the error message cmdstanpy outputs better. Currently it seems to complain that the version doesn’t exist when the download fails, which is obviously confusing when the version does exist. We should instead say something like “Version x.x cannot be downloaded. Connection to GitHub failed, check firewall settings or try with an existing version”
