### ISSUE TITLE
CmdStanModel automatically changes root logging level

### ISSUE THREAD

**Issue by gibsramen** [stan-dev/cmdstanpy#522]
#### Summary:

When initializing a CmdStanModel, the default root level of `logging` changes from `WARNING -> INFO`.

#### Description:

I believe this is because of this line which sets the root level to `INFO`. 

https://github.com/stan-dev/cmdstanpy/blob/a40b6a185163299f37d9d503fd3b10c33330304e/cmdstanpy/utils.py#L54

This caused me an issue in an application where I implemented other loggers and the outputs were not what I expected.

<details open>
<summary>Code to reproduce</summary>
<br>

```python
import logging
import os

from cmdstanpy import cmdstan_path, CmdStanModel

my_logger = logging.getLogger("mylogger")
print("======================================")
print(f"Root logging level: {logging.root.level}")
print("======================================")
my_logger.info("TEST_1")  # Is not logged (root is WARNING)

bernoulli_stan = os.path.join(
    cmdstan_path(), "examples", "bernoulli", "bernoulli.stan"
)
bernoulli_data = os.path.join(
    cmdstan_path(), "examples", "bernoulli", "bernoulli.data.json"
)
bernoulli_model = CmdStanModel(stan_file=bernoulli_stan)
bern_fit = bernoulli_model.sample(data=bernoulli_data)

print("======================================")
print(f"Root logging level: {logging.root.level}")
print("======================================")
my_logger.info("TEST_2")  # Is logged (root is INFO)
```
</details>

<details open>
<summary>Output</summary>
<br>

![image](https://user-images.githubusercontent.com/4030868/151233144-8db079a6-c2b5-4060-ba8d-e5b8de79666b.png)

</details>

#### Additional Information:

I believe this was touched on [here](https://github.com/stan-dev/cmdstanpy/issues/415#issuecomment-888632693) but I still think it's worth bringing up explicitly. I am not an expert on logging by any means but I believe this could be solved by explicitly setting *just* the cmdstanpy logger to `logging.INFO` rather than root. Happy to try a PR if that would help.

#### Current Version:

`cmdstanpy 1.0.0`

**Comment by WardBrian** [comment]
This is a good issue to bring up. I’m not that familiar with how to configure individual loggers in python outside of the basicConfig option, but if it’s possible to not touch other loggers that would be much preferred
