### ISSUE TITLE
Complex output is not properly reshaped

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/cmdstanpy#536]
#### Summary:

Since 2.28, cmdstan CSV can have `real` and `imag` as 'indicies` in column headers. These are not properly handled.

#### Description:

Consider the following stan model:
```stan
generated quantities {
  array[2,3] complex zs = {{3,4i,0},{1i,2i,3i}};
}
```
If run with `./complex_output sample num_samples=1`, it produces the following CSV file:

```csv
# stan_version_major = 2
# stan_version_minor = 28
# stan_version_patch = 0
# model = complex_output_model
# start_datetime = 2022-02-04 16:14:05 UTC
# method = sample (Default)
#   sample
#     num_samples = 1
#     num_warmup = 1000 (Default)
#     save_warmup = 0 (Default)
#     thin = 1 (Default)
#     adapt
#       engaged = 1 (Default)
#       gamma = 0.050000000000000003 (Default)
#       delta = 0.80000000000000004 (Default)
#       kappa = 0.75 (Default)
#       t0 = 10 (Default)
#       init_buffer = 75 (Default)
#       term_buffer = 50 (Default)
#       window = 25 (Default)
#     algorithm = hmc (Default)
#       hmc
#         engine = nuts (Default)
#           nuts
#             max_depth = 10 (Default)
#         metric = diag_e (Default)
#         metric_file =  (Default)
#         stepsize = 1 (Default)
#         stepsize_jitter = 0 (Default)
#     num_chains = 1 (Default)
# id = 1 (Default)
# data
#   file =  (Default)
# init = 2 (Default)
# random
#   seed = 3433902475 (Default)
# output
#   file = output.csv (Default)
#   diagnostic_file =  (Default)
#   refresh = 100 (Default)
#   sig_figs = -1 (Default)
#   profile_file = profile.csv (Default)
# num_threads = 1 (Default)
# stanc_version = stanc3 v2.28.0
# stancflags = 
lp__,accept_stat__,zs.1.1.real,zs.1.1.imag,zs.2.1.real,zs.2.1.imag,zs.1.2.real,zs.1.2.imag,zs.2.2.real,zs.2.2.imag,zs.1.3.real,zs.1.3.imag,zs.2.3.real,zs.2.3.imag
0,0,3,0,0,1,0,4,0,2,0,0,0,3
# 
#  Elapsed Time: 0 seconds (Warm-up)
#                0 seconds (Sampling)
#                0 seconds (Total)
# 
```

CmdStanPy cannot properly read this:

```python
In [1]: import cmdstanpy

In [2]: x = cmdstanpy.from_csv('output.csv')

In [3]: x.stan_variables()
Out[3]: 
{'zs,1,1,real': array([3.]),
 'zs,1,1,imag': array([0.]),
 'zs,2,1,real': array([0.]),
 'zs,2,1,imag': array([1.]),
 'zs,1,2,real': array([0.]),
 'zs,1,2,imag': array([4.]),
 'zs,2,2,real': array([0.]),
 'zs,2,2,imag': array([2.]),
 'zs,1,3,real': array([0.]),
 'zs,1,3,imag': array([0.]),
 'zs,2,3,real': array([0.]),
 'zs,2,3,imag': array([3.])}
```

I would expect the output to be:

```python
Out[3]:
  { 'zs': array([[3.+0.j, 0.+4.j, 0.+0.j],
                 [0.+1.j, 0.+2.j, 0.+3.j]])}
```

#### Additional Information:
Provide any additional information here.

#### Current Version:

1.0 (`develop` branch), CmdStan >2.28

**Comment by WardBrian** [comment]
@mitzimorris - do you have the capacity to look into this? I'm still not terribly familiar with how we handle the Stan variables parsing and reshaping

**Comment by WardBrian** [comment]
Leaving some notes here:

These should always be the final index. That means we can treat `real` and 0 and `imag` as 1 and then use a trick like 

```python
Data[...,0] + 1j * Data[...,1]
```
from [here](https://stackoverflow.com/a/12288514)

**Comment by mitzimorris** [comment]
yes, I can deal with this.

**Comment by WardBrian** [comment]
Great! I propose using the above CSV as the test for this, as it has a very easy to recreate expected result. I don't think it should be too difficult in principle, I'm just having a hard time even locating which code to change

**Comment by mitzimorris** [comment]
started branch: https://github.com/stan-dev/cmdstanpy/tree/feature/536-complex-outputs
parsing names, no big, but dims are problematic.
we need to add the notion of "draws-as-columns" vs "draws-as-variables"

**Comment by WardBrian** [comment]
Perhaps the easier thing is to convert dims always to numbers, but then also keep a set of “complex variables” flagged so we know to do conversion on them at the end?

**Comment by mitzimorris** [comment]
yes, that would seem to be the best thing to do.
we could take this a step further to track all types - int, real, complex - because folks have asked to get ints vars back as ints.

**Comment by mitzimorris** [comment]
update: variable type info isn't available from CmdStan CSV file or model exe - only available if source code is there and can be run through the Stanc3 parser.

**Comment by WardBrian** [comment]
I suspected that might be true but wasn’t sure. Seems reasonable to only handle it for complex types then, since we always know about them thanks to the real/imag tags

another good thing to think about for the IO spec

**Comment by mitzimorris** [comment]
got `stan_variable` working for complex output.  whole lotta hacking - cf: https://github.com/stan-dev/cmdstanpy/compare/feature/536-complex-outputs

**Comment by WardBrian** [comment]
It's not too messy besides the reshaping, which can be made faster by avoiding the for loop:

```python
import math
import numpy as np
```


```python
num_draws_tot = 500
```


```python
def loop(dims):
    data = np.random.random(math.prod(dims)).reshape(num_draws_tot, -1)
    # logic starts here
    dims.pop()
    draws_complex = np.empty(
        (math.prod(dims)), dtype=complex, order='F'
    )
    # skipping the selection of self._draws[draw1:, :, col_idxs] here
    idx = 0
    for i in range(num_draws_tot):
        it = iter(data[i, :])
        for x in it:
            draws_complex[idx] = x + 1j * next(it)
            idx += 1
    return draws_complex.reshape(dims, order='F')
```


```python
def vector(dims):
    data = np.random.random(math.prod(dims)).reshape(num_draws_tot, -1)
    # logic starts here
    # skipping the selection of self._draws[draw1:, :, col_idxs] here
    draws_complex = data.reshape(dims, order='F')
    return draws_complex[...,0] + 1j* draws_complex[...,1]
```


```python
dims = [num_draws_tot,10,12,2]
```


```python
%timeit vector(dims.copy())
```

    1.09 ms ± 10.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



```python
%timeit loop(dims.copy())
```

    116 ms ± 2.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
