### ISSUE TITLE
Ignore integer divison warning.

### ISSUE THREAD

**Issue by alexhallam** [stan-dev/cmdstanpy#541]
#### Summary:
Just want to supress a warning

#### Description:
I am getting a warning I understand, but don't want to see anymore. The parameters must be integers in the way I have this sorted out, so the warning is useless at this point. I just cant figure out how to suppress the warning. 

```
WARNING:cmdstanpy:stanc3 has produced warnings:
Warning in '/home/user/.local/lib/python3.8/site-packages/tablespoon/stan/snaive.stan', line 20, column 66: Found int division:
  ((h - 1) * 1) / (lag)
```

Is this found in `CmdStanModel()` or `.sample()`

#### Additional Information:

None

#### Current Version:
`cmdstanpy = "^0.9.77"`

**Comment by mitzimorris** [comment]
this is coming from CmdStanModel() - it calls the stanc3 compiler on the Stan file on model instantiation.
these warnings are coming from the Python logger.
to disable warnings, you would set the logging level to "ERROR" -
cf discussion here:  https://discourse.mc-stan.org/t/cmdstanpy-not-compiling-with-uninformative-error/25576/7?u=mitzimorris

**Comment by WardBrian** [comment]
The warning should suggest using strict integer division with `%/%`, which should silence it

That part of the warning may be cut off in older versions

**Comment by alexhallam** [comment]
Thanks @WardBrian that is a better solution than changing the warning. Better to be explicit/clear as opposed to silencing warnings.
