### ISSUE TITLE
Design Discussion - allowing the use of `.` to access Stan variables?

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/cmdstanpy#542]
#### Summary:

I've recently been using cmdstanpy to go through Richard McElreath's _Rethinking_ course. The `stan_variable` function has been essential for this, but it is also very verbose. Consider the following snippet:

```python
mu_contrast = m_SW.stan_variable('a')[:,1] - m_SW.stan_variable('a')[:,0]
az.plot_kde(mu_contrast, plot_kwargs= dict(color='k'))
plt.ylabel('Density')
plt.xlabel('Posterior mean weight contrast (kg)')
```

It would be great if the fit objects were able to be used like so, replacing the first line with:

```python
mu_contrast = m_SW.a[:,0] - m_SW.a[:,1]
```

#### Additional Information:

This is easy to 'try out' by using the following snippet:

```python
class CustomFit(CmdStanMCMC):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
    
    def __getattr__(self,key):
        try:
            return self.stan_variable(key)
        except:
            getattr(super(), key)

# new object
m_SW_new = CustomFit(m_SW.runset)
```

The actual implementation would be very similar, except we would just test if `key` is in the list of stan variables rather than using a try/except.

#### Current Version:
1.0.1

**Comment by mitzimorris** [comment]
this would be super cool - I had no idea you could do this kind of thing in Python - by all means, let's do this!

**Comment by WardBrian** [comment]
I'll do it tomorrow (and improve the error message if you request a variable that doesn't exist - we can go ahead and list the ones that _do_, right?)

**Comment by mitzimorris** [comment]
if variable doesn't exist, listing the ones that do would be most helpful, especially for the typo-inclined.
(as opposed to folks who are type-inclined)

**Comment by ahartikainen** [comment]
What methods do we currently have with fit? And would these then override the variables?

What if we would use something similar as

    fit.vars.a

**Comment by WardBrian** [comment]
There aren’t that many methods on the fit objects, and very few of them have names which I think anyone would ever name a variable in a Stan program:
https://cmdstanpy.readthedocs.io/en/v1.0.1/api.html#cmdstanpy.CmdStanMCMC

We can break the tie in either direction we want. The thing that makes the most sense is probably preferring anything existing rather than the variables, since the user can fall back on `stan_variable`

Using `.vars.a` would look very different in implementation (rather than a simple wrapper to stan_variable, we would need to define a new object and make it a property called “var”), and I personally don’t think name collisions will be common enough to warrant it
