### ISSUE TITLE
empty generated quantities

### ISSUE THREAD

**Issue by jonathan-taylor** [stan-dev/cmdstanpy#544]
#### Summary:
Please provide a short couple sentence summary.

Trying to sample predictive distribution from a model for which MCMC runs fine but `generated_quantities` gives me an array of shape (0,500) (I have 500 generated quantities say). No error message either.

#### Description:
Describe the issue as clearly as possible.

I have 4 chains running 1000 samples for 13 parameters so my MCMC sample is (4,1000,13). When I pass the return value of `CmdStanModel.sample` or a list of csv files saved from such object I get an empty return value, i.e. shape (0,500) where I might expect a shape (4,100,500)

#### Additional Information:
Provide any additional information here.

#### Current Version:

0.9.66

**Comment by WardBrian** [comment]
Are you able to try with a newer version of the package? 0.9.66 is quite old at this point

**Comment by jonathan-taylor** [comment]
Installed 1.0.1 and will retry
________________________________

**Comment by jonathan-taylor** [comment]
Seems it was a bug in my STAN code that raised no error.

I was trying something like

```
prob = normal_lcdf(mu | 0, 1);
group = bernoulli_rng(prob);
```

But normal_lcdf​ is logCDF so it is invalid as an arg to bernoulli_rng​ but I saw no error in the generate_quantities​ method but execution returned an empty result.

Using normal_cdf​ works fine. Might be helpful to have some error or warning.
________________________________

**Comment by jonathan-taylor** [comment]
A minimal example that produces behaviour:

```
# %%
from cmdstanpy.model import CmdStanModel
import tempfile

# %%
model_code = """
data {
  int<lower=0> N;
  int<lower=0,upper=1> y[N];
}
parameters {
  real<lower=0,upper=1> theta;
}
model {
  theta ~ beta(1,1);  // uniform prior on interval 0,1
  y ~ bernoulli(theta);
}
"""
model_file = tempfile.mkstemp()[1] + '.stan'
open(model_file, 'w').write(model_code)

# %%
data = {'N':10, 'y':[0]*5+[1]*5}
model = CmdStanModel(stan_file=model_file)
fit = model.sample(data=data)

# %%
predictive_model_code = """
data { 
  int<lower=0> N; 
  int<lower=0,upper=1> y[N];
} 
parameters {
  real<lower=0,upper=1> theta;
} 
generated quantities {
  int y_rep[N];
  real myprob;
  for (n in 1:N) {
    myprob = normal_lcdf(theta | 0, 1);
    y_rep[n] = bernoulli_rng(myprob);
  }
}
"""
predictive_model_file = tempfile.mkstemp()[1] + '.stan'
open(predictive_model_file, 'w').write(predictive_model_code)

# %%
predictive_model = CmdStanModel(stan_file=predictive_model_file)

# %%
new_quantities = predictive_model.generate_quantities(data=data, mcmc_sample=fit)
# %%
new_quantities.draws_pd()

```

This raises `ValueError: could not broadcast input array from shape (0,1) into shape (1000,11)
`

**Comment by ahartikainen** [comment]
Can you set up flags so you see the C++ messages? (I don't remember what kw it was)

**Comment by WardBrian** [comment]
You should be able to set `verbose` In the call to `generated_quantities`

**Comment by jonathan-taylor** [comment]
I guess you mean `show_console=True` -- `verbose` doesn't seem to be an argument. That does definitely give information that is useful. Maybe a parsing of the console to search for `Exception`?

As a potential user, raising a python warning after the cmdstan raises one could be helpful. In this case, the error is clearly mine, and I happened to notice on inspecting the code. If the console warnings were raised it might have saved me some time.

**Comment by WardBrian** [comment]
We do check the console for the string 'Error' or 'Exception' in the method `runset.get_err_msgs()`, but it doesn't seem to be actually called unless the process exits with a nonzero exit code. 

This seems like it is related to https://github.com/stan-dev/cmdstan/issues/1082?

**Comment by WardBrian** [comment]
I've opened a new issue for the error/exception issue, so we can close this now.
