### ISSUE TITLE
install_cmdstan fails with TypeError: main() missing 1 required positional argument: 'args'

### ISSUE THREAD

**Issue by fohria** [stan-dev/cmdstanpy#547]
#### Summary:
Using `install_cmdstan` script [as per documentation](https://cmdstanpy.readthedocs.io/en/v1.0.1/installation.html#function-install-cmdstan) fails

#### Description:
I created a new conda environment and installed cmdstanpy 1.0.1 from conda-forge. When running `install_cmdstan` in the newly created environment, I get the error:

```
Traceback (most recent call last):
  File "/home/stan/mambaforge/envs/newstan/bin/install_cmdstan", line 10, in <module>
    sys.exit(main())
TypeError: main() missing 1 required positional argument: 'args'
```

Reading comments in previous issue mentioned below in additional info, I tried running with `python -m cmdstanpy.install_cmdstan`. This gives me a warning:

```
/home/stan/mambaforge/envs/newstan/lib/python3.9/runpy.py:127: RuntimeWarning: 'cmdstanpy.install_cmdstan' found in sys.modules after import of package 'cmdstanpy', but prior to execution of 'cmdstanpy.install_cmdstan'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
```

After warning, script downloads and installs cmdstan and I can use it as normal from python

#### Additional Information:
Issue seems similar to https://github.com/stan-dev/cmdstanpy/issues/499 

#### Current Version:
cmdstanpy 1.0.1

**Comment by WardBrian** [comment]
This sounds like you may have cmdstanpy installed to a system python as well as the one in the conda environment. What is the output of `which install_cmdstan` (Linux/MacOS) or `Get-Command install_cmdstan` (Windows)?

**Comment by ahartikainen** [comment]
Also, if you conda installed cmdstanpy, you also got the compiled cmdstan with it?

The other thing, you might have the cmdstanpy installed on a base conda env which then might leak to your another env.

**Comment by WardBrian** [comment]
Glad it is working for you now!
