### ISSUE TITLE
RunSet's __repr__ throws an error

### ISSUE THREAD

**Issue by daikonradish** [stan-dev/cmdstanpy#55]
#### Summary:
`RunSet`'s `__repr__` is broken.

#### Description:
Followed the instructions in the notebook.

    import os
    import os.path
    from cmdstanpy import cmdstan_path, compile_model, sample, get_drawset, summary, diagnose

    bernoulli_path = os.path.join(cmdstan_path(), 'examples', 'bernoulli')
    bernoulli_stan = os.path.join(bernoulli_path, 'bernoulli.stan')
    bernoulli_model = compile_model(bernoulli_stan)
    bern_data = { "N" : 10, "y" : [0,1,0,0,0,0,0,0,0,1] }

    bern_fit = sample(bernoulli_model, data=bern_data)

    bern_fit . # Error!

#### Additional Information:
Offending line is here: https://github.com/daikonradish/cmdstanpy/blob/master/cmdstanpy/lib.py#L500

(Should be `self._args`)

**Comment by mitzimorris** [comment]
@daikonradish - good catch, many thanks!

fixed by https://github.com/stan-dev/cmdstanpy/commit/fe4142179ca934a2146ee5869de47f0b59b43c4a
