### ISSUE TITLE
Improving installation instructions

### ISSUE THREAD

**Issue by patel-zeel** [stan-dev/cmdstanpy#558]
#### Summary:
Changing `ValueError` from `run "install_cmdstan"` to (1) `run "cmdstanpy.install_cmdstan()"` or (2) `run "import cmdstanpy;cmdstanpy.install_cmdstan()"` will make it more convenient and explicit from Python users.
https://github.com/stan-dev/cmdstanpy/blob/f2616ae320f09041ec4570df96be9b1010400686/cmdstanpy/utils.py#L181-L183

#### Current Version:
1.0.1

**Comment by mitzimorris** [comment]
very clear - will do!

**Comment by WardBrian** [comment]
I think the current message is a reference to the `install_cmdstan` shell command, not the Python function, hence the confusion. We should probably mention both
