### ISSUE TITLE
Issues installing Cmdstan Through Cmdstanpy

### ISSUE THREAD

**Issue by justinessert** [stan-dev/cmdstanpy#563]
#### Summary:

I am trying to install cmdstanpy through various methods on a Docker image and am having issues with the cmdstan install.

##### Installing through Conda:

Within a docker build, I am running `conda install -c conda-forge cmdstanpy=0.9.77` to install the cmdstanpy. My understanding is that this should install cmdstan and get everything ready to be run.

This conda install completes successfully, but then when I go to use the docker image that I have created, I get errors. Specifically, I get the following error:

```
ERROR    cmdstanpy:model.py:343 file /opt/program/Aenomoleas/aenomoleas/detectors/anomaly/bayesian/stan_models/smHW_residual_init.stan, exception Command: ['make', '/opt/program/Aenomoleas/aenomoleas/detectors/anomaly/bayesian/stan_models/smHW_residual_init']
failed, returncode: 2, error: No such file or directory, stderr: <built-in>: fatal error: opening dependency file stan/src/stan/model/model_header.d: Permission denied
compilation terminated.
<built-in>: fatal error: opening dependency file src/cmdstan/main.d: Permission denied
compilation terminated.
/usr/include/stdc-predef.h:1:0: fatal error: can't create precompiled header stan/src/stan/model/model_header.hpp.gch: Permission denied
compilation terminated.
make: *** [make/program:27: stan/src/stan/model/model_header.hpp.gch] Error 1
ERROR    cmdstanpy:model.py:381 model compilation failed
```

To my understanding, this occurs because within cmdstanpy is trying to compile some cmdstan source files within the site packages directory. But when I am running this docker image, I no longer have access to edit the docker image, hence the failure.

##### Installing through `install_cmdstan` function

I'd much prefer to install via conda, but this works locally for me at least. Based on my understanding, this function is first downloading and installing `cmdstan`, but the crucially also runs `make build` [here](https://github.com/stan-dev/cmdstanpy/blob/develop/cmdstanpy/install_cmdstan.py#L111) and then tests a model compilation [here](https://github.com/stan-dev/cmdstanpy/blob/develop/cmdstanpy/install_cmdstan.py#L188). This seems to do create all the necessary files so that when we go to run `cmdstanpy` we don't have to change the site-packages anymore.

Unfortunately, with this solution, when I try to run it on my company's remote servers, our proxy is preventing me from actually downloading the cmdstan source from GitHub. So that leads me back to trying to get the conda install to work

##### Troubleshooting conda install

My next idea was to try to combine the two approaches. So I first installed `cmdstanpy` from conda. After that I tried to replicate what the `install_cmdstan` function was doing by running:

```
cd /opt/conda/envs/env_name/bin/cmdstan
echo "Compiling Cmdstan"
make build

echo "Testing Model Compilation"
make examples/bernoulli/bernoulli
```

When I run that, it seems to successfully do the initial `make build`, but then when it comes to compiling the model I get this long error message:

<details>
Testing Model Compilation
g++ -std=c++1y -pthread -D_REENTRANT -Wno-sign-compare -Wno-ignored-attributes      -I /opt/conda/envs/mlaasflow/include/    -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.75.0 -I stan/lib/stan_math/lib/sundials_6.0.0/include -I stan/lib/stan_math/lib/sundials_6.0.0/src/sundials    -DBOOST_DISABLE_ASSERTS   -DTBB_INTERFACE_NEW  -DTBB_INTERFACE_NEW     -c -MT stan/src/stan/model/model_header.hpp.gch -MT stan/src/stan/model/model_header.d -MM -E -MG -MP -MF stan/src/stan/model/model_header.d stan/src/stan/model/model_header.hpp
g++ -std=c++1y -pthread -D_REENTRANT -Wno-sign-compare -Wno-ignored-attributes      -I /opt/conda/envs/mlaasflow/include/    -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.75.0 -I stan/lib/stan_math/lib/sundials_6.0.0/include -I stan/lib/stan_math/lib/sundials_6.0.0/src/sundials    -DBOOST_DISABLE_ASSERTS   -DTBB_INTERFACE_NEW  -DTBB_INTERFACE_NEW     -c -MT src/cmdstan/main.o -MM -E -MG -MP -MF src/cmdstan/main.d src/cmdstan/main.cpp

--- Translating Stan model to C++ code ---
bin/stanc  --o=examples/bernoulli/bernoulli.hpp examples/bernoulli/bernoulli.stan

--- Compiling, linking C++ code ---
g++ -std=c++1y -pthread -D_REENTRANT -Wno-sign-compare -Wno-ignored-attributes      -I /opt/conda/envs/mlaasflow/include/    -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.75.0 -I stan/lib/stan_math/lib/sundials_6.0.0/include -I stan/lib/stan_math/lib/sundials_6.0.0/src/sundials    -DBOOST_DISABLE_ASSERTS   -DTBB_INTERFACE_NEW  -DTBB_INTERFACE_NEW     -c -Wno-ignored-attributes   -x c++ -o examples/bernoulli/bernoulli.o examples/bernoulli/bernoulli.hpp
g++ -std=c++1y -pthread -D_REENTRANT -Wno-sign-compare -Wno-ignored-attributes      -I /opt/conda/envs/mlaasflow/include/    -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.75.0 -I stan/lib/stan_math/lib/sundials_6.0.0/include -I stan/lib/stan_math/lib/sundials_6.0.0/src/sundials    -DBOOST_DISABLE_ASSERTS   -DTBB_INTERFACE_NEW  -DTBB_INTERFACE_NEW           -Wl,-L,"/opt/conda/envs/mlaasflow/lib/" -Wl,-rpath,"/opt/conda/envs/mlaasflow/lib/" -Wl,--disable-new-dtags -ltbb    examples/bernoulli/bernoulli.o src/cmdstan/main.o        -Wl,-L,"/opt/conda/envs/mlaasflow/lib/" -Wl,-rpath,"/opt/conda/envs/mlaasflow/lib/" -Wl,--disable-new-dtags -ltbb stan/lib/stan_math/lib/sundials_6.0.0/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_6.0.0/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_6.0.0/lib/libsundials_idas.a stan/lib/stan_math/lib/sundials_6.0.0/lib/libsundials_kinsol.a   -o examples/bernoulli/bernoulli
/usr/bin/ld: warning: src/cmdstan/main.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
/usr/bin/ld: warning: src/cmdstan/main.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
src/cmdstan/main.o: In function `stan::services::util::mcmc_writer::log_timing(double, double)':
main.cpp:(.text._ZN4stan8services4util11mcmc_writer10log_timingEdd[_ZN4stan8services4util11mcmc_writer10log_timingEdd]+0xa5): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
main.cpp:(.text._ZN4stan8services4util11mcmc_writer10log_timingEdd[_ZN4stan8services4util11mcmc_writer10log_timingEdd]+0xfe): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
main.cpp:(.text._ZN4stan8services4util11mcmc_writer10log_timingEdd[_ZN4stan8services4util11mcmc_writer10log_timingEdd]+0x190): undefined reference
 to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
src/cmdstan/main.o: In function `cmdstan::write_datetime(stan::callbacks::writer&)'
:
main.cpp:(.text._ZN7cmdstan14write_datetimeERN4stan9callbacks6writerE+0x6a): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
src/cmdstan/main.o: In function `cmdstan::json::json_data_handler::set_last_dim()':
main.cpp:(.text._ZN7cmdstan4json17json_data_handler12set_last_dimEv[_ZN7cmdstan4json17json_data_handler12set_last_dimEv]+0x7f): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::
basic_stringstream()'

src/cmdstan/main.o:main.cpp:(.text._ZN7cmdstan4json17json_data_handler7booleanEb[_ZN7cmdstan4json17json_data_handler7booleanEb]+0x2d): more undefined references to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()' follow
src/cmdstan/main.o: In function `void stan::math::invalid_argument<int>(char const*, char const*, int const&, char const*, char const*)':
main.cpp:(.text._ZN4stan4math16invalid_argumentIiEEvPKcS3_RKT_S3_S3_[_ZN4stan4math16invalid_argumentIiEEvPKcS3_RKT_S3_S3_]+0x3d):
undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
src/cmdstan/main.o: In function `stan::math::check_positive(char const*, char const*, char const*, int)::{lambda()#1}::operator()() const':
main.cpp:(.text.unlikely._ZZN4stan4math14check_positiveEPKcS2_S2_iENKUlvE_clEv[_ZZN4stan4math14check_positiveEPKcS2_S2_iENKUlvE_clEv]+0x2c): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
src/cmdstan/main.o: In function `stan::math::check_size_match<
int, int>(char const*, char const*, int, char const*, int)::{lambda()#1}::operator()() const':
main.cpp:(.text.unlikely._ZZN4stan4math16check_size_matchIiiEEvPKcS3_T_S3_T0_ENKUlvE_clEv[_ZZN4stan4math16check_size_matchIiiEEvPKcS3_T_S3_T0_ENKUlvE_clEv]+0x2c): undefined reference to `
std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
src/cmdstan/main.o: In function `stan
::math::check_size_match<int, long>(char const*, char const*, int, char const*, long)::{
lambda()#1}::operator()() const':
main.cpp:(.text.unlikely._ZZN4stan4math16check_size_matchIilEEvPKcS3_T_S3_T0_ENKUlvE_clEv[_ZZN4stan4math16check_size_matchIilEEvPKcS3_T_S3_T0_ENKUlvE_clEv]+0x2c): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
src/cmdstan/main.o: In function `stan::math::check_size_match<int, unsigned long>(char const*, char const*, int,
char const*, unsigned long)::{lambda()#1}::operator()() const':
main.cpp:(.text.unlikely._ZZN4stan4math16check_size_matchIimEEvPKcS3_T_S3_T0_ENKUlvE_clEv[_ZZN4stan4math16check_size_matchIimEEvPKcS3_T_S3_T0_ENKUlvE_clEv]+0x2c): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
src/cmdstan/main.o: In function `cmdstan::singleton_argument<std
::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::parse_args(std::vector<std::__cxx11::basic_string<char, std
::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, stan::callbacks::writer&, stan::callbacks::writer&, bool&)':
main.cpp:(.text._ZN7cmdstan18singleton_argumentINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE10parse_argsERSt6vectorIS6_SaIS6_EERN4stan9callbacks6writerESF_Rb[_ZN7cmdstan18singleton_argumentINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE10parse_argsERSt6vectorIS6_SaIS6_EERN4stan9callbacks6writerESF_Rb]+0x268): undefined reference
to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
src/cmdstan/main.o: In
function `cmdstan::json::json_data::validate_dims(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const&) const':
main.cpp:(.text._ZNK7cmdstan4json9json_data13validate_dimsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_RKSt6vectorImSaImEE[_ZNK7cmdstan4json9json_data13validate_dimsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_RKSt6vectorImSaImEE]+0x89): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
main.cpp:(.text._ZNK7cmdstan4json9json_data13validate_dimsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_RKSt6vectorImSaImEE[_ZNK7cmdstan4json9json_data13validate_dimsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_RKSt6vectorImSaImEE]+0x266): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
main.cpp:(.text._ZNK7cmdstan4json9json_data13validate_dimsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_RKSt6vectorImSaImEE[_ZNK7cmdstan4json9json_data13validate_dimsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_RKSt6vectorImSaImEE]+0x370): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator
<char> >::basic_stringstream()'
main.cpp:(.text._ZNK7cmdstan4json9json_data13validate_dimsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_RKSt6vectorImSaImEE[_ZNK7cmdstan4json9json_data13validate_dimsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_RKSt6vectorImSaImEE]+0x54a): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
src/cmdstan/main.o:main.cpp:(.text._ZN4stan4math22check_lower_triangularIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEELPv0EEEvPKcS7_RKT_[_ZN4stan4math22check_lower_triangularIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEELPv0EEEvPKcS7_RKT_]+0xc9): more undefined references to `std::__cxx11::basic_stringstream<char, std::char_traits<char>
, std::allocator<char> >::basic_stringstream()' follow
src/cmdstan
/main.o: In function `void stan::math::invalid_argument<long>(char const*, char const*, long const&, char const*, char const*)':
main.cpp:(.text._ZN4stan4math16invalid_argumentIlEEvPKcS3_RKT_S3_S3_[_ZN4stan4math16invalid_argumentIlEEvPKcS3_RKT_S3_S3_]+0x3d): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
src/cmdstan/main.o: In function `stan::math::check_size_match<long, int>(char const*, char const*, long, char const*, int)::{lambda(
)#1}::operator()() const':
main.cpp:(.text.unlikely._ZZN4stan4math16check_size_matchIliEEvPKcS3_T_S3_T0_ENKUlvE_clEv[_ZZN4stan4math16check_size_matchIliEEvPKcS3_T_S3_T0_ENKUlvE_clEv]+0x2c): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std
::allocator<char> >::basic_ostringstream()'
src/cmdstan/main.o: In function `stan::math::check_size_match<long, long>(char const*, char const*, long,
char const*, long)::{lambda()#1}::operator()() const':
main.cpp:(.text.unlikely._ZZN4stan4math16check_size_matchIllEEvPKcS3_T_S3_T0_ENKUlvE_clEv[_ZZN4stan4math16check_size_matchIllEEvPKcS3_T_S3_T0_ENKUlvE_clEv]+0x2c): undefined reference to `std
::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
src/cmdstan/main.o: In function `stan::math::check_size_match<long, long>(char const*, char const*, char const*, long, char const*, char const*, long)::{
lambda()#1}::operator()() const':
main.cpp:(.text.unlikely._ZZN4stan4math16check_size_matchIllEEvPKcS3_S3_T_S3_S3_T0_ENKUlvE_clEv[_ZZN4stan4math16check_size_matchIllEEvPKcS3_S3_T_S3_S3_T0_ENKUlvE_clEv]+0x30): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
main.cpp:(.text.unlikely._ZZN4stan4math16check_size_matchIllEEvPKcS3_S3_T_S3_S3_T0_ENKUlvE_clEv[_ZZN4stan4math16check_size_matchIllEEvPKcS3_S3_T_S3_S3_T0_ENKUlvE_clEv]+0x74): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
src/cmdstan/main.o:main.cpp:(.text.unlikely._ZZN4stan4math15check_symmetricIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEELPv0EEEvPKcS7_RKT_ENKUlvE_clEv[_ZZN4stan4math15check_symmetricIN5Eigen6MatrixIdLin1ELin1ELi0ELin1ELin1EEELPv0EEEvPKcS7_RKT_ENKUlvE_clEv]+0x30): more undefined references to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char>
>::basic_ostringstream()' follow
src/cmdstan/main.o: In function `void stan::services::util::gq_writer::write_gq_values<stan::model::model_base, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u,
2147483399u> > >(stan::model::model_base const&, boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014u, 0u, 2147483563u>, boost::random::linear_congruential_engine<unsigned int, 40692u, 0u, 2147483399u>
>&, std::vector<double, std::allocator<double> > const&)':
main.cpp:(.text._ZN4stan8services4util9gq_writer15write_gq_valuesINS_5model10model_baseEN5boost6random23additive_combine_engineINS7_26linear_congruential_engineIjLj40014ELj0ELj2147483563EEENS9_IjLj40692ELj0ELj2147483399EEEEEEEvRKT_RT0_RKSt6vectorIdSaIdEE[_ZN4stan8services4util9gq_writer15write_gq_valuesINS_5model10model_baseEN5boost6random23additive_combine_engineINS7_26linear_congruential_engineIjLj40014ELj0ELj2147483563EEENS9_IjLj40692ELj0ELj2147483399EEEEEEEvRKT_RT0_RKSt6vectorIdSaIdEE]+0x6b): undefined reference to `std::__cxx11::basic_stringstream<char,
std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
src/cmdstan/main.o: In function `cmdstan::singleton_argument<bool>::parse_args(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, stan::callbacks::writer&, stan::callbacks::writer&, bool&)':
main.cpp:(.text._ZN7cmdstan18singleton_argumentIbE10parse_argsERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EERN4stan9callbacks6writerESF_Rb[_ZN7cmdstan18singleton_argumentIbE10parse_argsERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EERN4stan9callbacks6writerESF_Rb]+0x226): undefined reference to `std::__cxx11::basic_stringstream<
char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
src/cmdstan/main.o: In function `cmdstan::json::json_data_handler::start_array()':
main.cpp:(.text._ZN7cmdstan4json17json_data_handler11start_arrayEv[_ZN7cmdstan4json17json_data_handler11start_arrayEv]+0x292):
undefined reference to `std::__cxx11::basic_stringstream
<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
src/cmdstan/main.o: In function `cmdstan::json::json_data_handler::string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
main.cpp:(.text._ZN7cmdstan4json17json_data_handler6stringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN7cmdstan4json17json_data_handler6stringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x1eb): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
src/cmdstan/main.o: In function `stan::variational::print_progress(int, int, int, int, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&,
stan::callbacks::logger&)':
main.cpp:(.text._ZN4stan11variational14print_progressEiiiibRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_RNS_9callbacks6loggerE[_ZN4stan11variational14print_progressEiiiibRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_RNS_9callbacks6loggerE]+0x120): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'

src/cmdstan/main.o:main.cpp:(.text._ZN4stan4math8internal30elementwise_throw_domain_errorIJPKcS4_S4_S4_dS4_S4_S4_EEEvDpKT_[_ZN4stan4math8internal30elementwise_throw_domain_errorIJPKcS4_S4_S4_dS4_S4_S4_EEEvDpKT_]+0x5b): more undefined references to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()' follow
src/cmdstan/main.o: In function `void stan::math::throw_domain_error<char [1]>(char const*, char const*, char const (&) [1], char const*, char const*)':
main.cpp:(.text._ZN4stan4math18throw_domain_errorIA1_cEEvPKcS4_RKT_S4_S4_[_ZN4stan4math18throw_domain_errorIA1_cEEvPKcS4_RKT_S4_S4_]+0x3d): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
src/cmdstan/main.o: In function `void stan::math::internal::elementwise_throw_domain_error<char const*, char const*, char const*, char const*, unsigned long, char const*, double, char const*, char const*, char const*>(char const* const, char const* const, char const* const, char const* const, unsigned long const, char const* const, double
 const
, char const* const, char const* const, char const* const)':
main.cpp:(.text._ZN4stan4math8internal30elementwise_throw_domain_errorIJPKcS4_S4_S4_mS4_dS4_S4_S4_EEEvDpKT_[_ZN4stan4math8internal30elementwise_throw_domain_errorIJPKcS4_S4_S4_mS4_dS4_S4_S4_EEEvDpKT_]+0x6f): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
src/cmdstan
/main.o: In function `void stan::math::internal::elementwise_throw_domain_error<char const*, char const*, char const*, char const*, unsigned long, char const*, unsigned long, char const*, double, char const*, char const*, char const*>(char const* const, char const* const, char const* const, char const* const, unsigned long const, char const* const, unsigned long const, char const* const, double const, char const* const, char const* const, char const* const)':
main.cpp:(.text._ZN4stan4math8internal30elementwise_throw_domain_errorIJPKcS4_S4_S4_mS4_mS4_dS4_S4_S4_EEEvDpKT_[_ZN4stan4math8internal30elementwise_throw_domain_errorIJPKcS4_S4_S4_mS4_mS4_dS4_S4_S4_EEEvDpKT_]+0x7a): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
src/cmdstan/main.o: In function `void stan::math::throw_domain_error<char [26]>(char const*, char const*, char const (&) [26], char const*, char const*)':
main.cpp:(.text._ZN4stan4math18throw_domain_errorIA26_cEEvPKcS4_RKT_S4_S4_[_ZN4stan4math18throw_domain_errorIA26_cEEvPKcS4_RKT_S4_S4_]+0x3d): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
src/cmdstan/main.o: In function `void stan::math::throw_domain_error<unsigned long>(char const*, char const*, unsigned long
const&,
 char const*, char const*)':
main.cpp:(.text._ZN4stan4math18throw_domain_errorImEEvPKcS3_RKT_S3_S3_[_ZN4stan4math18throw_domain_errorImEEvPKcS3_RKT_S3_S3_]+0x3d): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'

src/cmdstan/main.o: In function `cmdstan::categorical_argument::print_help(stan::callbacks::writer&, int, bool)':
main.cpp:(.text._ZN7cmdstan20categorical_argument10print_helpERN4stan9callbacks6writerEib[_ZN7cmdstan20categorical_argument10print_helpERN4stan9callbacks6writerEib]+0x173): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
src/cmdstan/main.o: In function `cmdstan::json::json_data_handler::save_current_key_value_pair()':
main.cpp:(.text._ZN7cmdstan4json17json_data_handler27save_current_key_value_pairEv[_ZN7cmdstan4json17json_data_handler27save_current_key_value_pairEv]+0xeb): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<
char> >::basic_stringstream()'
src/cmdstan/main.o: In function `cmdstan::argument_parser::print_usage(stan::callbacks::writer&, char const*)':
main.cpp:(.text._ZN7cmdstan15argument_parser11print_usageERN4stan9callbacks6writerEPKc[_ZN7cmdstan15argument_parser11print_usageERN4stan9callbacks6writerEPKc]+0x175): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
src/cmdstan/main.o: In
 function `cmdstan::list_argument::parse_args(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, stan::callbacks::writer&, stan:
:callbacks::writer&, bool&)':
main.cpp:(.text._ZN7cmdstan13list_argument10parse_argsERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EERN4stan9callbacks6writerESE_Rb[_ZN7cmdstan13list_argument10parse_argsERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EERN4stan9callbacks6writerESE_Rb]+0x2a0): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(
)'
src/cmdstan/main.o: In function `int stan::model::test_gradients<true, true, stan::model::model_base>(stan::model::model_base const&, std::vector<double, std::allocator<double> >&, std::vector<int, std::allocator<int> >&, double, double, stan::callbacks::interrupt&, stan::
callbacks::logger&, stan::callbacks::writer&)':
main.cpp:(.text._ZN4stan5model14test_gradientsILb1ELb1ENS0_10model_baseEEEiRKT1_RSt6vectorIdSaIdEERS6_IiSaIiEEddRNS_9callbacks9interruptERNSD_6loggerERNSD_6writerE[_ZN4stan5model14test_gradientsILb1ELb1ENS0_10model_baseEEEiRKT1_RSt6vectorIdSaIdEERS6_IiSaIiEEddRNS_9callbacks9interruptERNSD_6loggerERNSD_6writerE]+0x65): undefined reference to `std::__cxx11::
basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
src/cmdstan/main.o:main.cpp:(.text._ZN4stan5model14test_gradientsILb1ELb1ENS0_10model_baseEEEiRKT1_RSt6vectorIdSaIdEERS6_IiSaIiEEddRNS_9callbacks9interruptERNSD_6loggerERNSD_6writerE[_ZN4stan5model14test_gradientsILb1ELb1ENS0_10model_baseEEEiRKT1_RSt6vectorIdSaIdEERS6_IiSaIiEEddRNS_9callbacks9interruptERNSD_6loggerERNSD_6writerE]+0x1f1): more undefined references to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()' follow

collect2: error: ld returned 1 exit status

make: *** [make/program:59: examples/bernoulli/bernoulli] Error 1
</details>

Could you help me understand why this is happening and how I can fully compile everything after I install via conda?

#### Current Version:

We are using cmdstanpy `0.9.77`

**Comment by WardBrian** [comment]
Your hunch about the folder being inaccessable sounds reasonable to me. Have you tried using `--prefix` to change where your conda environment is created?

As for your second question, that is not an error I have seen before. Combining Conda with your own attempts at compilation is probably not going to work perfectly, but you could try running `make clean-all` before the `make build`.

Finally, if you're able to download the cmdstan tarball manually from https://github.com/stan-dev/cmdstan/releases, you should be able to unpack that and run `make build`. This is the same thing `install_cmdstan` does, but if downloading inside the container is not an option it should work

**Comment by justinessert** [comment]
Thanks Brian!

It looks like everything is working after I added the `make clean-all` prior to the `make build`!

Though this is working fine for me so far, do you think moving forward it would be possible to either add one or both of these:

- Add a function to cmdstanpy that handles this `make clean-all`, `make build`, and testing `make examples/bernoulli/bernoulli`
- Include all the files that result from `make build` (and maybe even run the `make examples/bernoulli/bernoulli` test, if that's possible) within the conda install

**Comment by WardBrian** [comment]
I believe the rebuild_cmdstan function does the first bullet you describe

**Comment by justinessert** [comment]
Awesome, thanks!
