### ISSUE TITLE
Proposal: Add reviewnb to the repository

### ISSUE THREAD

**Issue by mjhajharia** [stan-dev/cmdstanpy#576]
[ReviewNB](https://www.reviewnb.com) makes it easier to view Pull requests and edits made to jupyter notebooks, whenever a PR with a notebook is created a github action runs which shows you an option to open that notebook in reviewnb which shows git diff for the notebook along with a place to add comments to specific cells which also get rendered on the github issue. PyMC uses it as well and I think it makes things very smooth.

**Comment by bob-carpenter** [comment]
Are there notebooks in cmdstanpy?  If so for what?  If not, are there plans to add notebooks?  

So far, our doc has been in other forms and our case studies have gone elsewhere.

**Comment by mjhajharia** [comment]
yeah we use sphinx in pymc as well, the only usefulness was for PRs, i mean yeah if you don't plan on having a few notebooks with consistent updates it won't be too useful. like the pymc-examples repo exists with only jupyter-notebooks and it makes things easier, example PR: https://github.com/pymc-devs/pymc-examples/pull/141 (you can login to reviewnb with github, and it isn't too much to setup).

**Comment by WardBrian** [comment]
Each individual contributor would need to log in to this service right? I can’t click the link in the above PR you mention without being prompted to log in/grant them permissions on my personal GitHub account

**Comment by mjhajharia** [comment]
yeah you'd have to do that, that's definitely a con and makes it a tradeoff, **unrelated**: but just because you mentioned sphinx, I love fidgeting with docs with sphinx, so you probably already know all of this but there's all these cool directives in sphinx etc, and oriol made this very nice cheatsheet i go to https://sphinx-primer.readthedocs.io/en/latest/core/directives.html. like you can have visually sensible boxes for warnings and deprecations and hints etc etc and if it's fine once in a while I'll keep making such PRs for cmdstanpy as I'm browsing the api and docs for my work!

**Comment by WardBrian** [comment]
Yeah, I don't think we can expect contributors to want to do that (I wouldn't myself), so it's probably better to just do review all in-github IMO

**Comment by WardBrian** [comment]
> unrelated: but just because you mentioned sphinx

That's a nice reference. I find the Sphinx doc is not great when it comes to discoverability, so a more practical guide is definitely nice. We use a few of the note/warning directives, I think mainly on the installation page

We of course always welcome docs updates! It's very useful to get fresh eyes on this sort of thing every now and then - at first I had a lot of feedback for our docs, but now I find I am too used to them to really see a lot of their blind spots and hidden assumptions
