### ISSUE TITLE
do we still need `install_cmdstan` as command line script?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#580]
#### Summary:
Initial version of `install_cmdstan` was a shell script; then rewritten in Python.
Is there any reason to continue to support the command-line script?

#### Description:
Not sure what's going on with my Python environment, but running `install_cmdstan` script produces a RuntimeWarning:

```
~/github/stan-dev/cmdstanpy (docs/570-install-instructions)> python3 -m cmdstanpy.install_cmdstan --help
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py:127: RuntimeWarning: 'cmdstanpy.install_cmdstan' found in sys.modules after import of package 'cmdstanpy', but prior to execution of 'cmdstanpy.install_cmdstan'; this may result in unpredictable behaviour
```

#### Current Version:
CmdStanPy 1.0.1

**Comment by mitzimorris** [comment]
@WardBrian  - address via PR #579?

**Comment by WardBrian** [comment]
I believe you should not be running it with python3 -m, but rather just running `install_cmdstan`. We tell python to expose the command directly in our setup.py

I think it’s still useful for things like CI

**Comment by WardBrian** [comment]
I believe you should not be running it with python3 -m, but rather just running `install_cmdstan`. We tell python to expose the command directly in our setup.py

I think it’s still useful for things like CI

**Comment by mitzimorris** [comment]
thanks!  will correct the docs.

**Comment by mitzimorris** [comment]
> I believe you should not be running it with python3 -m, but rather just running install_cmdstan

even on Windows?
for Windows, we need to add argument `--compiler`
