### ISSUE TITLE
cmdstanpy>=1.0.2 fails to find cmdstan binary

### ISSUE THREAD

**Issue by heavywatal** [stan-dev/cmdstanpy#585]
#### Summary:
`cmdstanpy.install_cmdstan()` raises `ValueError: CmdStan installataion missing binaries.` after showing `CmdStan version 2.29.2 already installed` with `cmdstanpy>=1.0.2`.
`cmdstanpy==1.0.1` works fine.

#### Description:

```
>>> import cmdstanpy
>>> print(cmdstanpy.__version__)
1.0.3
>>> cmdstanpy.install_cmdstan()
Installing CmdStan version: 2.29.2
Install directory: /Users/watal/.cmdstan
CmdStan version 2.29.2 already installed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/watal/.pyenv/versions/3.10.4/lib/python3.10/site-packages/cmdstanpy/utils.py", line 1364, in install_cmdstan
    set_cmdstan_path(args.dir)
  File "/Users/watal/.pyenv/versions/3.10.4/lib/python3.10/site-packages/cmdstanpy/utils.py", line 167, in set_cmdstan_path
    validate_cmdstan_path(path)
  File "/Users/watal/.pyenv/versions/3.10.4/lib/python3.10/site-packages/cmdstanpy/utils.py", line 155, in validate_cmdstan_path
    raise ValueError(
ValueError: CmdStan installataion missing binaries. Re-install cmdstan by running command "install_cmdstan --overwrite", or Python code "import cmdstanpy; cmdstanpy.install_cmdstan(overwrite=True)"
```
#### Additional Information:
`import cmdstanpy; cmdstanpy.install_cmdstan(overwrite=True)` did not solve the problem.

#### Current Version:
- 1.0.3 fails
- 1.0.2 fails
- 1.0.1 works
- Python 3.10.4 and 3.7.13; with and without virtualenv

**Comment by WardBrian** [comment]
After restarting python does CmdStan function? If the problem is what I think it is, it is probably installing correctly but the error is wrong

**Comment by heavywatal** [comment]
Yes, I tried `CmdStanModel` and it works regardless of this error. I guess changes around `set_cmdstan_path()` in de0c14123887a5856f166d87d5645178e9173e6e did somthing wrong...?

**Comment by WardBrian** [comment]
Yeah, seems like the version folder got left off. 

Not the biggest issue, since it does succeed, but definitely confusing for users. I believe the command line version is unaffected by this
