### ISSUE TITLE
cmdstanpy_logger documentation

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstanpy#594]
#### Summary:

@WardBrian clued me in on how to suppress logging output, which works:

```python
import logging
cmdstanpy_logger = logging.getLogger("cmdstanpy")
cmdstanpy_logger.disabled = True
```

But I don't see documentation anywhere on that.  A Google search for `[cmdstanpy_logger site:mc-tan.org]` yields nothing other than source code.

#### Current Version:

```python
>>> csp.cmdstan_version()
(2, 30)
```

I don't know how to get the cmdstanpy version itself, but the online doc says 1.04 and I just installed.

**Comment by WardBrian** [comment]
This can be achieved with 

```python
import logging
cmdstanpy_logger = logging.getLogger("cmdstanpy")
cmdstanpy_logger.disabled = True
```

Note that this will disable all logging from cmdstanpy, not just info from sampling. If you want a more nuanced logging setup then you can instead set `cmdstanpy_logger.handlers = []` to remove the one we install by default and add your own [logging handler](https://docs.python.org/3/library/logging.handlers.html)

**Comment by bob-carpenter** [comment]
Thanks, @WardBrian.  That worked.  I'll update the issue to be about documentation.

**Comment by WardBrian** [comment]
Yeah, we don't mention our logging anywhere and definitely should. At the very least saying "We're using the official python logging module and you can control it through that" would be better than nothing

**Comment by WardBrian** [comment]
Re: versions - `cmdstanpy.show_versions()`. We should mention this in the issue template https://github.com/stan-dev/cmdstanpy/blob/develop/.github/ISSUE_TEMPLATE.md
