### ISSUE TITLE
`draws_pd` - if argument `vars` is given, order of dataframe columns should match list ordering

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#597]
#### Summary:
The order of the dataframe columns doesn't necessarily match the list ordering.

#### Description:
This is only annoying if displaying intermediate results.
But we might be able to do a better job with pandas - investigate.

#### Current Version:
v 1.0.4

**Comment by ahartikainen** [comment]
https://github.com/stan-dev/cmdstanpy/blob/5bc1040206b6a6812a6123d811480ab0323d13ff/cmdstanpy/stanfit/mcmc.py#L592

There is a trick to do this without a set

**Comment by ahartikainen** [comment]
```python
list(dict.fromkeys(vars_list))
```

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/598
