### ISSUE TITLE
Fix doc references to PyCmdStan

### ISSUE THREAD

**Issue by seantalts** [stan-dev/cmdstanpy#6]
#### Summary:
There are references (e.g. http://cmdstanpy.readthedocs.org) to pycmdstan we should change to cmdstanpy. (we might even want to change the Python module to just `cmdstan` or `stan`).

**Comment by maedoc** [comment]
#9 fixes all the stuff found by `grep -i pycmdstan -r ./`

**Comment by seantalts** [comment]
Oops, this seems like a duplicate of https://github.com/stan-dev/cmdstanpy/issues/3
