### ISSUE TITLE
How to read from csv files?

### ISSUE THREAD

**Issue by petergaoshan** [stan-dev/cmdstanpy#601]
I have saved my results by the function
```
save_csvfiles()
```
It creates a folder of csv files. How do I read these files to create another fit object?

**Comment by WardBrian** [comment]
cmdstanpy.from_csv should be able to do this for you

**Comment by petergaoshan** [comment]
> cmdstanpy.from_csv should be able to do this for you

Hi, I did 
```
import cmdstanpy
fit = cmdstanpy.from_csv('result')
```

but got the error
```
ValueError: bad Stan CSV file result/Wired_HMM-20220809065015_3.csv, expected 1000 draws, found 5000
```

Do you know how to fix it? I didn't set the draws to 1000 prior than this.

**Comment by ahartikainen** [comment]
How many csv files can be found in the result folder? Can you check the linecount?

Does `arviz.from_cmdstan("result/*.csv")` work (it will create a InferenceData object)

https://arviz-devs.github.io/arviz/getting_started/CreatingInferenceData.html#from-cmdstan
https://arviz-devs.github.io/arviz/api/generated/arviz.from_cmdstan.html

**Comment by petergaoshan** [comment]
> arviz.from_cmdstan("result/*.csv")

There are 8 csv in the folder

It gives:

```
ValueError: shape mismatch: value array of shape (5000,) could not be broadcast to indexing result of shape (1000,)
```

**Comment by ahartikainen** [comment]
Can you list the filenames?

    from pathlib import Path
    print(list(Path("result").glob("*.csv")))

**Comment by petergaoshan** [comment]
> Can you list the filenames?
> 
> ```
> from pathlib import Path
> print(list(Path("result").glob("*.csv")))
> ```

They are

```
[PosixPath('result/Wired_HMM-20220809054928_1.csv'), PosixPath('result/Wired_HMM-20220809054928_2.csv'), PosixPath('result/Wired_HMM-20220809054928_4.csv'), PosixPath('result/Wired_HMM-20220809054928_3.csv'), PosixPath('result/Wired_HMM-20220809065015_3.csv'), PosixPath('result/Wired_HMM-20220809065015_4.csv'), PosixPath('result/Wired_HMM-20220809065015_1.csv'), PosixPath('result/Wired_HMM-20220809065015_2.csv')]
```

**Comment by ahartikainen** [comment]
```
result/Wired_HMM-20220809054928_1.csv  2022-08-09 05:49:28 1
result/Wired_HMM-20220809054928_2.csv  2022-08-09 05:49:28 2
result/Wired_HMM-20220809054928_4.csv  2022-08-09 05:49:28 4
result/Wired_HMM-20220809054928_3.csv  2022-08-09 05:49:28 3
result/Wired_HMM-20220809065015_3.csv  2022-08-09 06:50:15 3
result/Wired_HMM-20220809065015_4.csv  2022-08-09 06:50:15 4
result/Wired_HMM-20220809065015_1.csv  2022-08-09 06:50:15 1
result/Wired_HMM-20220809065015_2.csv  2022-08-09 06:50:15 2
```

So you have to set of files there.

Try

    import cmdstanpy
    fit = cmdstanpy.from_csv('result/Wired_HMM-20220809054928_*.csv')
    fit2 = cmdstanpy.from_csv('result/Wired_HMM-20220809065015_*.csv')

and for ArviZ this would be 

    import arviz as az
    idata = az.from_cmdstan("result/Wired_HMM-20220809054928_*.csv")
    idata2 = az.from_cmdstan("result/Wired_HMM-20220809065015_*.csv")

**Comment by petergaoshan** [comment]
> ```
> result/Wired_HMM-20220809054928_1.csv  2022-08-09 05:49:28 1
> result/Wired_HMM-20220809054928_2.csv  2022-08-09 05:49:28 2
> result/Wired_HMM-20220809054928_4.csv  2022-08-09 05:49:28 4
> result/Wired_HMM-20220809054928_3.csv  2022-08-09 05:49:28 3
> result/Wired_HMM-20220809065015_3.csv  2022-08-09 06:50:15 3
> result/Wired_HMM-20220809065015_4.csv  2022-08-09 06:50:15 4
> result/Wired_HMM-20220809065015_1.csv  2022-08-09 06:50:15 1
> result/Wired_HMM-20220809065015_2.csv  2022-08-09 06:50:15 2
> ```
> 
> So you have to set of files there.
> 
> Try
> 
> ```
> import cmdstanpy
> fit = cmdstanpy.from_csv('result/Wired_HMM-20220809054928_*.csv')
> fit2 = cmdstanpy.from_csv('result/Wired_HMM-20220809065015_*.csv')
> ```
> 
> and for ArviZ this would be
> 
> ```
> import arviz as az
> idata = az.from_cmdstan("result/Wired_HMM-20220809054928_*.csv")
> idata2 = az.from_cmdstan("result/Wired_HMM-20220809065015_*.csv")
> ```

Oh! Thank you so much.

**Comment by mitzimorris** [comment]
@petergaoshan - just to confirm - did you do two runs of the sampler and then both times save the csv files
to the directory "result"?
did one run of the sampler have 5000 iterations total (non-default values for `iter_warmup` or `iter_sampling`?)

I think that `from_csv` could harder to detect this and throw a better error message - @ahartikainen and @WardBrian - thoughts?

**Comment by ahartikainen** [comment]
Maybe we could add option to groupby by timestamps and print a solution if multiple runs detected?

By default we probably should keep the current method, but run groupby if fail?

**Comment by mitzimorris** [comment]
if directory contains files with same ts - no problems

if directory contains files with different ts but same size and shape - warn or error?  if error, we'd want to add option 'force' to override error.

if directory contains files with different ts and different size and shape - informative error message
