### ISSUE TITLE
`compile=True` behavior with includes

### ISSUE THREAD

**Issue by tillahoffmann** [stan-dev/cmdstanpy#614]
When the `compile` argument of `CmdStanModel` is `True`, the following code checks whether a newer executable exists such that the compile step can be skipped.

https://github.com/stan-dev/cmdstanpy/blob/e885cb0edf2e611802cb36f491fa05192d4190b3/cmdstanpy/model.py#L481-L488

If the `.stan` file has an `#include` directive, compilation will be skipped if changes were made to the included file but not the `stan_file` argument passed to `CmdStanModel`. Would it be feasible to check included files as well or is that overkill, and I should just use `compile="force"`?

**Comment by WardBrian** [comment]
I think solving this in the most general cases is really tricky. In `stanc_info()` we have a list of included files, but most of them will be relative paths and you need to know the value of `--include-paths` to find them. 

I think this is the kind of thing we'd be happy to accept a PR for, but `compile='force'` will be the recommended thing for now
