### ISSUE TITLE
Optimize fail to parse the tol_grad argument

### ISSUE THREAD

**Issue by xidulu** [stan-dev/cmdstanpy#617]
Hi

I was trying to use `optimize` to acquire the map estimation of a model but when I set the tol_grad parameter:

```python
 map_estimate = model.optimize(
        data=args,
        algorithm='lbfgs',
        tol_grad=1e-20
    )
```

 a RuntimeError got raised:

```
tol_grad=1e-20 is either mistyped or misplaced.
Perhaps you meant one of the following valid configurations?
  method=optimize optimize algorithm=bfgs bfgs tol_grad=<double>
  method=optimize optimize algorithm=lbfgs lbfgs tol_grad=<double>
```

**Comment by WardBrian** [comment]
Hi -

Thanks for reporting. Can you share what versions of cmdstanpy and cmdstan are you using?

**Comment by xidulu** [comment]
@WardBrian 
Hi the cmdstanpy version is 1.01 and the cmdstan version is 2.29.2

Thanks

**Comment by WardBrian** [comment]
I'm not able to recreate this using the latest CmdStanpy with either CmdStan 2.29 or 2.30. This code doesn't seem to have changed in a very long time, either, so I'm not sure what could be causing this.

Are you using a special text encoding on your computer? Something other than ASCII or UTF-8 which could be using a special encoding for `-`, for example?

**Comment by xidulu** [comment]
ummm, this is really weird. I don't think I am using special text encoding...

Also, the `iter` argument can be parsed without trouble. But all arguments that involve float numbers would run into trouble.

FYI: I am running the code on a Linux machine, could that be the cause of the problem?

**Comment by WardBrian** [comment]
I am also running on a Linux machine, so I don’t believe so. 

If you pass the float as something like “0.00000001” rather than in scientific notation, does it work?

**Comment by xidulu** [comment]
No it doesn't...  
This is my code
```python
map_estimate = model.optimize(
        data=args,
        iter=10000,
        tol_grad=0.00001
    )
```

and this is the output:

```
tol_grad=1e-05 is either mistyped or misplaced.
Perhaps you meant one of the following valid configurations?
  method=optimize optimize algorithm=bfgs bfgs tol_grad=<double>
  method=optimize optimize algorithm=lbfgs lbfgs tol_grad=<double>
Failed to parse command arguments, cannot run model.
```

I will try to reinstall the cmdstan to see if it could help.

**Comment by bob-carpenter** [comment]
Thanks, @xidulu.  It's obviously parsing that command-line argument, because it's printing it back in scientific notation. 

I would suggest that these would be easier to debug if CmdStanPy reported which CmdStan operation was being attempted rather than just suggesting alternatives.

**Comment by bob-carpenter** [comment]
Also, I don't know if this is just for testing the argument parser, but $10^{-20}$ is several orders of magnitude smaller than machine precision for `double` types.   It might make sense if you think your problem scale is much smaller than unit scale, but otherwise, I'd recommend relaxing this tolerance.  Otherwise, you'll just run for max iterations or until the gradients underflow to 0.

**Comment by WardBrian** [comment]
> I would suggest that these would be easier to debug if CmdStanPy reported which CmdStan operation was being attempted rather than just suggesting alternatives.

Those alternatives are being suggested by CmdStan, not cmdstanpy. The failure is happening after cmdstanpy has run the model binary

**Comment by WardBrian** [comment]
Thanks for figuring that out @xidulu. We currently make sure that the algorithm isn't "newton" for that argument, but this is a hole in that check

**Comment by bob-carpenter** [comment]
> Those alternatives are being suggested by CmdStan, not cmdstanpy.

I was suggesting that when things go wrong, it could be helpful to echo the command that cmdstanpy is trying to send to cmdstan.  I don't think it makes sense to echo back suggestions on how to fix from cmdstan, as most of that parsing is not worth it.  For instance, is this even correct with `bfgs` repeated twice (still waiting for command line tools and Xcode to install, so I can't check):

```
method=optimize optimize algorithm=bfgs bfgs tol_grad=<double>
```

**Comment by WardBrian** [comment]
Nope, the correct versions are either 

```shell
./bernoulli method=optimize algorithm=bfgs tol_grad=1e-20 data file=bernoulli.data.json
```
or
```shell
./bernoulli optimize algorithm=bfgs tol_grad=1e-20 data file=bernoulli.data.json
```

So even that diagnostic is wrong, but trying to re-create it on the cmdstanpy side would be nigh on impossible. The commands are always logged if you enable debug logging, though I'm not sure that would have helped too much in debugging this
