### ISSUE TITLE
better message when failing to compile

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstanpy#618]
#### Summary:

Everything was working before, but today I get errors trying to compile a model.

#### Description:

```
>>> import cmdstanpy as csp
>>> model = csp.CmdStanModel(stan_file="~/temp2/simple.stan")
13:56:49 - cmdstanpy - INFO - compiling stan file /Users/bcarpenter/temp2/simple.stan to exe file /Users/bcarpenter/temp2/simple
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/cmdstanpy/model.py", line 214, in __init__
    raise ValueError(
ValueError: Unable to compile Stan model file: /Users/bcarpenter/temp2/simple.stan.
```

#### Additional Information:

If I try to compile directly from cmdstan, it's clear right away that the problem is that Xcode hasn't been activated for command-line tools on my Mac.  

```
~/github/stan-dev/cmdstan$ make ~/temp2/simple.stan 


You have not agreed to the Xcode license agreements. You must agree to both license agreements below in order to use Xcode.
```

But this wasn't at all apparent from the CmdStanPy error.

Also, it took some digging to remind myself how to do this from the command line, but this worked:

```
sudo xcodebuild -license accept
```

which kicked off a dialog box to do some further installs.  These took a long time (10+ minutes).

#### Current Version:

> Please include the output of `cmdstanpy.show_versions()`, or
at least the cmdstan and cmdstanpy versions used.

This instruction is confusing because it doesn't work if you follow the tutorial instructions.

```python
>>> cmdstanpy.show_versions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'cmdstanpy' is not defined
```

That's because I'd used what seems more standard to me, namely

```python
import cmdstanpy as csp
```

in which case I needed to do this

```python
csp.show_versions()
```

which returns

```
INSTALLED VERSIONS
---------------------
python: 3.9.4 (default, Apr  5 2021, 01:47:16) 
[Clang 11.0.0 (clang-1100.0.33.17)]
python-bits: 64
OS: Darwin
OS-release: 21.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
cmdstan_folder: /Users/bcarpenter/.cmdstan/cmdstan-2.30.0
cmdstan: (2, 30)
cmdstanpy: 1.0.4
pandas: 1.4.3
xarray: None
tdqm: None
numpy: 1.21.4
ujson: 5.4.0

' '
```

Should we also suggest to do the import before running the command?

**Comment by WardBrian** [comment]
This is because `compile` tries to break down what the error is rather than outputting the entirety of stdout/stderr unconditionally on failure: https://github.com/stan-dev/cmdstanpy/blob/1c761ff7a1c0e597f6d67d28645432533276016e/cmdstanpy/model.py#L548

This is not great, in my opinion, because it means errors we don't think about in advance get swallowed entirely


Re: `show_versions`; I think it would be fine to change the text to `import cmdstanpy; cmdstanpy.show_versions()`. Most of our doc is written such that you import specific things from cmdstanpy, which I don't love. I'd never seen `csp` before, though

**Comment by bob-carpenter** [comment]
> I think it would be fine to change the text to import cmdstanpy; cmdstanpy.show_versions().

Sounds good.

> I'd never seen csp before, though

Any better suggestion for a two or three character abbreviation for CmdStanPy?  I just chose the capitalized letters.

**Comment by WardBrian** [comment]
This is one of the few packages that I personally import as itself, rather than trying to abbreviate.

**Comment by ahartikainen** [comment]
Same here, I only use some specific functionality with cmdstanpy so no need to make it shorter.
