### ISSUE TITLE
Temporary files are not auto cleaned (multiprocessing)

### ISSUE THREAD

**Issue by HanlinGao** [stan-dev/cmdstanpy#642]
#### Summary:
Temporary files created in Linux /tmp are not cleaned

#### Description:
I have noticed that cmdstanpy will clean temporary files theoretically, but it seems not work for my situation. I have a pandas.dataframe containing multiple time series, and I ran a prophet model on each time series via a parallel_apply on each group. And it created many temporary files in my /tmp directory with a filename like 'tmpw3yuel_7/prophet_model00i.../prophet_model-timestamp-stdout.txt' and 'prophet_model-timestamp.csv'
So I wonder what will cause the auto-clean of temporary files to fail?

#### Additional Information:
the python script is run in a tmux session, will it have effect on this problem?

#### Current Version:
cmdstanpy 1.0.8
prophet 1.1.1
pandarallel 1.6.3

**Comment by WardBrian** [comment]
We use atexit to clean up this temporary directory:
https://github.com/stan-dev/cmdstanpy/blob/1612c0496555a7718f1c45e9d0ffe30bd9fafc7a/cmdstanpy/__init__.py#L16-L21

It's hard to predict exactly what could be causing this without a reproducible example, but my guess is probably that cmdstanpy is being imported fresh in each process but the atexit is not being run for some reason.

**Comment by HanlinGao** [comment]
> We use atexit to clean up this temporary directory:
> 
> https://github.com/stan-dev/cmdstanpy/blob/1612c0496555a7718f1c45e9d0ffe30bd9fafc7a/cmdstanpy/__init__.py#L16-L21
> 
> It's hard to predict exactly what could be causing this without a reproducible example, but my guess is probably that cmdstanpy is being imported fresh in each process but the atexit is not being run for some reason.

Hi, I can give an easy reproducible example, which I have tested on my Linux remote server.
```
import pandas as pd
from prophet import Prophet
from pandarallel import pandarallel
import numpy as np

data = pd.DataFrame({
        'id': ['a', 'a', 'a', 'b', 'b', 'b'],
        'ds': list(pd.date_range('2022-11-1', '2022-11-3')) * 2,
        'y': np.random.random(6)
})

def f(subdf):
    model = Prophet()
    model.fit(subdf[['ds', 'y']])
    return

# successfully auto-cleaned tmp* files in /tmp directory
data.groupby('id').apply(f)

# unsuccessfully auto-cleaned tmp* files in /tmp directory
pandarallel.initialize(nb_workers=2)
data.groupby('id').parallel_apply(f)
```

after `apply`, I checked the /tmp directory, there were no tmp* files remained, while after `parallel_apply`, I found tmp* were all kept

**Comment by WardBrian** [comment]
It seems that atexit and multiprocessing are intentionally not compatible, which is unfortunate. See: https://stackoverflow.com/a/34507557

I’m not sure what we could do instead, but I think in the mean time calling cmdstanpy._cleanup_tmpdir() inside your forked function may have the desired effect

**Comment by HanlinGao** [comment]
> 

Thanks a lot!

**Comment by WardBrian** [comment]
I am reasonably certain we can't fix this. The fact that `atexit` does not work with `multiprocess` seems to me a poor design choice, and it is one that is really difficult to work around. 

There are packages such as [`multiexit`](https://github.com/kuralabs/multiexit) which try to fix this, but they require running some code _before_ any subprocesses are spawned, which we can't _make_ happen.

For example, this issue would still be around if we used multiexit and a user wrote code like:

```python
def f():
    import cmdstanpy # this means cmdstanpy is not imported on the main process, so the code can't run!
    ...

# use f in multiprocess
```
