### ISSUE TITLE
Seed argument doesn't accept np.int types

### ISSUE THREAD

**Issue by AidanMar** [stan-dev/cmdstanpy#647]
#### Summary:

ValueError: Argument "seed" must be an integer between 0 and 2**32-1, found 76113.

I believe that  76113 < 2**32-1 (= 4294967295)

Any help?

#### Current Version:
cmdstan                   2.29.0              
cmdstanpy                 1.0.8

**Comment by AidanMar** [comment]
Never mind. I was using 

```
rng = np.random.default_rng(42)
seed = rng.integers(low=0, high=1e7)
```
to generate seeds for a sequence of models that I was fitting. The assigned seed variable in this case turned out to be numpy.int64, and not a python builtin integer.

**Comment by WardBrian** [comment]
I think this is a worthy report anyway, we should probably allow np.int* types in this check. Thanks!

**Comment by bob-carpenter** [comment]
The actual initialization used by the pseudo-RNG is an unsigned 32-bit int.  Which is odd, because I think the intermediate state is 128 or 256 bits.  While we could just truncate larger integers down, I think it'd be confusing because then two different RNG inputs could produce the same output.
