### ISSUE TITLE
[CmdStan 2.32] Add method `laplace_sample`

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/cmdstanpy#649]
See https://github.com/stan-dev/cmdstan/pull/1134

Also added: `jacobian` flag for optimization.

**Comment by WardBrian** [comment]
Note: Once argument `jacobian` is available for optimization, the class `CmdStanMLE`'s name is incorrect

**Comment by mitzimorris** [comment]
is there a way to change a class name or introduce a new one while maintaining backwards compatibility?
if so, what is the best new name?   CmdStanOPTM ?

**Comment by WardBrian** [comment]
I think you can do something like

```python

class NewName:
    ... # all logic

class OldName(NewName):
    def __init__(self, *args, **kwargs):
        warnings.warn("Deprecated")
        super().__init__(*args, **kwargs)
```

**Comment by WardBrian** [comment]
See CmdStanR design discussion:
https://github.com/stan-dev/cmdstanr/issues/760#issuecomment-1516609693
