### ISSUE TITLE
Automatic include-path specification interacts poorly with spaces in filepaths

### ISSUE THREAD

**Issue by WardBrian** [stan-dev/cmdstanpy#659]
#### Summary:

```shell
mkdir "space in directory name"
cd "space in directory name"
touch foo.stan
echo "#include foo.stan" > bar.stan
cd ..
python -c 'import cmdstanpy; cmdstanpy.CmdStanModel(stan_file="./space in directory name/bar.stan")'
```

For me this fails with 

```
Command ['make', 'STANCFLAGS+=--include-paths=/home/brian/Dev/py/cmdstanpy/space in directory name', '/tmp/tmp9q5etflx/tmp9r9gf0ec']
        error during processing No such file or directory
```
due to the include path argument being interpreted as passing multiple model files at once,
but another user reported to me that they get an error from stanc about specifically not finding the `#include`d file.

I don't see an obvious fix for this in general, since even determining if files are `#include`d relies on us using stanc.

#### Current Version:

cmdstan: (2, 31)
cmdstanpy: 1.1.0
OS: Ubuntu 20.04. I believe on Windows this results in different behavior (but still fails!)

**Comment by ahartikainen** [comment]
Windows could use the shortpath (dos path) trick but this must be handled correctly (with "" or '' not sure if Windows supports both?)

Who creates that path for make call? And is it make that fails?

**Comment by WardBrian** [comment]
I believe it is Stanc that fails. We automatically include the model directory as an include path, so it’s cmdstanpy which is generating it
