### ISSUE TITLE
C++ toolchain - install instructions or lightweight download?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#66]
#### Summary:
CmdStanPy provides script `install_cmdstan` but that depends on already having a C++11 (or higher?) compiler installed.   Investigate how to automate toolchain install and/or provide platform-specific foolproof step-by-step instructions

#### Description:
Installation has always been a huge pain point for non-programmers, which is the category that many working statisticians and data analyists fall into.  For them, we need a painless install experience.

**Comment by mitzimorris** [comment]
what is the best way to test these?  Travis on a suite of machines?  AWS instances?

**Comment by mitzimorris** [comment]
ideally, this would be available to CmdStan users as well.

**Comment by wsuchy** [comment]
I am afraid that this is highly platform dependent. Most of linux distributions (Ubuntu, Fedora, etc) should have GCC present by default whereas OSX is using Xcode that needs to be installed via AppStore (Clang, see: https://github.com/stan-dev/rstan/wiki/RStan-Mojave-Mac-OS-X-Prerequisite-Installation-Instructions). It looks like Windows installation requires also mingw32.
Maybe it would be worth considering to support Docker based compiling and running of the model?

**Comment by mitzimorris** [comment]
chicken and egg problem - asking non-programmers to install docker seems equally daunting.

but yes, Docker is an option - see https://github.com/stan-dev/cmdstanpy/issues/25

**Comment by ahartikainen** [comment]
I think we could something similar as conda have and have an option to use our "own" compilers. They could go in `.cmdstanpy` etc and would be used by hardcoded `CC` and `CXX` in `make/local`.

Would it be the best use `clang` on all platforms? Clang on windows could use mingw libs (`mingw-w64`, no `mingw32`)?

**Comment by mitzimorris** [comment]
this would be a good option for CmdStan and is along the lines of what I was imagining.
perhaps we should move this issue to CmdStan?

downside, the CmdStan tarball is already quite large.  however I remember someone looking into the size of just the C++ compiler and it wasn't that large.

**Comment by bob-carpenter** [comment]
Various people have wrapped various chunks of interfaces into Docker.   For an end user, the big question is how much of their R/Python, etc. environment to also encapsulate.

@ariddell created completely encapsulated containers that ran PyStan, RStan, and JuliaStan through Jupyter.

**Comment by ahartikainen** [comment]
Docker is nice and future. Not all machine have docker and it needs admin rights, which is not optimal.

**Comment by mitzimorris** [comment]
this is a duplicate of #7 - see discussion there.
