### ISSUE TITLE
cmdstanpy still attempts to contact github.com even when cmdstan is already installed

### ISSUE THREAD

**Issue by grantsohn** [stan-dev/cmdstanpy#672]
#### Summary:
cmdstanpy still attempts to contact github.com even when cmdstan is already installed

#### Description:
This is to address software companies that is building cmdstanpy in CI where no outbound internet access is allowed due to security.
When trying to leverage an existing cmdstan, the cmdstanpy is failing despite there being a preinstalled version of cmdstan.
#### Additional Information:
This is happening while building orbit-ml which requires cmdstan 2.31.0.

To reproduce, do the following:
Download the orbit-ml-1.1.4.2.tar.gz
```
tar -xzvf orbit-ml-1.1.4.2.tar.gz
cd orbit-ml-1.1.4.2
# first time to install cmdstan
python3 setup.py build 
rm -rf orbit_ml.egg-info/
# turn off Wi-Fi or network
python3 setup.py build 

```
You should see:

```
No `name` configuration, performing automatic discovery
running build
running build_py
Importing cmdstanpy...
Installing cmdstan...
checking version 2.31.0 availability, retry (1/5)
checking version 2.31.0 availability, retry (2/5)
checking version 2.31.0 availability, retry (3/5)
checking version 2.31.0 availability, retry (4/5)
checking version 2.31.0 availability, retry (5/5)
Release 2.31.0 is unavailable from URL https://github.com/stan-dev/cmdstan/releases/download/v2.31.0/cmdstan-2.31.0.tar.gz
URLError: [Errno 8] nodename nor servname provided, or not known
10:45:23 - cmdstanpy - WARNING - CmdStan installation failed.
Version 2.31.0 cannot be downloaded. Connection to GitHub failed. Check firewall settings or ensure this version exists.
CmdStan installation failed.
Version 2.31.0 cannot be downloaded. Connection to GitHub failed. Check firewall settings or ensure this version exists.
```

#### Current Version:
Requirements say cmdstanpy>=1.0.4 and I'm using cmdstanpy 1.1.0.

**Comment by grantsohn** [comment]
Another consideration is to revisit https://github.com/stan-dev/cmdstanpy/issues/227#issuecomment-699565045 and a release_url parameter.

**Comment by bob-carpenter** [comment]
Thanks, @grantsohn.  This sounds like a really useful patch and I hope @mitzimorris can review it (she's doing most of the CmdStan maintenance these days).

**Comment by grantsohn** [comment]
Thanks @WardBrian for quick turn around!
