### ISSUE TITLE
draws_pd() should include chain, iteration, and draw columns

### ISSUE THREAD

**Issue by roualdes** [stan-dev/cmdstanpy#676]
#### Summary:
The method `draws_pd()` on a `cmdstanpy.CmdStanMCMC` object is analogous to CmdStanR's method `draws(..., format = "df")`.  CmdStanR also returns columns containing indices for chain, iteration, and draw, where chain indexes each chain, iteration indexes draws witihin each chain, and draw indexes across the chains.

It would be nice if `draws_pd()` gave such columns in the returned Pandas dataframe. 

#### Additional Information:

Assuming chains are stacked into a Pandas dataframe, It would probably be easiest to add two columns (chain and iteration) to each chain, stack the chains, and then add the column draw to the dataframe.  

#### Current Version:
```
cmdstanpy.show_versions()
INSTALLED VERSIONS
---------------------
python: 3.11.3 (main, Apr  7 2023, 19:29:16) [Clang 14.0.0 (clang-1400.0.29.202)]
python-bits: 64
OS: Darwin
OS-release: 21.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
cmdstan_folder: /Users/ez/.cmdstan/cmdstan-2.32.2
cmdstan: (2, 32)
cmdstanpy: 1.1.0
pandas: 2.0.3
xarray: 2023.6.0
tqdm: 4.65.0
numpy: 1.23.5
```

**Comment by WardBrian** [comment]
I think this is relatively simple - I started a branch here: https://github.com/stan-dev/cmdstanpy/tree/feature/676-pandas-columns/

**Comment by roualdes** [comment]
Differentiating parameter columns from other columns via extra chars in the column names might be good.  CmdStanR names these `.draw`, `.iteration`, and `.chain`.  That doesn't seem to work in Python since Pandas allows method like dot access to columns.  All other diagnostics (plus `lp__`) in `draws_pd()` append two underscores.  What do you think?

**Comment by mitzimorris** [comment]
the indexes are implicit in the way that we flatten the chains.

**Comment by roualdes** [comment]
Right, so this is just a request to make the indexes explicit as CmdStanR does.   Are there any objections to making the indexes explicit?
