### ISSUE TITLE
Read Stan csv to StanFit

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#68]
We need (or do we have this already) a function that can take a list of (stan) csv and outputs StanFit.

**Comment by mitzimorris** [comment]
we don't have this function.
per the refactor-in-progress - https://github.com/stan-dev/cmdstanpy/tree/feature/57-api-refactor

such a function would have to create a StanFit object, set attributes `csv_files`, and then call method `_validate_csv_files` -

see unit tests:

https://github.com/stan-dev/cmdstanpy/blob/ffbe08aed2c8cd4c313d2a72779c6b075cebadf6/test/test_stanfit.py#L40

and 

https://github.com/stan-dev/cmdstanpy/blob/ffbe08aed2c8cd4c313d2a72779c6b075cebadf6/test/test_stanfit.py#L87

**Comment by ahartikainen** [comment]
I hacked this together, which is fine

    from cmdstanpy import StanFit
    from cmdstanpy.model import CmdStanArgs, SamplerArgs
    
    args = CmdStanArgs(
                "dummy.stan", "dummy.exe", list(range(1, 5)), method_args=SamplerArgs()
    )
    obj = StanFit(args)
    obj.csv_files = filepaths
    obj._validate_csv_files() 
    obj._assemble_sample()

https://github.com/arviz-devs/arviz/blob/master/arviz/tests/test_data_cmdstanpy.py

I don't think we currently need more advanced functionality.
