### ISSUE TITLE
draws_pd() option to exclude transformed parameters and/or generated quantities

### ISSUE THREAD

**Issue by roualdes** [stan-dev/cmdstanpy#680]
#### Summary:
The method draws_pd() on a cmdstanpy.CmdStanMCMC object defaults to all parameters, transformed parameters, and generated quantities.  A nice feature would be the option to exclude transformed parameters and/or generated quantities.

#### Current Version:
```
INSTALLED VERSIONS
---------------------
python: 3.11.3 (main, Apr  7 2023, 19:29:16) [Clang 14.0.0 (clang-1400.0.29.202)]
python-bits: 64
OS: Darwin
OS-release: 21.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
cmdstan_folder: /Users/ez/.cmdstan/cmdstan-2.32.2
cmdstan: (2, 32)
cmdstanpy: 1.1.0
pandas: 2.0.3
xarray: 2023.6.0
tqdm: 4.65.0
numpy: 1.23.5
```

**Comment by WardBrian** [comment]
I don't think we always have the knowledge of where the different output columns came from. _If_ we have access to the source code of the model, we can get it from `src_info()`, but if all we have is some output CSVs I don't think this information is encoded in them.

`draws_pd` does accept the `vars` argument, so if you have a (small-ish) list of parameters it should be reasonable to just pass them there to filter out as needed

**Comment by roualdes** [comment]
Sounds good.  OK to close by me.
