### ISSUE TITLE
cmdstanpy hello world doc (maybe others) uses old array syntax that now errors

### ISSUE THREAD

**Issue by jgabry** [stan-dev/cmdstanpy#694]
Just noticed this while demonstrating cmdstanpy in the Stan workshop I'm currently teaching (posting this now during my lunch break so I don't forget later!). As of today the doc still has array syntax that would result in errors if using the latest CmdStan (we need to fix this in cmdstanr too). For example, the Stan model in 

https://mc-stan.org/cmdstanpy/users-guide/hello_world.html

uses `int<lower=0,upper=1> y[N]`, so any user trying that hello world example with the latest CmdStan will get an error.

**Comment by WardBrian** [comment]
Thanks. I think all of the other examples are code that we actually run in the docs, so they were updated at one point.

Unfortunately the built web pages won't update until we do our next release.
