### ISSUE TITLE
add docs example for pathfinder

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#701]
#### Summary:
Add example notebook for Pathfinder to docs.

**Comment by mitzimorris** [comment]
the output from running Pathfinder (or something it calls) is a tad confusing - one run of multi-path Pathfinder runs 4 chains, but console message looks like it only ran one chain - change wording?


<img width="944" alt="pathfinder_cmdstanpy" src="https://github.com/stan-dev/cmdstanpy/assets/5466612/a0518fda-eb88-4ae5-aca3-309031ca2160">

**Comment by mitzimorris** [comment]
also updating wording in `variational` notebook example, since there's now 2 variational methods as part of this issue.
noticed that there's links to `readthedocs.io` instead of `mc-stan.org/cmdstanpy`.    fix everywhere or file a separate issue?

**Comment by WardBrian** [comment]
The "Chain [1]" label comes from https://github.com/stan-dev/cmdstanpy/blob/2cf6120ce82cbd218dba5e801887149742a6f691/cmdstanpy/model.py#L2038

Party of the patchy logic to make our fake multi chain look like the real multiple-chains-single-process

**Comment by mitzimorris** [comment]
- the User's Guide is stale - needs work.
- we need examples for the Laplace method as well.

**Comment by mitzimorris** [comment]
@WardBrian - we're planning to do a 1.2 release before doing a 2.0 release, correct?

started work for this issue here:  https://github.com/stan-dev/cmdstanpy/tree/docs/701-pathfinder

should I generalize this issue (and rename accordingly) to make this a docs update for everything in 1.2?

**Comment by WardBrian** [comment]
What else needs updating besides the changelog (already in #691)?

**Comment by mitzimorris** [comment]
I'm checking the .rst and .ipynb notebooks in folder docsrc/users-guide - I'm not sure they're all up-to-date.  do we want to document `laplace` method in the users guide?  it's a very minor feature.

**Comment by WardBrian** [comment]
I think just the API documentation on laplace is probably sufficient. Of course, more documentation is never a bad thing
