### ISSUE TITLE
Question: Run `compile_example` in call to `install_cmdstan` even if already installed?

### ISSUE THREAD

**Issue by tillahoffmann** [stan-dev/cmdstanpy#703]
The `install_cmdstan` script verifies the installation by calling `compile_example` after (re)-building `cmdstan`. Should we also call it after identifying that `cmdstan` is already installed to check the installation is functional (or add a flag to compile the example if `cmdstan` is already installed)? The main motivation is that sometimes the existing installation breaks, e.g., due to precompiled header changes.

**Comment by WardBrian** [comment]
I think this is a good idea

**Comment by tillahoffmann** [comment]
Alright, will put together a PR. Preference for

- always run `compile_example`
- don't run `compile_example` by default but add a flag to run it
- run `compile_example` by default but add a flag to not run it?

**Comment by WardBrian** [comment]
I think it is fine to always do it. We may want to check if the executable exists and delete it first
