### ISSUE TITLE
extraneous advice on show_console=True

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstanpy#706]
#### Summary:

Even when I've set `show_console = True` in the call, if there's a divergence, I still see

```
Consider re-running with show_console=True if the above output is unclear!
```

#### Description:

Check if it's already set to `True` before advising user to set it to `True` so we don't see this message if the flag is already set.

#### Current Version:

```
INSTALLED VERSIONS
---------------------
python: 3.9.4 (default, Apr  5 2021, 01:47:16) 
[Clang 11.0.0 (clang-1100.0.33.17)]
python-bits: 64
OS: Darwin
OS-release: 22.6.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
cmdstan_folder: /Users/bcarpenter/.cmdstan/cmdstan-2.33.1
cmdstan: (2, 33)
cmdstanpy: 1.1.0
pandas: 2.0.3
xarray: 2023.1.0
tqdm: 4.64.0
numpy: 1.25.0

' '
```

**Comment by WardBrian** [comment]
Good suggestion, I've Incorporated this into a collection of other changes we're making before the next release in #691
