### ISSUE TITLE
doc for generate_quantities function argument mcmc_sample

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstanpy#710]
#### Summary:

There's no doc for the argument `mcmc_sample` to the function `generate_quantities`.  There's only a signature.

See:  https://mc-stan.org/cmdstanpy/api.html#cmdstanpy.CmdStanModel.generate_quantities

#### Current Version:

1.2.0 doc

**Comment by WardBrian** [comment]
`mcmc_sample` is the deprecated name for `previous_fit` which will be removed in the next release

**Comment by bob-carpenter** [comment]
OK, then not much point in documenting it now!
