### ISSUE TITLE
Scopes of Runset are inconsistent among stanfit classes

### ISSUE THREAD

**Issue by lucidfrontier45** [stan-dev/cmdstanpy#719]
#### Summary:
Scopes of Runset are inconsistent among stanfit classes

#### Description:
CmdStanGQ, CmdStanMCMC, CmdStanMLE and CmdStanVB hold a Runset as `self.runset`.
CmdStanLaplace and CmdStanPathfinder hold it as `self._runset`.

Are there any intention that Runset is private in Laplace and Pathfinder?
Can I submit a Pull Request to change all of them to public `self.runset`?

#### Current Version:
1.2.0

**Comment by WardBrian** [comment]
I think it not being public currently is unrelated. Generate quantities just isn't that interesting for those algorithms

**Comment by lucidfrontier45** [comment]
https://github.com/stan-dev/cmdstanpy/blob/535c4e6d666f514b0860c49545ae3cbada86168f/cmdstanpy/model.py#L1280

As you can see the `generate_quantities`  is accessing `previous_fit.runset`. I expect when generate_quantities for Laplace and Pathfinder is implemented, the `runset` field of those two fit classes will also be public. I close this issue and wait until then.
