### ISSUE TITLE
The performance of map_rect function

### ISSUE THREAD

**Issue by Jinyin-Hu** [stan-dev/cmdstanpy#720]
#### Summary:
Please provide a short couple sentence summary.
It seems the map_rect function does not work as the way I expected. is there anything wrong with the way I used? Thanks.

#### Description:
Describe the issue as clearly as possible.
My problem involves intensive computation. And reduce map function didn't help much so I have to try map_rect. In my code, I broken the dataset into 21 shards. There are 4 chains, and I set 21 threads per chain. On HPC, i used 96 cpus to run the code. But only ~40% cpu used. 

####The main script#####
from cmdstanpy import CmdStanModel

stan_file = 'test.stan'
data_file = 'data.json'

model = CmdStanModel(stan_file=stan_file, cpp_options={'STAN_THREADS':'True' }, force_compile=True)

fit = model.sample(data=data_file, iter_warmup=150, iter_sampling=1000, adapt_delta=0.97, \
    save_warmup=True, show_progress=True, show_console=True, seed=20001,chains=4, parallel_chains=4, threads_per_chain=21, max_treedepth=20)
fit.save_csvfiles(dir='output_test')

print (fit.summary())
print (fit.diagnose())
################
<img width="810" alt="Screen Shot 2023-12-06 at 11 05 31 PM" src="https://github.com/stan-dev/cmdstanpy/assets/80732143/7d352c89-0231-4701-86e0-caca6e7ddcd8">

<img width="599" alt="Screen Shot 2023-12-06 at 11 06 21 PM" src="https://github.com/stan-dev/cmdstanpy/assets/80732143/e65499a7-2424-424f-8ccd-5fd3951613cd">

<img width="632" alt="Screen Shot 2023-12-06 at 11 06 37 PM" src="https://github.com/stan-dev/cmdstanpy/assets/80732143/2a2a6458-6af0-448f-b90f-ee75eafbe914">

#### Additional Information:
Provide any additional information here.

#### Current Version:
Please include the output of `import cmdstanpy; cmdstanpy.show_versions()`, or
at least the cmdstan and cmdstanpy versions used.
cmdstanpy 1.2.0
cmdstan 2.33.1

**Comment by WardBrian** [comment]
If there is an issue here I believe it would be tied to the Math library rather than cmdstanpy. But it's also possible that there just isn't enough work to saturate all those threads

**Comment by bob-carpenter** [comment]
You might want to see if running only a single chain speeds up with the cluster compared to a single chain on your PC.

There are all kinds of things that can get in the way on a big cluster, like I/O bottlenecks in the output and most importantly memory contention and thread contention (because 4 chains with multiple threads per chain might take over the number of cores you have).

**Comment by Jinyin-Hu** [comment]
Hi @bob-carpenter for a update, I tested it with only one chain and reduce the number of sampling to 200. It took 1 hour 17 mins without any parallel computing on HPC, and took 21 mins using map-rect function with 21 shards. So I think it works with only one chain. And the reason I chose 21 shards is that I used data ( time series ) from 7 instruments with 3 channels each. I assume all 21 channels are independent. when trying multipule chains, one thing confused me. if cross-chains multi-threading and within-chain multi-threading can work at the same time? e.g., I set the parallel_chains=chains, threads_per_chain=21. If both them apply, are these parallel chains from single one process, or individual process? I noticed there is one parameter in sample, force_one_process_per_chain. so far, it is set None by default. Should I change it to 'True' when runing multiple chains and within-chain parallelization? This confused me because I did not figure out by reading the documentation and examples. Many thanks.

**Comment by bob-carpenter** [comment]
Thanks for the update.

> if cross-chains multi-threading and within-chain multi-threading can work at the same time? 

I think so, but I'm not 100%, so I'd like to hear from @SteveBronder.  

The problem may just be thread lock contention and/or memory contention.  Everything in Stan winds up going back to CPU to save, etc.

**Comment by Jinyin-Hu** [comment]
Thanks @bob-carpenter @WardBrian , I just tried an extra test of 2 chains in seperate processes (ie, force_one_process_per_chain=True). cross-chain and within-chain multi-threading can work at the same time. The walltime is 41 mins with 48 cpus. Compared with the  previous test of only one chain with 24 cpus which took 21 mins, it didn't improve in terms of the computational cost for my case. I agree with @bob-carpenter thread lock contention and/or memory contention could be the reason. Actually, hours cost is not that bad for me because we are not doing something with real-time analysis. Thanks.
