### ISSUE TITLE
JSON Encoding of data is too slow

### ISSUE THREAD

**Issue by csmarchbanks** [stan-dev/cmdstanpy#733]
#### Summary:
In version 1.0.8 of cmdstanpy `ujson` support was removed causing significant CPU usage and time spent serializing data to JSON. It would be nice if the CPU time spent writing data to disk was reduced back to the 5% goal from https://github.com/stan-dev/cmdstanpy/issues/38.

#### Description:
We were profiling the performance of a workload using cmdstanpy and saw that 20+% of CPU for a production workload is spent serializing data to JSON via `write_stan_json`.

#### Additional Information:
There is excellent background information in https://github.com/stan-dev/cmdstanpy/issues/38 on the performance of writing JSON, as well as in https://github.com/stan-dev/cmdstanpy/pull/623 for why `ujson` was removed.

#### Current Version:
cmdstanpy = 1.1.0, but was introduced in 1.0.8.

**Comment by WardBrian** [comment]
Can you provide some (possibly fake) data which I can use for benchmarking when I look into this?

Partially the issue is that as Stan has gained new features (complex numbers, tuples, etc), the overhead for serialization has increased since these need bespoke representations in JSON

**Comment by WardBrian** [comment]
@csmarchbanks could you try running `python -m pip install stanio==0.5.0 ujson` (ignore any warnings about version incompatibilities for now) and see if you notice any improvement for your case?

**Comment by csmarchbanks** [comment]
Will do, I will look into if I have a good dataset that can be shared as well!

Thank you for the quick response.

**Comment by WardBrian** [comment]
You may also need cmdstanpy 1.2, I don't think 1.1 was depending on the `stanio` package yet

**Comment by csmarchbanks** [comment]
Initial results show ~65% reduction in the amount of time spent in `write_stan_json`! I will try to check again in the workload we saw taking 20% of time once the update is deployed, this workload only took 10% (now 3.5%).

**Comment by csmarchbanks** [comment]
The next environment shows ~5% of CPU time spent in writing files now, so significantly improved as well. As discussed in the previous issue that seems like a reasonable enough value. Thanks again and I will close this!
