### ISSUE TITLE
add parallel options for multi-path pathfinder

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstanpy#738]
#### Summary:

It wold be nice to be able to run multi-path Pathfinder in parallel using multiple threads.

#### Current Version:

CmdStanPy 1.2.1

**Comment by WardBrian** [comment]
One can do this now, but it is a bit manual:

1. Compile the model with `{'STAN_THREADS':1}` as a cpp_option
2. Set `os.environ['STAN_NUM_THREADS'] = number_of_desired_threads`

Then, running pathfinder as normal should work as intended. 

What would the desired API be here? A `num_threads` argument to `pathfinder()`? Would we want it to error if the model wasn't compiled with threading?

**Comment by bob-carpenter** [comment]
I think we just need to add that to the Pathfinder doc.  If it were there, I would've found it.
