### ISSUE TITLE
Compile flag deprecation presents problems for reformatting code

### ISSUE THREAD

**Issue by bamarco** [stan-dev/cmdstanpy#739]
#### Summary:
Deprecating the compile flag in the CmdStanModel constructor will make reformatting code impossible unless proper precautions are taken.

#### Description:
There is an upcoming deprecation for the compile flag in the CmdStanModel(compile=...) constructor. If you are unable to set compile=False you will be unable to reformat deprecated code before an error is thrown. Just wanted to make sure whoever is updating the constructor makes sure to at least provide a stand alone function for reformatting code.

```
cmdstanpy - WARNING - CmdStanModel(compile=...) is deprecated and will be removed in the next major version. The constructor will always ensure a model has a compiled executable.
If you wish to force recompilation, use force_compile=True instead.
```

#### Current Version:
Please include the output of `import cmdstanpy; cmdstanpy.show_versions()`, or
at least the cmdstan and cmdstanpy versions used.
cmdstanpy version 1.2.1

**Comment by WardBrian** [comment]
This will be moved to a function independent of the `CmdStanModel` object, like compilation itself has already been. Good catch though, we might want to do this as a 1.2.2 or something before the jump to 2.x
