### ISSUE TITLE
Use logging module instead of print

### ISSUE THREAD

**Issue by wsuchy** [stan-dev/cmdstanpy#74]
#### Summary:
Currently we log our messages via `print` method call which makes it impossible to control it
#### Description:
Logging should be done using `import logging` (the same way as in `fbprophet`)

**Comment by bob-carpenter** [comment]
I think it'd be great.  We need to sort messages into log levels.  Then if this is like other logger interfaces, we can separately control level of output or even format of output to the console and to file.

There's a long-term plan to convert Stan's C++ output to use logging at the Stan language and algorithms level (`stan-dev/stan`).  But there's no design in place yet.  The math library (`stan-dev/math`) doesn't use messages---it just works or throws exceptions.

For CmdStanPy, the issue will be how to wrap CmdStan's shell output (just to stdout, I think, but maybe also to stderr).  Many of them could be filtered by content using simple pattern matching and then assigned different logging levels.  I'm specifically thinking of things like the refreshed iteration feedback vs. warnings/error diagnostics vs. the final "I'm done" report with timing.

**Comment by ahartikainen** [comment]
@bob-carpenter I think that is the long-term goal.

For the short-term, the output from Python should be changed from print to logging. This is done in PyStan too.
