### ISSUE TITLE
CmdStanPy docs - add OpenGraph tags?

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#746]
#### Summary:

Discourse won't show preview of CmdStanPy docs because of lack of OpenGraph tags.
When linking to CmdStanPy docs in Discourse post, the UI shows this warning

![discourse_wtf](https://github.com/stan-dev/cmdstanpy/assets/5466612/4d395f38-d681-4cc4-bbad-8e11ab11dc9d)

The fix would be to use OpenGraph, but is this worth it?   Links without preview work just fine.

#### Description:

from Discourse:  https://meta.discourse.org/t/unable-to-generate-a-preview-for-this-web-page-because-the-following-oembed-opengraph-tags-could-not-be-found-description-image/276711

from SO:  https://stackoverflow.com/questions/70947883/how-to-set-opengraph-metadata-tags-for-a-sphinx-document

**Comment by WardBrian** [comment]
The second link you posted seems to imply we could use [`sphinxext-opengraph`](https://github.com/wpilibsuite/sphinxext-opengraph) in our doc's `conf.py` with some minimal config. 

I've not previously had any issues on the forums however. I think this just means it doesn't create a full-width banner style preview, but those are also often annoying when you're just trying to make a link

**Comment by mitzimorris** [comment]
> I think this just means it doesn't create a full-width banner style preview, but those are also often annoying when you're just trying to make a link

agreed - the so-called "preview" feature is annoying and usually useless as well.

closing this as won't fix - the cost of adding more config and sphinx dependencies isn't worth it.
