### ISSUE TITLE
fit.runset references non-existent *profile*.csv (with STAN_THREADS enabled)

### ISSUE THREAD

**Issue by Garren-H** [stan-dev/cmdstanpy#750]
Hi all

I ran a simple 2 chain sampler to test out the usage of profile. According the the cmdstanpy docs it says that the profile csv gets the a similar name as that of the output csv but with "profile-<chain_ID>" appended (or something like this). I have implemented this and the the actual output gets merged into a single .csv file without the <chain_ID> appended when running with `STAN_THREADS=True` (I have not tested this with `STAN_THREADS=False`). When running `fit.runset` however, the profile csv referenced has chain_ID appended, which is a non-existent file. Just wanted to bring this to your attention.

Also, I wanted to know if there maybe is a method to access the output from the profile.csv file? Currently I am using just using runset to locate the folder in which the results are stored and then reading to a dataframe (will probably change `output_dir` to something other then the default when running my actual inference).

## Versions
cmdstan: 2.34.0
cmdstanpy: 1.2.1

**Comment by mitzimorris** [comment]
>  actual output gets merged into a single .csv file without the <chain_ID> appended when running with STAN_THREADS=True

The CmdStanPy docs are wrong and should be changed.

> Also, I wanted to know if there maybe is a method to access the output from the profile.csv file

no, this is an oversight.
