### ISSUE TITLE
cmdstanpy not utilizing all requested cpu's available on a linux cluster

### ISSUE THREAD

**Issue by Garren-H** [stan-dev/cmdstanpy#767]
Hi all. I have ran into some problems running my models on a cluster running CentOS Linux 7 (Core). I am using `reduce_sum` and have compiled my model with `STAN_THREADS` enabled. I am also setting the environmental variable, `STAN_NUM_THREADS` to the number of cores requested, 4 cpu cores in this case.

I am running several independent jobs, using the same model and only changing the input data (currently only using optimization and not sampling). Majority of my jobs uses all requested cpu cores but occasionally I encounter situations where only a single core is utilized (`htop` showing 100% max core utilization). I just wanted to know if anyone might have any idea as to why this occur? Would this be a problem related to cmdstan/cmdstanpy or to the cluster?

### Versions
cmdstan: 2.34.0
cmdstanpy: 1.2.2

**Comment by WardBrian** [comment]
Are you also passing any arguments related to threading to the calls to cmdstanpy in Python? Some of these will take precedence over (or even overwrite) the STAN_NUM_THREADS environment variable

**Comment by Garren-H** [comment]
Thanks for the response Brian. I am not passing any arguments related to this to the call to `CmdStanModel.optimize`. My current call to this is as follows:
```
MAP = model.optimize(data=data, inits=inits2, show_console=True,  iter=1000000, refresh=1000, 
                algorithm='lbfgs', jacobian=False, tol_rel_grad=1e-20, tol_rel_obj=1e-20, tol_param=1e-10,
                tol_grad=1e-20, output_dir=output_dir2, init_alpha=1e-15)
```

And looking at the output during optimization, the `num_threads` parameter is given as `4 (default)`

**Comment by WardBrian** [comment]
If you see “num_threads 4” in the console output as you describe, then it is indeed being passed from the environment and there is nothing to worry about from that perspective. 

The optimizer itself is single threaded, are you using features in your model that you expect to use multiple threads? Otherwise, I would not expect to see full utilization in this case

**Comment by Garren-H** [comment]
I am using `reduce_sum` for my likelihood function, which I would assume would use multiple cores. Looking at majority of my other jobs the cpu utilization varies between 350-400% which is what I would've expected for all my jobs. But a few of these jobs (currently 3 out of 24 jobs) only uses a single core

**Comment by WardBrian** [comment]
Yes, reduce_sum should be using multiple cores in this situation. 

Assuming they all have that output in the console (which rules out config issues or accidentally having a copy of the model which wasn’t compiled with threading support), either you’ve found an issue in Stan’s math library or there is something about your call to reduce_sum which could not be optimally using the cores (usually related to grain size, based on what I’ve seen before)

If you are able to share your model code, I recommend posting on the Stan forums to see if anyone can provide some assistance on the usages of reduce sum to see if that can be improved in a way that uses more of the available resources

**Comment by Garren-H** [comment]
I wouldn't mind sharing my code there, but I do not think this is related to the call to `reduce_sum`. To give some more context, I have 4 different stan models which I use. These models uses matrix factorization and estimate 8 DxN matrices (the parameters of the model). Some models have slightly more parameters due to lower level information being incorporated. For each of the 4 models, I am only changing the value of D=[2, 5, 8, 11, 15, 17]. Hence for each model, there is 6 jobs running per model. For one of these models the model currently still running is that where D=5, whilst the others have completed. Considering this, I would assume that my model setup and calls to `reduce_sum` are correct. The grainsize I am using for all models is 1, which on my laptop indicated that the performance was good, utilizing 350-400% cpu and finishing much faster than the model without `reduce_sum`. The only thing I see that the currently running models have in common is that they are all running on the same node. However, my jobs have previously ran on this node without any issues. Considering that these only occur in a few jobs, and that these jobs run on the same node, would it be logical to conclude that it might be an issue related to the node and not cmdstan/cmdstanpy?

**Comment by WardBrian** [comment]
> Considering that these only occur in a few jobs, and that these jobs run on the same node, would it be logical to conclude that it might be an issue related to the node and not cmdstan/cmdstanpy?

Certainly possible, though if it is consistently the same value of D that triggers this behavior it's possible you're seeing some result of posterior geometry being difficult for specifically that version of the model

**Comment by Garren-H** [comment]
Thanks Brian. These occurred somewhat randomly with different settings of D and different models. I have ran this again, on different nodes, and the cpu utilization is now what was expected. May have just been a node specific issue.
