### ISSUE TITLE
Add functionality to manage cmdstan git repo

### ISSUE THREAD

**Issue by seantalts** [stan-dev/cmdstanpy#8]
I think it would be great if we had convenience functions for users to specify a specific version of CmdStan and have CmdStanPy manage the cmdstan repo itself.

**Comment by ahartikainen** [comment]
So it would use git to handle these changes?

**Comment by mitzimorris** [comment]
adressed by https://github.com/stan-dev/cmdstanpy/pull/39

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/39
