### ISSUE TITLE
investigate performance

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#88]
#### Summary:

Investigate reports that CmdStanPy sampling is slow.

Also investigate why method StanFit.summary() hangs when running
in Python shell interactively, but appears to work when testing
via Jupyter notebook.

#### Description:

Using model `bym2` with data from NYC - model has 12K parameters.

Compare times for CmdStan (shell script), CmdStanPy, and PyStan (latest)

**Comment by ahartikainen** [comment]
`-O1`?

Is it still hanging (`.wait` removed?)

Is it hanging under __name__ == '__main__' block?

**Comment by mitzimorris** [comment]
actually no - not hanging w/ latest PR - many thanks!
just uploaded CmdStanPy version 0.4.1 to PyPI and am now testing

**Comment by ahartikainen** [comment]
Do we have some example models we want to check the performance (some large data, some complex models)?

`lineprofiler` and `lprun` magics are neat with jupyter notebook, so at least we can profile against python parts.

**Comment by mitzimorris** [comment]
here's a performance testing script for datasets on my computer:

```
import os
import time
import numpy as np
import pandas as pd

from cmdstanpy import Model, StanFit
from cmdstanpy.cmdstan_args import SamplerArgs, CmdStanArgs
from cmdstanpy._version import __version__

print(__version__)

bym2_path = os.path.join('bym2')
bym2_stan = os.path.join(bym2_path,'bym2.stan')
bym2_model = Model(stan_file=bym2_stan)
bym2_model.compile()

import time

# bym2_data = os.path.join(bym2_path,'bym2_nyc.data.R')
# start = time.time()
# fit = bym2_model.sample(data=bym2_data, chains=4, cores=4)
# end = time.time()
# print(f'sample time elapsed: {end - start}')
# fit.save_csvfiles(dir=bym2_path, basename='bym2-perftest')

exe = os.path.join(os.path.join(bym2_path,'bym2'))
output = os.path.join(bym2_path, 'bym2-perftest')
sampler_args = SamplerArgs()
cmdstan_args = CmdStanArgs(
    model_name='bym2',
    model_exe=exe,
    chain_ids=[1, 2, 3, 4],
    seed=15542,
    output_basename=output,
    method_args=sampler_args,
    )

bym2_fit = StanFit(args=cmdstan_args, chains=4)
start = time.time()
bym2_fit._validate_csv_files()
end = time.time()
print(f'validate time elapsed: {end - start}')

start = time.time()
bym2_summary = bym2_fit.summary()
end = time.time()
print(f'summary time elapsed: {end - start}')

print(bym2_summary.loc[['beta0', 'betas[1]', 'betas[2]', 'betas[3]', 'betas[4]','sigma', 'rho'],:])

drawset = bym2_fit.get_drawset()
```

**Comment by mitzimorris** [comment]
the above script tests performance of the routines which read the csv files into memory - this has been reworked into a unit test as part of  https://github.com/stan-dev/cmdstanpy/pull/132

to test the performance of the sampler, I ran the bym2 model on the new york city dataset and got timing information via the unix `time` command for total elapsed time.  CmdStan and CmdStanPy ran equally fast - 8m 23s total elapsed time by Unix time command,  CmdStan sampler reported sample time  8m 18 seconds.   PyStan was slower - 9m 1s,  although PyStan reported that the sampler time was 7m 58s - 20 seconds faster - 5% faster - but I don't know how PyStan measures the sampler time.

given this, I don't think that there's any meaningful difference in performance w/r/t sampling between CmdStanPy and PyStan.

compilation times are much faster - possibly due to the fact that CmdStanPy is using 2.20 and PyStan is using 2.19.

**Comment by mitzimorris** [comment]
attaching bym2 model, data, and scripts - 
[bym2.zip](https://github.com/stan-dev/cmdstanpy/files/3711376/bym2.zip)

**Comment by ahartikainen** [comment]
There is huge overhead (which can be seen only with huge data) on PyStan with C++ --> Cython --> Python which is not going anywhere soon (PyStan 2). PyStan 3 will handle this better.

**Comment by mitzimorris** [comment]
> huge data

large inputs or large outputs?

**Comment by ahartikainen** [comment]
Both I guess.

**Comment by mitzimorris** [comment]
for large inputs, next CmdStan release will be include upgrade to rapidjson parser, so loading input data from file should be very fast.

for large outputs, we need binary formats for the output - this is a stan::io issue.  definitely something we need to work on, for all users, all interfaces.

**Comment by brianwa84** [comment]
I've seen hanging on `fit.summary()`. Is it supposed to be fixed? I'm on 0.5.0.

**Comment by brianwa84** [comment]
I guess file size could be a problem :)
```
-rw------- 1 bjp primarygroup 1706907421 Oct 18 13:38 stan-stan_model_0a6c9713b9592e0c740166b860303e0c-Method.SAMPLE-1-se6abym9.csv
-rw-r--r-- 1 bjp primarygroup      14992 Oct 18 13:38 stan-stan_model_0a6c9713b9592e0c740166b860303e0c-Method.SAMPLE-1-se6abym9.txt
-rw------- 1 bjp primarygroup 1706967352 Oct 18 13:38 stan-stan_model_0a6c9713b9592e0c740166b860303e0c-Method.SAMPLE-2-dg1dhdi6.csv
-rw-r--r-- 1 bjp primarygroup      14500 Oct 18 13:38 stan-stan_model_0a6c9713b9592e0c740166b860303e0c-Method.SAMPLE-2-dg1dhdi6.txt
-rw------- 1 bjp primarygroup 1706962905 Oct 18 13:38 stan-stan_model_0a6c9713b9592e0c740166b860303e0c-Method.SAMPLE-3-d95d01ez.csv
-rw-r--r-- 1 bjp primarygroup      15008 Oct 18 13:38 stan-stan_model_0a6c9713b9592e0c740166b860303e0c-Method.SAMPLE-3-d95d01ez.txt
-rw------- 1 bjp primarygroup 1707045935 Oct 18 13:38 stan-stan_model_0a6c9713b9592e0c740166b860303e0c-Method.SAMPLE-4-j6_85p7v.csv
-rw-r--r-- 1 bjp primarygroup      16500 Oct 18 13:38 stan-stan_model_0a6c9713b9592e0c740166b860303e0c-Method.SAMPLE-4-j6_85p7v.txt
```

**Comment by mitzimorris** [comment]
filed issue https://github.com/stan-dev/cmdstan/issues/759

the workaround here would be to get this information by downstream processing of the returned sample via Arviz or other packages.
