### ISSUE TITLE
Add rload function

### ISSUE THREAD

**Issue by maedoc** [stan-dev/cmdstanpy#89]
#### Summary:
Add a `rload` that reads a file generated by `rdump`.

#### Description:
Some of my workflows find use for reading an Rdump file back into memory, e.g. instead of rerunning an expensive script that generates the Rdump file in the first place.  In `pycmdstan` I had a `rload` but it doesn't seem to have survived.

#### Additional Information:
From [here](https://gitlab.thevirtualbrain.org/tvb/pycmdstan/blob/master/pycmdstan/io.py#L39) it reads
```python
def rload(fname):
    """Load a dict of data from an R dump format file.
    """
    with open(fname, 'r') as fd:
        lines = fd.readlines()
    data = {}
    for line in lines:
        lhs, rhs = [_.strip() for _ in line.split('<-')]
        if rhs.startswith('structure'):
            *_, vals, dim = rhs.replace('(', ' ').replace(')', ' ').split('c')
            vals = [float(v) for v in vals.split(',')[:-1]]
            dim = [int(v) for v in dim.split(',')]
            val = np.array(vals).reshape(dim[::-1]).T
        elif rhs.startswith('c'):
            val = np.array([float(_) for _ in rhs[2:-1].split(',')])
        else:
            try:
                val = int(rhs)
            except:
                try:
                    val = float(rhs)
                except:
                    raise ValueError(rhs)
        data[lhs] = val
    return data
```
and may find use within other library functions such as the read_metric function.

#### Current Version:
I just pip installed it, 0.4.1 I think.

**Comment by ahartikainen** [comment]
Does this handle dataframe input?

**Comment by maedoc** [comment]
> Does this handle dataframe input?

Unless `dataframe` means the `A <- structure(1, 2, 3, 4, c=(2,2))` thing, no.  I put this together by inspecting Rdump files meant for Stan models.

**Comment by ahartikainen** [comment]
Ok, just making sure. At least that is what PyStan etc implement.

There are however some dataframe in rdump format in example models, and I have yet tried if that works for CmdStan / RStan. They are not working for PyStan.

**Comment by mitzimorris** [comment]
will add this back in!

**Comment by mitzimorris** [comment]
@ahartikainen - re:
> some dataframe in rdump format in example models

which ones are these?  there's stuff in repo example models that doesn't work - we need to flag them and do some cleanup.

**Comment by ahartikainen** [comment]
For example ARD data

https://github.com/stan-dev/example-models/blob/master/misc/gaussian-process/gp-fit-ARD.data.R

See https://github.com/stan-dev/example-models/issues/152

**Comment by mitzimorris** [comment]
thanks!
that example can only be run via RStan - Stan's parser (`stan::io::dump`) somehow accepts the input file, but the resulting parse is incorrect.   will file an issue against the Stan io module.

**Comment by mitzimorris** [comment]
for CmdStanPy, supporting Rdump data as described in Appendix D of CmdStan manual - not trying to parse R dataframes.   Updated docstring for `rload` function specifying supported variable types.
