### ISSUE TITLE
Gather commands to a list

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#91]
#### Summary:

Calling subprocess needs a list of commands. 
Currently `_run_cmdstan` functions uses `.split` method to create a list from the cmd string.
If one of the items contains whitespace (a path for example) then the subprocess will fail.

https://github.com/stan-dev/cmdstanpy/blob/9dd4b45788e0e59ad2230ec60b854dbf592bf6c4/cmdstanpy/model.py#L566

**Comment by wesbarnett** [comment]
Working on this issue. Thanks!
