### ISSUE TITLE
Add functionality to edit make/local

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/cmdstanpy#94]
#### Summary:
Please provide a short couple sentence summary.

This should be simple and flexible (also foolproof=backup old?)

Functions:
Read -> list of lines (or if multiline cmd, by block?) or dict?
Create <- list of lines or dict?
Write <- list of lines or dict?
Append

Option to change `\` -> `/`, true by default
Option to run shortpath function on Windows?

Helpers for GPU, MPI, threading

Option to run cmdstanpy provided compilers (in future)

#### Description:
Describe the issue as clearly as possible.

edit make/local

#### Additional Information:
Provide any additional information here.

#### Current Version:

latest git master

**Comment by mitzimorris** [comment]
would documentation be sufficient?
is it reasonable to expect that users with GPUs and/or MPI needs are OK editing files directly,
provided there is clear documentation of the makefile and compiler flags?

**Comment by ahartikainen** [comment]
maybe, I just usually don't like to leave my python env, so having some kind of convenience function usually helps.

I think something simple is better than too complicated. So even just printing `make/local` and maybe some kind of replace / append scheme could be enough.

**Comment by mitzimorris** [comment]
not implementing this - although it would be nice -
instead, CmdStanModel object holds dictionary of compiler options.
https://github.com/stan-dev/cmdstanpy/pull/219
